### ISSUE TITLE
vim

### ISSUE THREAD

**Issue by Luffy4321** [iamcco/markdown-preview.nvim#10]

**Comment by Luffy4321** [comment]
请问，vim是不是用您的另外一个版本？

**Comment by Luffy4321** [comment]
用MarkdownPreview没反应markdown-preview.vim可以正常工作

**Comment by iamcco** [comment]
> 请问，vim是不是用您的另外一个版本？

是的

vim 里面 `:mess` 看下输出的什么错误。我猜测是插件没有安装完全。

**Comment by Luffy4321** [comment]
ok,谢谢

**Comment by iamcco** [comment]
还有问题吗？

**Comment by roachsinai** [comment]
Should vim also use this version right now?

**Comment by roachsinai** [comment]
> Note: PLEASE USE markdown-preview.nvim INSTEAD

If not, `Note: for nvim PLEASE USE markdown-preview.nvim INSTEAD` will be better.

**Comment by iamcco** [comment]
yes, vim and neovim both shou

> Should vim also use this version right now?

yes, both vim and neovim

**Comment by roachsinai** [comment]
Thanks.
