### ISSUE TITLE
命令:MarkdownPreview 能启动浏览器，但是是出现的是空白页

### ISSUE THREAD

**Issue by Piller4F** [iamcco/markdown-preview.nvim#100]
命令:MarkdownPreview 能启动浏览器，但是是出现的是空白页
![QQ截图20191116231714](https://user-images.githubusercontent.com/49083286/68995319-43f70e00-08c7-11ea-9def-2c6455514cb0.png)

**Comment by iamcco** [comment]
更新插件试试

**Comment by Piller4F** [comment]
解决了，谢谢谢谢 @iamcco
