### ISSUE TITLE
Issue after updating

### ISSUE THREAD

**Issue by novafacing** [iamcco/markdown-preview.nvim#101]
I get a crash at processTicksAndRejections (internal/process/task_queues.js:80:21)

after updating the plugin. Doesn't seem to be fixed by reinstalling and doing cd app && yarn install either.

**Comment by iamcco** [comment]
paste the error by `mess` command.

**Comment by novafacing** [comment]
Solved,

It was an error that the name of my browser binary had changed, I just didn't realize it.
Sorry to false alarm on that!
