### ISSUE TITLE
Chrome won't start ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [iamcco/markdown-preview.nvim#103]
win 10 
nvim-qt
markdown-preview.vim install ok

When I run the command MarkdownPreview

The Chrome won't start. why is this happened? 

my init.vim
```
"Set GUI"
set guifont=Source\ Code\ Pro:h14
colorscheme molokai

"Set Env"
let g:python3_host_prog='c:\Anaconda3\python.exe'

"Key Map"
nnoremap to :tabo<CR>
nnoremap S S<ESC>
nnoremap <leader>te /^\s*$<CR>
nnoremap p p`]
vnoremap y y`]
nnoremap Y y$
nnoremap <A-x> @:
nnoremap <A-a> <C-o> 
nnoremap <A-d> <C-i>
nnoremap <C-s> :w<CR>
nnoremap qq :x<CR>
nnoremap ww :w<CR>
nnoremap <silent><leader>o :silent !start explorer %:p:h<cr>
nnoremap <leader>wc :%s/<C-r><C-w>//gn<CR>
nnoremap <C-o> i<Enter><Esc>
nnoremap <A-1> :MRU<CR>
vnoremap <A-1> :MRU<CR>
nnoremap <C-A-r> :Restart<CR>
nnoremap <leader>tn :tabnew<CR>
nnoremap <C-n> :tabnew<CR>
nnoremap <C-t> :tabnew<CR>
nnoremap <A-z> :exe "tabn ".g:lasttab<CR>
nnoremap <A-h> <C-w>h
nnoremap <A-l> <C-w>l
nnoremap <A-=> <C-w>=
nnoremap <C-Tab> :exe "tabn ".g:lasttab<CR>
vnoremap gh ^
vnoremap gl $
nnoremap gl $
nnoremap gV `[v`]
nnoremap <S-Enter> o<ESC>
nnoremap cw ce
nnoremap <A-;> A:<ESC>o
nnoremap dtt d/[]">)']<cr>:noh<cr>h 
nnoremap ctp :call SelectContent()<CR>a<C-r>*<ESC>
nnoremap ctt :call SelectContent()<CR>a
nnoremap n nzz
nnoremap N Nzz
nnoremap <leader>gd :g/<C-r><C-w>/d<CR>
nnoremap <leader>vd :v/<C-r><C-w>/d<CR>
vnoremap <leader>gd "zy:g/<C-r>z/d<CR>
vnoremap <leader>vd "zy:v/<C-r>z/d<CR>
nnoremap / /\v
nnoremap <leader>uw :s/\<./\u&/g<CR>:noh<CR>
vnoremap <leader>uw :s/\%V\<./\u&/g<CR>:noh<CR>
nnoremap <C-A-h> <C-w>h
vnoremap <C-A-h> <C-w>h
vnoremap <A-s> :call Compile_Run_Code()<CR>
nnoremap to :tabo<CR>
nnoremap S S<ESC>
nnoremap <leader>te /^\s*$<CR>
nnoremap p p`]
vnoremap y y`]
nnoremap Y y$
nnoremap <A-x> @:
nnoremap <A-a> <C-o> 
nnoremap <A-d> <C-i>
nnoremap <C-s> :w<CR>
nnoremap qq :x<CR>
nnoremap ww :w<CR>
nnoremap <silent><leader>o :silent !start explorer %:p:h<cr>
nnoremap <leader>wc :%s/<C-r><C-w>//gn<CR>
nnoremap <C-o> i<Enter><Esc>
nnoremap <A-1> :MRU<CR>
vnoremap <A-1> :MRU<CR>
nnoremap <C-A-r> :Restart<CR>
nnoremap <leader>tn :tabnew<CR>
nnoremap <C-n> :tabnew<CR>
nnoremap <C-t> :tabnew<CR>
nnoremap <A-z> :exe "tabn ".g:lasttab<CR>
nnoremap <A-h> <C-w>h
nnoremap <A-l> <C-w>l
nnoremap <A-=> <C-w>=
nnoremap <C-Tab> :exe "tabn ".g:lasttab<CR>
vnoremap gh ^
vnoremap gl $
nnoremap gh :call Jump2Head()<CR>
nnoremap gl $
nnoremap gV `[v`]
nnoremap <S-Enter> o<ESC>
nnoremap cw ce
nnoremap <A-;> A:<ESC>o
nnoremap dtt d/[]">)']<cr>:noh<cr>h 
nnoremap ctp :call SelectContent()<CR>a<C-r>*<ESC>
nnoremap ctt :call SelectContent()<CR>a
nnoremap n nzz
nnoremap N Nzz
nnoremap <leader>gd :g/<C-r><C-w>/d<CR>
nnoremap <leader>vd :v/<C-r><C-w>/d<CR>
vnoremap <leader>gd "zy:g/<C-r>z/d<CR>
vnoremap <leader>vd "zy:v/<C-r>z/d<CR>
nnoremap / /\v
nnoremap <leader>uw :s/\<./\u&/g<CR>:noh<CR>
vnoremap <leader>uw :s/\%V\<./\u&/g<CR>:noh<CR>
nnoremap <C-A-h> <C-w>h
vnoremap <C-A-h> <C-w>h
nnoremap <C-A-l> <C-w>l
vnoremap <C-A-l> <C-w>l
nnoremap <A-t> xp
nnoremap <A-S-t> Xp
nnoremap <leader>dkh :g/^[\s\|\r]*$/d<CR>
nnoremap <leader>fbl /\v^\s*$<CR>
nnoremap <silent> <Plug>TransposeCharacters :call NERDComment("n", "Toggle")<CR>
vnoremap <silent> <Plug>TransposeCharacters :call NERDComment("x", "Toggle")<CR>
nnoremap <A-=> magg=G`a
nnoremap <A-n> :noh<CR>
nnoremap ccw <ESC>viw"+y
nnoremap yw yiw 
nnoremap <C-S-t> :call UndoCloseTab()<CR> 
nnoremap cp  <ESC>movip"+y`oh<ESC>
nnoremap yp  yip
nnoremap dp  dip
nnoremap vcp vip:call NERDComment('x',"toggle")<CR>
nnoremap <leader>dir V:s/\\/\//g<CR>:noh<CR>
nnoremap <leader>ex 0v$hy:<C-r>0<CR>
nnoremap <C-A-t> :tabnew<CR>:MRU<CR>1<CR>
nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>
vnoremap <Leader>s y:%s/<C-r>"//g<Left><Left>
nnoremap gx :call HandleURL()<cr>
nnoremap <leader>vm :tabnew<CR>:cd D:\VmWareShare\<CR>:NERDTree<CR>
nnoremap <A-r>      <ESC>:call EditVimrc()<CR>
nnoremap <leader>ee <ESC>:call EditVimrc()<CR>
nnoremap <S-A-h> :tabpre<CR>
nnoremap <S-A-l> :tabnext<CR>
nnoremap <leader>dfc :call DragonflyCmdProcess(0)<CR>
vnoremap <leader>dfc :call DragonflyCmdProcess(1)<CR>
nnoremap <a--1q> :exe "tabn ".g:lasttab<CR>
nnoremap <leader>kew :%s/\v[^a-zA-Z ]//g
nnoremap <leader>rm :%s/\v\r\n/\r/g<CR>
nnoremap <leader>n :call RunNotepad()<CR>
nnoremap z/ :if AutoHighlightToggle()<Bar>set hls<Bar>endif<CR>
nnoremap <leader>sw :%s/\v<<C-r><C-w>>//g<left><left>
nnoremap <esc> <esc>:w<CR>
nnoremap <c-f> <esc>/\v

""
set nu

" 设置着色模式和字体
" if g:isWIN
    " colorscheme molokai
    " " colorscheme solarized
    " " set guifont=monaco:h14
    " set guifont=Source\ Code\ Pro:h14
    " " set guifont=Caecilia\ LT\ Std\ Light:h14
    " set gfw=NSimsun:h14:cGB2312
    " " set guifontwide=YaHei\ monaco\ Hybrid:h14
    " " set guifontwide=微软雅黑:h14:cGB2312
" elseif g:isMAC
    " colorscheme molokai
    " set guifont=monaco:h14
" else
    " colorscheme molokai
    " set guifont=monaco\ 11
" endif

fu! SelectContent()
    " execute "normal ?[[(\"']\%<c-r>=line(\".\")\<cr>l\<cr>\<CR>"
    " find the last quotation mark
    execute "normal ?[\[\(\"']\<CR>" 
    "Store the mark in the varable `b`"
    let b:mc=matchstr(getline('.'), '\%' . col('.') . 'c.')
    if b:mc=="("
        let b:mc=")"
    elseif b:mc=="["
        let b:mc="]"
    elseif b:mc=="{"
        let b:mc="}"
    endif
    "select the content in the quota, here we get the b:mc to mark the symbol
    "we are going to find and replace the content we find"
    execute "normal lv/" . b:mc . "\<CR>hc"
endfunction

" Plugin
"关于状态栏的小配置
"Powerline setting
let g:airline_theme='molokai'
let g:airline_powerline_fonts = 1

"Plugin Config"
let g:mkdp_path_to_chrome = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
    " 设置 chrome 浏览器的路径（或是启动 chrome（或其他现代浏览器）的命令）
    " 如果设置了该参数, g:mkdp_browserfunc 将被忽略

    let g:mkdp_browserfunc = 'MKDP_browserfunc_default'
    " vim 回调函数, 参数为要打开的 url

    let g:mkdp_auto_start = 0
    " 设置为 1 可以在打开 markdown 文件的时候自动打开浏览器预览，只在打开
    " markdown 文件的时候打开一次

    let g:mkdp_auto_open = 0
    " 设置为 1 在编辑 markdown 的时候检查预览窗口是否已经打开，否则自动打开预
    " 览窗口

    let g:mkdp_auto_close = 1
    " 在切换 buffer 的时候自动关闭预览窗口，设置为 0 则在切换 buffer 的时候不
    " 自动关闭预览窗口

    let g:mkdp_refresh_slow = 0
    " 设置为 1 则只有在保存文件，或退出插入模式的时候更新预览，默认为 0，实时
    " 更新预览

    let g:mkdp_command_for_global = 0
    " 设置为 1 则所有文件都可以使用 MarkdownPreview 进行预览，默认只有 markdown
    " 文件可以使用改命令

    let g:mkdp_open_to_the_world = 0
    " 设置为 1, 在使用的网络中的其他计算机也能访问预览页面
    " 默认只监听本地（127.0.0.1），其他计算机不能访问

call plug#begin('c:\Users\Administrator\AppData\Local\nvim\plugged\')
Plug 'iamcco/mathjax-support-for-mkdp'
Plug 'iamcco/markdown-preview.vim'
call plug#end()

```

**Comment by woshichuanqilz** [comment]
![image](https://user-images.githubusercontent.com/11295355/69389052-d3f0e980-0d05-11ea-8b17-51b00b3fd77b.png)
When I start the markdown preview I get error like this, I want to find the python log file, so I run in the command mode
`echo $NVIM_PYTHON_LOG_FILE` but nothing shows out. 
The python path is set correctly, how this happened?

**Comment by iamcco** [comment]
use markdown-preview.nvim instead

**Comment by woshichuanqilz** [comment]
Hi I tried on my manjaro not windows 10 the problem still happens

init.vim file 
> " set to 1, nvim will open the preview window after entering the markdown buffer
" default: 0
let g:mkdp_auto_start = 0

" set to 1, the nvim will auto close current preview window when change
" from markdown buffer to another buffer
" default: 1
let g:mkdp_auto_close = 1

" set to 1, the vim will refresh markdown when save the buffer or
" leave from insert mode, default 0 is auto refresh markdown as you edit or
" move the cursor
" default: 0
let g:mkdp_refresh_slow = 0

" set to 1, the MarkdownPreview command can be use for all files,
" by default it can be use in markdown file
" default: 0
let g:mkdp_command_for_global = 0

" set to 1, preview server available to others in your network
" by default, the server listens on localhost (127.0.0.1)
" default: 0
let g:mkdp_open_to_the_world = 0

" use custom IP to open preview page
" useful when you work in remote vim and preview on local browser
" more detail see: https://github.com/iamcco/markdown-preview.nvim/pull/9
" default empty
let g:mkdp_open_ip = ''

" specify browser to open preview page
" default: ''
let g:mkdp_browser = ''

" set to 1, echo preview page url in command line when open preview page
" default is 0
let g:mkdp_echo_preview_url = 0

" a custom vim function name to open preview page
" this function will receive url as param
" default is empty
let g:mkdp_browserfunc = ''

" options for markdown render
" mkit: markdown-it options for render
" katex: katex options for math
" uml: markdown-it-plantuml options
" maid: mermaid options
" disable_sync_scroll: if disable sync scroll, default 0
" sync_scroll_type: 'middle', 'top' or 'relative', default value is 'middle'
"   middle: mean the cursor position alway show at the middle of the preview page
"   top: mean the vim top viewport alway show at the top of the preview page
"   relative: mean the cursor position alway show at the relative positon of the preview page
" hide_yaml_meta: if hide yaml metadata, default is 1
" sequence_diagrams: js-sequence-diagrams options
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {}
    \ }

" use a custom markdown style must be absolute path
let g:mkdp_markdown_css = ''

" use a custom highlight style must absolute path
let g:mkdp_highlight_css = ''

" use a custom port to start server or random for empty
let g:mkdp_port = ''

" preview page title
" ${name} will be replace with the file name
let g:mkdp_page_title = '「${name}」'

markdown preview installed

> - Finishing ... Done!                            │ 'plugin'
- markdown-preview.nvim: Already installed       │
- nerdtree: Already installed   

And now I ran the command 
`nvim test.md`

And type :MarkdownPreview command the browser dont start either. why this happened? 

Any prepare for this plugin ?

**Comment by iamcco** [comment]
Any error ?

**Comment by woshichuanqilz** [comment]
> Any error ?

When I open the md file and run the command `:MarkdownPreview` the browser won't start

**Comment by iamcco** [comment]
Does have any error when you run `: MarkdownPreview`? check with `:mess` command

**Comment by woshichuanqilz** [comment]
![IMG1](https://user-images.githubusercontent.com/11295355/69518674-1f6bf780-0f93-11ea-8d10-4b5e13220f92.jpg)
![IMG2](https://user-images.githubusercontent.com/11295355/69518676-20048e00-0f93-11ea-95eb-0072a813c1ab.jpg)
here is the `mess` output. I will reply you later this night thank you for your timely reply

**Comment by iamcco** [comment]
The plugin's installation is not complete.

```
" If you don't have nodejs and yarn
" use pre build
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }

" If you have nodejs and yarn
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
```

if use the first one, try `call mkdp#util#install()` other wise go to the plugin direction run `cd app && yarn install`

**Comment by woshichuanqilz** [comment]
> The plugin's installation is not complete.
> 
> ```
> " If you don't have nodejs and yarn
> " use pre build
> Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
> 
> " If you have nodejs and yarn
> Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
> ```
> 
> if use the first one, try `call mkdp#util#install()` other wise go to the plugin direction run `cd app && yarn install` or `cd app && npm install`

Done ! Thank you my bro!
