### ISSUE TITLE
pre build and node is not found 

### ISSUE THREAD

**Issue by williamdwl** [iamcco/markdown-preview.nvim#104]
neovim0.4.3z最新版 使用这个plug
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
:MarkdownPreview 后出错
提示：pre build and node is not found

**Comment by iamcco** [comment]
什么平台，下载 pre build 失败了，重新执行 `:call mkdp#util#install()`试试

**Comment by williamdwl** [comment]
win10平台，重新执行也不行

**Comment by williamdwl** [comment]
win10平台

**Comment by williamdwl** [comment]
> 什么平台，下载 pre build 失败了，重新执行 `:call mkdp#util#install()`试试

win10平台，重新执行还是不行

**Comment by williamdwl** [comment]
重新执行了几次后来可以了，谢谢

**Comment by williamdwl** [comment]
我想问下这个语句什么意思，:call mkdp#util#install()

**Comment by williamdwl** [comment]
win10 平台

**Comment by iamcco** [comment]
就是下载预编译好的执行文件

**Comment by iamcco** [comment]
国内网络环境下载github的东西经常性抽风

**Comment by iamcco** [comment]
如果你有 nodejs 环境可以

`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }` 这么安装

**Comment by williamdwl** [comment]
嗯，readme里我有看到，我想问{}是神马意思

**Comment by iamcco** [comment]
这不就是 vim-plug 的格式

**Comment by williamdwl** [comment]
我想问下这个插件tpope/vim-fireplace
有什么用

**Comment by iamcco** [comment]
不知道哦，我没有使用
