### ISSUE TITLE
无法下载！！！！manjaro最新系统，linux那个13.9mb的包下载不下来

### ISSUE THREAD

**Issue by aizhouyi** [iamcco/markdown-preview.nvim#105]

**Comment by iamcco** [comment]
网络问题我也没办法，如果有 nodejs 可以使用第二种方式

`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }`

**Comment by aizhouyi** [comment]
非常感谢你的回答。目前我已经成功使用上这个插件了
我装了yarn，然后选用你的第二种方案
`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install' }`之后成功了！！！！

开始我就没想到这个。。。。后面我在一个可以突破网络fq的机器上
**手动下载**了这个markdown-preview-linux.tar.gz，我该如何去**手动安装**这个包呢？
我是manjaro的发行版，装yarn一步就完成了，其他的系统部署这个nodejs就麻烦了，能提供一下手动安装的方法吗？谢谢谢谢！！！就我想要存起来做成文档，之后可能会放到网上

**Comment by iamcco** [comment]
这个包解压到 插件的 `app/bin` 目录下就可以了，没有这个目录就建一个

**Comment by aizhouyi** [comment]
ok，好的，非常感谢
