### ISSUE TITLE
浏览器没有反应

### ISSUE THREAD

**Issue by sleeeeeeper** [iamcco/markdown-preview.nvim#106]
我用vim-plug安装这个插件 然后yarn也安装成功了 filetype也是markdown 但执行命令后没有反应 也不报错 很迷惑

**Comment by sleeeeeeper** [comment]
@iamcco 大佬能不能给点意见 我已经折腾一个星期的插件了QAQ

**Comment by iamcco** [comment]
`:mess` 查看报啥错了

**Comment by sleeeeeeper** [comment]
啥报错也没有&nbsp; 空的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"年糕小豆汤"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月1日(星期天) 晚上11:22
收件人:&nbsp;"iamcco/markdown-preview.nvim"<markdown-preview.nvim@noreply.github.com&gt;;
抄送:&nbsp;"111"<2290085762@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iamcco/markdown-preview.nvim] 浏览器没有反应 (#106)




:mess 查看报啥错了

**Comment by iamcco** [comment]
怎么安装配置的？设置 `let g:mkdp_echo_preview_url = 1` 看下有没有显示 url，如果显示打开能不能访问

**Comment by eternalcyan** [comment]
如果你是WIN7系統,看看我[之前發的貼](https://github.com/iamcco/markdown-preview.nvim/issues/90)也有類似安裝失敗無法使用的問題.
如果不是,當我沒說.

**Comment by bon-ami** [comment]
I have node.js but not yarn, so used the Plug line for prebuilt.
:mess shows Cannot find module 'tslib' from line 3 of nvim\plugged\markdown-preview.nvim\app\lib\app\index.js

**Comment by iamcco** [comment]
@bon-ami prebuilt download is not complete

if you have nodejs use `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & npm install'  }`

**Comment by oeeee** [comment]
@iamcco 大佬我也是这样，能返回url然后能手动打开，但是不会自动弹窗，安装方式用的是Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }，同样没用

**Comment by iamcco** [comment]
@oeeee 什么系统？关于这个插件的所有配置？

**Comment by walterhoson** [comment]
@iamcco 开发者你好：
我也遇到同样的问题，:markdownPreview无法调用浏览器，设置 `let g:mkdp_echo_preview_url = 1`无法看到url，也同样没有拉起浏览器。
环境为manjaro，nvim，chromium，都为最新版本

**Comment by iamcco** [comment]
@walterhoson `:checkhealth` 看下信息

**Comment by walterhoson** [comment]
抱歉，最近才有时间处理这个问题，以下是我的:checkhealth 信息

![image](https://user-images.githubusercontent.com/22598129/71628660-f266d080-2c33-11ea-9004-c2fb00a703a7.png)
![image](https://user-images.githubusercontent.com/22598129/71628675-06aacd80-2c34-11ea-9cba-deeda2954ead.png)

python3环境和nodejs环境都有

**Comment by walterhoson** [comment]
卸载插件，重新安装python以及nodejs，再安装插件，似乎已经正常工作了

**Comment by rogerlin0330** [comment]
> @bon-ami prebuilt download is not complete
> 
> if you have nodejs use `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & npm install' }`

亲测可用，我是通过:checkhealth发现没有装Nodejs Provider，所以先执行：

`npm install -g neovim`

然后再用

`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & npm install' }`

后解决问题。

如果是用SpaceVim，则可以

`cd ~/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim/app

然后执行

`npm install`

**Comment by X-Corde-Official** [comment]
@iamcco 
啊啊大佬我的也不行，跑了healthcheck跟上面的那个healthcheck几乎一模一样，系统是macOS，下面没有显示URL也没有调起浏览器，就是输入了:MarkdownPreview以后什么都没有发生

**Comment by iamcco** [comment]
@X-Corde-Official 执行 `:MarkdownPreview` 然后 `:mess` 查看有啥错误

**Comment by X-Corde-Official** [comment]
<img width="820" alt="截屏2020-02-12下午11 50 21" src="https://user-images.githubusercontent.com/56668763/74351685-6fb86000-4df2-11ea-98a1-8e2d4f18c071.png">
@iamcco

**Comment by X-Corde-Official** [comment]
已搞定，谢谢大佬

**Comment by Qnurye** [comment]
`cd ~/.vim/plugged/markdown-preview.nvim/app`  
`cnpm install`  
这是我的解决方法, 环境 : archlinux + nvim + Plug
*如果问题解决了就把这个issue close了吧*

**Comment by SimonYoungCN** [comment]
![无标题](https://user-images.githubusercontent.com/64118289/174216644-bb782289-2f94-40d3-a941-284ef954dc6f.png)
我的系统是Windows10,安装了插件后输入命令无反应(闪一下就没有了),也不能返回url,错误报告如上图所示,请求帮助,谢谢.
