### ISSUE TITLE
TOC and chart preview didn't work

### ISSUE THREAD

**Issue by zoumi** [iamcco/markdown-preview.nvim#108]
![image](https://user-images.githubusercontent.com/5162901/70384555-20e9e680-19bb-11ea-996c-de4d9164bdb6.png)

I'm new to markdown.My PC enviroment : windows7 64bit  firefox 71.0 gvim8.1 64bit

**Comment by iamcco** [comment]
can not reproduce, paste your markdown content here

**Comment by zoumi** [comment]
`
    ${toc}, [[toc]], [toc], [[_toc_]]

    ``` chart
    {
      "type": "pie",
      "data": {
        "labels": [
          "Red",
          "Blue",
          "Yellow"
        ],
        "datasets": [
          {
            "data": [
              300,
              50,
              100
            ],
            "backgroundColor": [
              "#FF6384",
              "#36A2EB",
              "#FFCE56"
            ],
            "hoverBackgroundColor": [
              "#FF6384",
              "#36A2EB",
              "#FFCE56"
            ]
          }
        ]
      },
      "options": {}
    }
    ```

    <div class="solid">
    &emsp;This is a Box
    </div>

    ``` plantuml
    Bob -> Alice : hello
    ```

    $\sqrt{3x-1}+(1+x)^2$

    $$\begin{array}{c}

    \nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &
    = \frac{4\pi}{c}\vec{\mathbf{j}}    \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\

    \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\

    \nabla \cdot \vec{\mathbf{B}} & = 0

    \end{array}$$

    ``` mermaid
    gantt
        dateFormat DD-MM-YYY
        axisFormat %m/%y

        title Example
        section example section
        activity :active, 01-02-2019, 03-08-2019
    ```

    ``` sequence-diagrams
    Andrew->China: Says
    Note right of China: China thinks\nabout it
    China-->Andrew: How are you?
    Andrew->>China: I am good thanks!
    ```

    ``` flowchart
    st=>start: Start|past:>http://flowchart.js.org[blank]
    e=>end: End|future:http://flowchart.js.org/
    op1=>operation: My Operation|past
    op2=>operation: Stuff|current
    sub1=>subroutine: My Subroutine|invalid
    cond=>condition: Yes
    or No?|approved:>http://flowchart.js.org/
    c2=>condition: Good idea|rejected
    io=>inputoutput: catch something...|future

    st->op1(right)->cond
    cond(yes, right)->c2
    cond(no)->sub1(left)->op1
    c2(yes)->io->e
    c2(no)->op2->e
    ```
`

**Comment by iamcco** [comment]
You should only use one of `${toc}, [[toc]], [toc], [[_toc_]]` format. Update the plugin to fix chart preview.

**Comment by zoumi** [comment]
Thank you! Will you add support for [flowchart](http://flowchart.js.org)

**Comment by iamcco** [comment]
Maybe when I have time, and PR always welcome.
