### ISSUE TITLE
建议从源码库移出app/out，可以作一个带生成结果的分支

### ISSUE THREAD

**Issue by zhaozg** [iamcco/markdown-preview.nvim#110]
app/out是一个生成目录，不应该被放到代码库中，每次合并官方分支我这边都会后合并冲突。
希望你那边考虑一下

thanks your great markdown-preview.nvim.

**Comment by iamcco** [comment]
现在把 app/out 移到一个新的分之影响太大，之前安装的所有人都得更改安装配置。

**Comment by iamcco** [comment]
我得理解没错的话你合并冲突应该都是 app/out 目录下的文件，合并后删掉 build 一下生成的就是最新的文件

**Comment by zhaozg** [comment]
或者可以反过来，新建个分支不包含  app/out ，我这边app/out是自己生成的，会合拉下来的版本冲突

**Comment by jian-ke** [comment]
> 或者可以反过来，新建个分支不包含 app/out ，我这边app/out是自己生成的，会合拉下来的版本冲突

I modify index.jsx, and need to regenerate out, but I dont know how..
could you give me a hint about how to do this?
