### ISSUE TITLE
Size of Picture

### ISSUE THREAD

**Issue by BenSYZ** [iamcco/markdown-preview.nvim#111]
I want to control the size of the picture. I have tried in this way `![alt](path =30x30)`, but it doesn't work. Could you add this function? Or if the function has already existed, could you tell me how to control its size ?

**Comment by iamcco** [comment]
Not support for now.

**Comment by MrSauna** [comment]
I might be barking up the wrong tree but I'm having difficulties since no pandoc markdown flavor supports this format.  

I'm suggesting also supporting https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html%23raw-tex#Images

`![my caption](./figures/myimage.png){ width=250px }`

**Comment by iamcco** [comment]
If it's new feature please open new issue.
