### ISSUE TITLE
implementation question

### ISSUE THREAD

**Issue by boulderob** [iamcco/markdown-preview.nvim#112]
just to confirm.  after browsing the source, it appears that this plugin doesn't rely on any external npm pkg browsersync solution to reload the compiled markdown to html document in a browser is that correct?  what i mean is it looks like you coded and supply your own simple server to handle this task and your vim plugin simply communicates with your own custom server to push the changes to the browser right?

thx

**Comment by iamcco** [comment]
You are right.

**Comment by boulderob** [comment]
ok thx
