### ISSUE TITLE
internal url links with spaces do not work on macs

### ISSUE THREAD

**Issue by pdoak** [iamcco/markdown-preview.nvim#12]
I am using nvim 0.3.1 on a mac and internal url links do not work if they contain a space. This link:

`![Close High Crosses](/images/Screenshot%202019.png) `
does not work. Filenames that don't contain a space appear to work as expected.

I have also tried: 
`![Close High Crosses](/images/Screenshot\ 2019.png) `
but this does not work either.

Also the link paths have to be relative to the folder that the markdown file is in. Is it possible to use the full path?

**Comment by iamcco** [comment]
fix, space in url is not allow for markdown. so use `\` if it contain space.

and `![Close High Crosses](/images/Screenshot\ 2019.png) ` is right, relative and absolute path are all support. update and have a try.

**Comment by pdoak** [comment]
Using `\` does not seem to work for me. If I use
`![Close High Crosses](/images/Screenshot\ 2019.png)` in my markdown document,  I get this error:
`[markdown-preview.vim] uncaught exception: Error: ENOENT: no such file or directory, open '/Users/xxx/images/Screenshot%5C%202019.png'`

Am I doing something wrong?

**Comment by iamcco** [comment]
have you udpate to the latest version? relative and absolute path should work
