### ISSUE TITLE
Is there any way to use the mhchem extension for KaTeX?

### ISSUE THREAD

**Issue by DavidHWhite** [iamcco/markdown-preview.nvim#121]
KaTeX has an (extension for typesetting chemical equations)[https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem/]. Is there any way for this to be supported in this plugin, or is this a feature that could be added? I'm trying to use this plugin as part of my workflow for writing chemistry notes, and support for the mhchem LaTeX package within KaTeX math blocks would be incredibly useful, but as of yet I haven't found a way to do so.

**Comment by iamcco** [comment]
Not support yet
