### ISSUE TITLE
[Enhancement] Theme the preview from .Xresources or pywal

### ISSUE THREAD

**Issue by GideonWolfe** [iamcco/markdown-preview.nvim#126]
I have been tinkering with this for some time, but basically the idea is to reference colors generated by pywal, which can be imported with `@import url('file:///home/username/.cache/wal/colors.css');`.

These colors would be used as the background, foreground and highlighting, so the markdown preview would look almost like a native application running on the system.

I can't seem to figure out how to edit these properties though. I can change the background color and stuff when changing the file set as `mkdp_markdown_css`, but I don't want to override any of the other markdown stylings. 

There seem to be variables for "background color" and such in all of the CSS files, I just am not sure what to edit to get the correct results.

**Comment by iamcco** [comment]
" use a custom markdown style must be absolute path
let g:mkdp_markdown_css = ''

" use a custom highlight style must absolute path
let g:mkdp_highlight_css = ''

The markdown style file https://github.com/iamcco/markdown-preview.nvim/blob/master/app/_static/markdown.css

The highlight style file https://github.com/iamcco/markdown-preview.nvim/blob/master/app/_static/highlight.css

**Comment by iamcco** [comment]
You can copy and change the two style file to change preview page style.

**Comment by GideonWolfe** [comment]
That's what I was trying to do, just without success. For example, I changed all the `background-color` attributes in the markdown.css file, yet no colors on the page were changed.

I really only want to change the background/foreground colors, which seems like it would be in `page.css`, but there is no configuration option for that.

**Comment by iamcco** [comment]
markdown css file is link after page css file. so you can change any rules that page css defined.

**Comment by GideonWolfe** [comment]
The feature has been completed and rolled into [vim.reaper](https://github.com/GideonWolfe/vim.reaper). 

I had to trick the plugin into hosting the `colors.css` file thinking it was `highlights.css`, because otherwise no browser could see it. I transferred the `CSS` for the highlighting into the `markdown.css` file.
