### ISSUE TITLE
Install still broken with dein?

### ISSUE THREAD

**Issue by msphinct** [iamcco/markdown-preview.nvim#130]
Hi, 

First, I just want to say, I LOVE this plugin.  Easily one of my all time favorites! So I am pretty comfortable using it.  And until recently, I've never had an issue.

I reported this to the maintainer of SpaceVim, who I believe handles 'dein' too.  I've been having issues with this installing via 'dein' for a while now. 
So, I'm still having to go manually into ~/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim/

and run "cd app; yarn install" by hand, even though it appears to work initially.  I'm thinking maybe 'dein' thinks there's an error, but it's actually a warning, so it's not doing it unless I manually do it. It does NOT throw and error. You have to try MarkdownPreview to 'not' see the error, but it's in messages.

Here's the messages I get when I run MarkdownPreview:

- initial error when I install:

 [ SpaceVim ] [16:16:56] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 3 

- After I restart vim and run :MarkdownPreview on a .md file:

 internal/modules/cjs/loader.js:583                                                                                                                
    throw err;                                                                                                                                    
    ^                                                                                                                                             
Error: Cannot find module 'msgpack-lite'                                                                                                          
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)                                                                   
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)                                                                              
    at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                     
    at require (internal/modules/cjs/helpers.js:22:18)                                                                                            
    at Object.<anonymous> (/home/testuser/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim/app/lib/app/preloadmodules.js:7:21)       
    at Module._compile (internal/modules/cjs/loader.js:689:30)                                                                                    
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                                      
    at Module.load (internal/modules/cjs/loader.js:599:32)                                                                                        
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                                                      
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

- Then I cd to the plugin dir and run the same command 'dein' does, but I have to do it by hand:

 yarn install
yarn install v1.21.1
warning package.json: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning ../package.json: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
Done in 0.48s.

- As you can see, by the output it now works:  
opening 'http://127.0.0.1:8259/page/1' ... done! (xdg-open)  

Like I mentioned early, I think it's 'dein' not liking the warnings, and I did do an issue on their github, but they suggest I ask you.  [issue 3323 - SpaceVim](https://github.com/SpaceVim/SpaceVim/issues/3323)

Please let me know if there is anything I can do to provide further assistance.  Thanks!

Pete

**Comment by iamcco** [comment]
Is it work?

https://github.com/iamcco/markdown-preview.nvim/pull/128

**Comment by msphinct** [comment]
No, it's still broken for SpaceVim, because of the warnings.  So, it's fixed for dein, but NOT when it's run from within SpaveVim.
If there's a way to suppress the warnings, it might solve it, but it' still broken.
So, the author has reopened the issue too.
Thanks! Please let me know if there is anything I can do to help.

**Comment by iamcco** [comment]
The warning should not broken the installation

**Comment by msphinct** [comment]
Right, I agree with you completely.  However, I am not a vim plugin/editor developer.  I just like your plugin and I like SpaceVim/dein.  I figured out a work around for myself when I first realized this a couple weeks ago.  After it hadn't been fixed in SpaceVim, I realized NO ONE was using your plugin with SpaceVim.  I hated to see that, because I like your projects.

So, after I figured out how to reproduce and work around the issue, I wrote their developer.  Of course, as everyone does, they immediately blamed your plugin...ugh :(  Then they fixed it for dein, but NOT SpaceVim. They are NOW working on a fix, but it's broken in the mean time.

Right now, people using SpaceVim CANNOT use your plugin unless they have the initiative and  knowledge to figure out a fix.  Most people will just start using some other plugin.  If it were me, I'd try to be as helpful as possible so more people would use  my code.

I don't like being the middle man---I'm too old for that.  I've been doing this too long.  I like solutions.

My first thought was to just stop using your plugin and find another one.  However, as I said, I decided to step in and help.  So, I've done what I can. You might want to consider helping him work through this----not me, as I am not a vim programmer.  I'm a unix admin, so I can figure something out, if you all don't want to support each other.

You know, enthusiasm is hard to find.  Friendly enthusiasm is even harder.  That's all I am offering.  I'll let you work it out.  I was just trying to help.

Please let me know if there is anything I can do.

**Comment by iamcco** [comment]
I want to help, but I'm not a spacevim user and either dein user, and even don't know how to install plugin using spacevim. So it's quite beyond my ken to figure it out.

**Comment by msphinct** [comment]
LOL, I completely understand brother.  What I'm asking is that you could possibly quite the errors, so that people could continue using it in SpaceVim, while the author is fixing it. Right now, your plugin is the default 'markdown' plugin for that editor, and it's how I discovered it. It's quite frankly what turned me onto SpaceVim. I'd love to see that continue, as more people will discover it, if it installs automatically as it was doing up until a few weeks ago.

Would it be possible to figure out what's causing these warnings and get it to stop? 

yarn install v1.21.1
warning package.json: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning ../package.json: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
warning markdown-preview.vim@0.0.1: Invalid bin entry for "markdown-preview.vim" (in "markdown-preview.vim").
Done in 0.52s.

I know next to nothing about 'yarn' or node.js. Is that an easy fix for you?

Thoughts?

Thanks!!

Pete

**Comment by iamcco** [comment]
Update and have a try. It should not have the warning anymore, but I don't think it's much help.

**Comment by msphinct** [comment]
Yup, it's all clean on  your end. I tried in vim an neovim---still no joy.  
I appreciate you trying that.

So, for some reason, SpaceVim doesn't appear to be installing some dependencies, that are pulled in when you run 'yarn install' by hand.

Any ideas, what might be happening?  Up until now, my bet was that the 'warnings' were causing dein to honk, but it appears it's not the case at all.   Thoughts?  See below.  Thanks again!


internal/modules/cjs/loader.js:670                                                                                                                     
    throw err;                                                                                                                                         
    ^                                                                                                                                                  
Error: Cannot find module 'msgpack-lite'                                                                                                               
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)                                                                        
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)                                                                                   
    at Module.require (internal/modules/cjs/loader.js:723:19)                                                                                          
    at require (internal/modules/cjs/helpers.js:14:16)                                                                                                 
    at Object.<anonymous> (/home/pete/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim/app/lib/app/preloadmodules.js:7:21)                
    at Module._compile (internal/modules/cjs/loader.js:816:30)                                                                                         
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)                                                                           
    at Module.load (internal/modules/cjs/loader.js:685:32)                                                                                             
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)                                                                                   
    at Module.require (internal/modules/cjs/loader.js:723:19)

**Comment by msphinct** [comment]
Hey, I think I see what might be going on.  I'm slowing figuring out how to write vimscript.  It appears he's not using 'yarn install' like he was.  I might be able to work out a fix when I get some time in the coming week.  I REALLY appreciate your response!

When developers handle things like you just did, it makes it all the more likely to attract more users--good vibes.  I dig good vibes!  Thanks brother.  I hope you have an amazing day.  I'll let you know when we get it fixed!

**Comment by msphinct** [comment]
Hey, fyi, I found the issue, it's how vim is now using 'npm' instead of yarn. :(

if executable('npm')                                                                                                                                                    
  ┊ let s:node_pkgm = 'npm'                                                                                                                                               
  elseif executable('yarn')                                                                                                                                               
  ┊ let s:node_pkgm = 'yarn'                                                 if executable('npm')                                                                                                                                                    
  ┊ let s:node_pkgm = 'npm'                                                                                                                                               
  elseif executable('yarn')                                                                                                                                               
  ┊ let s:node_pkgm = 'yarn'                                                                                                                                              
  else                                                                                                                                                                    
  ┊ let s:node_pkgm = ''                                                                                                                                                  
  ┊ call SpaceVim#logger#error('npm or yarn is required to build iamcco/markdown-preview and neoclide/vim-node-rpc')                                                      
  endif                                                                                                                                                                   
  call add(plugins, ['iamcco/markdown-preview.nvim',                                                                                                                      
  ┊ ┊ ┊ \ { 'on_ft' : 'markdown',                                                                                                                                         
  ┊ ┊ ┊ \ 'depends': 'open-browser.vim',                                                                                                                                  
  ┊ ┊ ┊ \ 'build' : 'cd app & ' . s:node_pkgm . ' install' }])                                                                                                            
  if !has('nvim')                                                                                                                                                            
  else                                                                                                                                                                    
  ┊ let s:node_pkgm = ''                                                                                                                                                  
  ┊ call SpaceVim#logger#error('npm or yarn is required to build iamcco/markdown-preview and neoclide/vim-node-rpc')                                                      
  endif                                                                                                                                                                   
  call add(plugins, ['iamcco/markdown-preview.nvim',                                                                                                                      
  ┊ ┊ ┊ \ { 'on_ft' : 'markdown',                                                                                                                                         
  ┊ ┊ ┊ \ 'depends': 'open-browser.vim',                                                                                                                                  
  ┊ ┊ ┊ \ 'build' : 'cd app & ' . s:node_pkgm . ' install' }])                                                                                                            
  if !has('nvim')                                                               
I'll get with the developer and get it working.  Thanks again!

**Comment by iamcco** [comment]
It should work with npm too
