### ISSUE TITLE
Plugin not working since I updated the plugin

### ISSUE THREAD

**Issue by Nevimmu** [iamcco/markdown-preview.nvim#136]
First of all, amazing plugin it's really what I needed!  

The plugin worked well until today : when I opened a markdown file the preview started normally without any issue.
Now when I open a markdown file this alert shows : 
 ```at processTicksAndRejections (internal/process/task_queues.js:85:21)```
And if I try to run ```:MarkdownPreview``` it shows 
``` TypeError: Cannot read property 'openBrowser' of undefined  ```
```TypeError: Cannot read property 'refreshPage' of undefined ```

The issue could come from the latest update since I updated all my plugins yesterday. I tried to uninstall the plugin, even deleting the files to reinstall didn't work

**Comment by iamcco** [comment]
Use `:mess` to show all error message.

**Comment by Nevimmu** [comment]
I get this :
```
[markdown-preview.vim] uncaught exception: Error: listen EADDRINUSE: address already in use 127.0.0.1:8277
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at doListen (net.js:1496:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

I've been able to fix it, I don't remember why I fixed the port to 8277 but I now deleted the line and everything works perfectly. I didn't know you could use ```:mess```.  

Thanks for the help!

**Comment by jgarl** [comment]
> I get this :
> 
> ```
> [markdown-preview.vim] uncaught exception: Error: listen EADDRINUSE: address already in use 127.0.0.1:8277
>     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
>     at listenInCluster (net.js:1357:12)
>     at doListen (net.js:1496:7)
>     at processTicksAndRejections (internal/process/task_queues.js:85:21)
> ```
> 
> I've been able to fix it, I don't remember why I fixed the port to 8277 but I now deleted the line and everything works perfectly. I didn't know you could use `:mess`.
> 
> Thanks for the help!

I'm having same problem here, what did you do to solve it?
