### ISSUE TITLE
安装不了的朋友来看&how to install it on vim8.1 and  later

### ISSUE THREAD

**Issue by happysmile12321** [iamcco/markdown-preview.nvim#138]
0.vim8.0不能安装这个插件。vimm8.1~往后可以，但你得vim --version|grep python
看是否支持python.建议你用neovim。neovim是一个vim的分支，之所以这样是因为vim太老了，bug太多，不好维护，neovim相当于代码的重构。如果你是程序员你应该懂的，拿到别人的烂代码的感受。
我用的国产的deepin，直接sudo apt install neovim就可以了。根据你的Linux选择你的安装方式。
1,把你的plug目录下这个插件删了
2.在你的vimrc配置文件中添加  Plug 'iamcco/markdown-preview.nvim'
(注意单引号不要写错!!!)
3.source一下你的vimrc--也就是刷新vimrc文件(不会可以重启)
4.打开vim，运行pluginstall,等待完成。
5.安装yarn 。注意，yarn不能直接用apt install yarn.
如果直接apt安装yarn,那么装的是cmdyarn.找个教程安装yarn。如果不行，那就更新yarn的版本。再不行--我是直接编译，编译好配置到环境变量(编译后默认会在/usr/bin/yarn)。在最后添加!!!
export PATH=$PATH:/usr/bin/yarn
如果你还配置过java的,你不用管，直接扔到最后就好了。
这个$PATH呢，是指刷新到环境变量。就像你int path = 1;以后你还想追加一个，那你就path = 2;
然后source一下你的profile。source ~/etc/profile
注意：环境变量配错可能导致你用不了命令比如ls。
6.安装完成之后打开XXX.md格式的文件之后就可以了。
emmm~再补一个坑。
我是vim-plug安装的。vim-plug的原理是什么呢？vim-plug主要依赖一个plug.vim的文件。这个是vim可以执行的一个脚本文件，以前有个编程语言叫vimscript。vim-plug所有的功能都在这个脚本文件中执行了。vim没有官方的插件库，这也是我推荐你们用neovim的原因，neovim更容易安装插件。
话题扯回来，国内不能访问raw.github.XXX其实没有多大关系，你只需要把plug.vim搞过来放到和你vim/neovim配置同级的文件夹autoload下就可以了。autoload我猜应该是每次vim启动都会默认加载里面的脚本。注意，我用wget 那个网址下载的plug.vim其实不对，wget是把整个html抓过来，改名成plug.vim。你打开看看其实全是html标签。
7.希望能给来者以帮助。
8.我不明白的是为什么还要执行yarn命令。。。。不过管他呢。希望作者别生气哈，我只是来踩个坑。还是很感谢你为我们开发这个一个插件的。

**Comment by happysmile12321** [comment]
再来踩一个坑，希望警惕后人。
我的系统是deepin，没错，就是那个国产的发型版。直接apt install neovim的话版本好像有点低，因此不能安装。貌似是不支持某些语法，注意，在安装时就不支持。
我不知道网络的问题。如果你是中国移动，请一定换成中国电信的网络，无论是wifi或有线!!!垃圾移动。
至于vim怎么安装，大家可以看我写的https://blog.csdn.net/u010563350/article/details/104214356
最下面有关于vim的介绍。包括怎么安装。注意，你编译vim的时候就不要克隆github了，直接克隆国内的gitee吧。这样快些。然后就是你可以加上一个--depth 1的选项在git clone后面。这个选项默认会克隆离这个项目最近一次的更新。因此作者以前成年累月的历史版本你就不用管了。
只克隆master就可以。然后就是我现在的vim是支持python的。我给你们看看我的输出:
```
happysmile@happysmile-PC:~/Desktop$ vim --version | grep python
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
happysmile@happysmile-PC:~/Desktop$ 
```
反正不管后面是什么，只要是python就可以了。可以看到我python2,python3都支持的。
你一定要小心，最好一次编译vim成功，因为你sudo make install的时候它不光编译，它还安装。
也就是把你编译的东西送到系统比如/usr/bin下面。这样我们不方便找到。所以你最好一次编译成功。
编译不成功我也有教怎么再编译的。
emmm....
vim的门槛虽然高，但并不是高不可攀。我的平常都是ranger配合vim来打造自己的记笔记的利器。emmm。
你会发现在折腾vim的过程中学到了好多。别放弃，都用linux了，就不要再想windows那个渣渣系统了。
总的来说，你要确保yarn安装正确，(不是cmdyarn)。作者在Plug后面那个多写的东西的意思也是用yarn安装。yarn是先从服务器下载编译好的二进制文件，然后再进行一些配置。反正进入~/.vim/Pluggin/markdown-preview/app下面执行yarn就对了。
网络不好可以Ctrl C然后再执行。
加油，奥利给!!!

**Comment by iamcco** [comment]
纠正一点，这个插件不需要 python 支持的。

如果使用的是 vim-plug 插件管理器

1. `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }`
2. `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }`

这两种安装方法都可以，yarn 也可以换成 npm。

第一种方法适合没有安装 nodejs 的情况，会根据系统下载打包好的二进制执行文件。

**Comment by happysmile12321** [comment]
恩。总结来说呢，如果想离线安装，就在自己的软件管理器的plug下面用git clone https://gitee.com/then_then/markdown-preview.nvim.git --depth 1
。然后在.vimrc或initvim中声明plug--相当于注册(必须要有:就用第一种)。然后进入markdown-preview.nvim的目录，找到app，进入并执行yarn。
在线安装是找托管在github上的二进制文件。其实就是通过vim-plug安装。
这种方式安装太慢。不建议。
