### ISSUE TITLE
Server startup failed

### ISSUE THREAD

**Issue by mrxiaozhuox** [iamcco/markdown-preview.nvim#139]
After I installed the plugin, preview could not be started.
Error Message:
Error detected while processing function mkdp#util#open_preview_page[6]..mkdp#rpc#start_server[2]..<SNR>87_start_vim_node_rpc[4]..mkdp#nvim#rpc#start_server:
line   25:
E475: Invalid argument: env

What do I need to do next ?

**Comment by iamcco** [comment]
What's your vim version ?

**Comment by jackcooperusesvim** [comment]
I have the same issue. I am using Neovim on a M1 Macbook Air. What was the solution?
