### ISSUE TITLE
关于例子的问题

### ISSUE THREAD

**Issue by FlamesCN** [iamcco/markdown-preview.nvim#141]
兄弟，感谢做出这么好用的国人VIM插件，比另外个几K星的强大很多。
例子里面我把dot:下面代码块贴进去，显示的是源码，viz.js也装了，怎么用？还有那个toc。

**Comment by iamcco** [comment]
文档更新了，toc 那个逗号分隔的几个只需要写一个

![image](https://user-images.githubusercontent.com/5492542/75364887-60a7d680-58f7-11ea-8cae-8584942c6aef.png)

**Comment by iamcco** [comment]
没问题先关闭了，有问题再打开
