### ISSUE TITLE
sudo后无法使用插件

### ISSUE THREAD

**Issue by lazyshawn** [iamcco/markdown-preview.nvim#142]
我用sudo nvim打开md文件后，运行这个插件没反应。但是正常打开的时候，插件运行没问题。我想请问下是什么问题呢？

**Comment by iamcco** [comment]
不懂，其他插件正常么？sudo 后的配置是一样的么

**Comment by lazyshawn** [comment]
@iamcco  其他插件正常。也没报错，就是运行没反应

**Comment by iamcco** [comment]
运行命令后，`:mess` 看下有啥错误信息

**Comment by lazyshawn** [comment]
@iamcco 什么信息都没有返回

**Comment by lazyshawn** [comment]
@iamcco  我好像找到问题了。我用的ubuntu，不能用root权限打开firefox，我改用chrome就可以正常使用了。不知道其他系统会不会有这类问题。

**Comment by iamcco** [comment]
一般不再root下操作
