### ISSUE TITLE
[Feature request] - Disable filename option

### ISSUE THREAD

**Issue by gonzolively** [iamcco/markdown-preview.nvim#147]
Blame it on my ocd, but I find the file title (and the subsequent broken image link) at the top of the page distracting to my beautiful docs (see screenshot). I'd love to have a feature toggle on this.

![screenshot](https://i.imgur.com/Tyohcrl.jpg)

Possible example:
`let g:mkdp_filename_enable = 0
`
or
`let g:mkdp_filename_enable = false
`

**Comment by znculee** [comment]
@iamcco Thank you for your great plugin and @evan1533 thank you for your contribution. I appreciate this disable filename option much, but when I call `MarkdownPreview` I do see the header will appear first and then disappear seconds later. Could you refine your code to prevent the filename header from popping up in the very beginning after calling `MarkdownPreview`?

**Comment by iamcco** [comment]
Should be fixed now.
