### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by vinaysb** [iamcco/markdown-preview.nvim#148]
Hello, when I try to open the markdown preview (using `:MarkdownPreview` command) on my mac it doesn't seem to do anything.

This is my config, could you please tell me what I am doing wrong?

```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#begin('~/.vim/plugged')

" Example plugin
" " Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
" Plug 'junegunn/vim-easy-align'

" Pre-build of vim markdown preview
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }

call plug#end()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" -> Plugin (Markdown-Preview): Config & Mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" set to 1, nvim will open the preview window after entering the markdown buffer
" default: 0
let g:mkdp_auto_start = 1

" set to 1, the nvim will auto close current preview window when change
" from markdown buffer to another buffer
" default: 1
let g:mkdp_auto_close = 1

" set to 1, the vim will refresh markdown when save the buffer or
" leave from insert mode, default 0 is auto refresh markdown as you edit or
" move the cursor
" default: 0
let g:mkdp_refresh_slow = 0

" set to 1, the MarkdownPreview command can be use for all files,
" by default it can be use in markdown file
" default: 0
let g:mkdp_command_for_global = 1

" set to 1, preview server available to others in your network
" by default, the server listens on localhost (127.0.0.1)
" default: 0
let g:mkdp_open_to_the_world = 0

" use custom IP to open preview page
" useful when you work in remote vim and preview on local browser
" more detail see: https://github.com/iamcco/markdown-preview.nvim/pull/9
" default empty
let g:mkdp_open_ip = ''

" specify browser to open preview page
" default: ''
let g:mkdp_browser = ''

" set to 1, echo preview page url in command line when open preview page
" default is 0
let g:mkdp_echo_preview_url = 1

" a custom vim function name to open preview page
" this function will receive url as param
" default is empty
function! g:Open_browser(url)
    silent exe 'open -a Firefox 'a:url
endfunction

let g:mkdp_browserfunc = 'g:Open_browser'

" options for markdown render
" mkit: markdown-it options for render
" katex: katex options for math
" uml: markdown-it-plantuml options
" maid: mermaid options
" disable_sync_scroll: if disable sync scroll, default 0
" sync_scroll_type: 'middle', 'top' or 'relative', default value is 'middle'
"   middle: mean the cursor position alway show at the middle of the preview page
"   top: mean the vim top viewport alway show at the top of the preview page
"   relative: mean the cursor position alway show at the relative positon of the preview page
" hide_yaml_meta: if hide yaml metadata, default is 1
" sequence_diagrams: js-sequence-diagrams options
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {},
    \ 'flowchart_diagrams': {}
    \ }

" use a custom markdown style must be absolute path
" like '/Users/username/markdown.css' or expand('~/markdown.css')
let g:mkdp_markdown_css = 'expand("~/github-markdown.css")'

" use a custom highlight style must absolute path
" like '/Users/username/highlight.css' or expand('~/highlight.css')
let g:mkdp_highlight_css = ''

" use a custom port to start server or random for empty
let g:mkdp_port = ''

" preview page title
" ${name} will be replace with the file name
let g:mkdp_page_title = '「${name}」'

" Mappings
nmap <C-s> <Plug>MarkdownPreview
nmap <M-s> <Plug>MarkdownPreviewStop
nmap <C-p> <Plug>MarkdownPreviewToggle
```

**Comment by iamcco** [comment]
change `let g:mkdp_markdown_css = 'expand("~/github-markdown.css")'` to `let g:mkdp_markdown_css = expand("~/github-markdown.css")`

run `:mess` after `:MarkdownPreview` to see error message.

**Comment by vinaysb** [comment]
I changed that, thanks for the tip.

This is the message I get 

```
[vim-node-rpc] rpc error: internal/modules/cjs/loader.js:638
[vim-node-rpc] rpc error:     throw err;
[vim-node-rpc] rpc error:     ^
[vim-node-rpc] rpc error:
[vim-node-rpc] rpc error: Error: Cannot find module 'tslib'
[vim-node-rpc] rpc error:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[vim-node-rpc] rpc error:     at Module.require (internal/modules/cjs/loader.js:692:17)
[vim-node-rpc] rpc error:     at require (internal/modules/cjs/helpers.js:25:18)
[vim-node-rpc] rpc error:     at Object.<anonymous> (/Users/bio/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
[vim-node-rpc] rpc error:     at Module._compile (internal/modules/cjs/loader.js:778:30)
[vim-node-rpc] rpc error:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[vim-node-rpc] rpc error:     at Module.load (internal/modules/cjs/loader.js:653:32)
[vim-node-rpc] rpc error:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by isweibin** [comment]
> I changed that, thanks for the tip.
> 
> This is the message I get
> 
> ```
> [vim-node-rpc] rpc error: internal/modules/cjs/loader.js:638
> [vim-node-rpc] rpc error:     throw err;
> [vim-node-rpc] rpc error:     ^
> [vim-node-rpc] rpc error:
> [vim-node-rpc] rpc error: Error: Cannot find module 'tslib'
> [vim-node-rpc] rpc error:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> [vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> [vim-node-rpc] rpc error:     at Module.require (internal/modules/cjs/loader.js:692:17)
> [vim-node-rpc] rpc error:     at require (internal/modules/cjs/helpers.js:25:18)
> [vim-node-rpc] rpc error:     at Object.<anonymous> (/Users/bio/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
> [vim-node-rpc] rpc error:     at Module._compile (internal/modules/cjs/loader.js:778:30)
> [vim-node-rpc] rpc error:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> [vim-node-rpc] rpc error:     at Module.load (internal/modules/cjs/loader.js:653:32)
> [vim-node-rpc] rpc error:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> [vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> ```

Hey there, same error, it gives "Cannot find module 'tslib'", did you figure it out?

**Comment by isweibin** [comment]
> I changed that, thanks for the tip.
> 
> This is the message I get
> 
> ```
> [vim-node-rpc] rpc error: internal/modules/cjs/loader.js:638
> [vim-node-rpc] rpc error:     throw err;
> [vim-node-rpc] rpc error:     ^
> [vim-node-rpc] rpc error:
> [vim-node-rpc] rpc error: Error: Cannot find module 'tslib'
> [vim-node-rpc] rpc error:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> [vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> [vim-node-rpc] rpc error:     at Module.require (internal/modules/cjs/loader.js:692:17)
> [vim-node-rpc] rpc error:     at require (internal/modules/cjs/helpers.js:25:18)
> [vim-node-rpc] rpc error:     at Object.<anonymous> (/Users/bio/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
> [vim-node-rpc] rpc error:     at Module._compile (internal/modules/cjs/loader.js:778:30)
> [vim-node-rpc] rpc error:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> [vim-node-rpc] rpc error:     at Module.load (internal/modules/cjs/loader.js:653:32)
> [vim-node-rpc] rpc error:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> [vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> ```

Hello, if you have node and yarn installed, you just use 'Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }' , then it will work.

**Comment by vinaysb** [comment]
@isweibin Yes that worked for me, but could tslib be included in the non npm/yarn install too?

**Comment by iamcco** [comment]
Since you use `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }` to install the plugin, it must be the prebuild bundle download fail. Try `:call mkdp#until#install()` again.

**Comment by vinaysb** [comment]
Oh ok, yea it works now, thank you :)

**Comment by vinn2010** [comment]
Hi, I am having a similar issue. My error log is similar to vinaysb. 

But, whether I try this:

`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}`

or this:

```
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
Or install with [dein](https://github.com/Shougo/dein.vim):
```

I get the same error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'tslib'
```

**Comment by denkk0** [comment]
Hello, I am having same error as guys above.

I am using Packer, and it still fails whether I use
```
use({
    "iamcco/markdown-preview.nvim",
    run = function() vim.fn["mkdp#util#install"]() end,
})
```
or
```
use({ "iamcco/markdown-preview.nvim", run = "cd app && npm install", setup = function() vim.g.mkdp_filetypes = { "markdown" } end, ft = { "markdown" }, })
```
or with yarn
```
use({ "iamcco/markdown-preview.nvim", run = "cd app && yarn install", setup = function() vim.g.mkdp_filetypes = { "markdown" } end, ft = { "markdown" }, })
```

I even tried using the first command, and then running `:call mkdp#util#install()`, but that leaves me with this:
```
Error detected while processing function mkdp#util#install:
line    2:
E484: Can't open file /Users/denis/.local/share/nvim/site/pack/packer/opt/markdown-preview.nvim/package.json
E714: List required
line    6:
E484: Can't open file /Users/denis/.local/share/nvim/site/pack/packer/opt/markdown-preview.nvim/package.json
E714: List required
Error detected while processing function mkdp#util#install[12]..mkdp#util#open_terminal:
line   18:
E344: Can't find directory "/Users/denis/.local/share/nvim/site/pack/packer/opt/markdown-preview.nvim/app" in cdpath
E472: Command failed
```

Any updates on this issue?

**Comment by VictorLemosR** [comment]
In case anyone is in trouble with: 

> Error: Cannot find module 'tslib'

What solved for me was installing tslib inside mardown-preview folder (%USERPROFILE%\AppData\Local\nvim-data\lazy\markdown-preview.nvim), note I'm on windows:

1) Open terminal
2) cd %USERPROFILE%\AppData\Local\nvim-data\lazy\markdown-preview.nvim
3) npm install tslib

Also, an extra for people installing with lazy.nvim. these are my configurations:
```
return {
    "iamcco/markdown-preview.nvim",
    ft = "markdown",
    build = function()
        vim.fn["mkdp#util#install"]()
    end,
    init = function()
        local g = vim.g
        g.mkdp_auto_start = 0
        g.mkdp_auto_close = 1
        g.mkdp_refresh_slow = 0
        g.mkdp_command_for_global = 0
        g.mkdp_open_to_the_world = 0
        g.mkdp_open_ip = ''
        g.mkdp_browser = 'chrome'
        g.mkdp_echo_preview_url = 0
        g.mkdp_browserfunc = ''
        g.mkdp_theme = 'dark'
        g.mkdp_filetypes = { "markdown" }
        g.mkdp_page_title = "${name}.md"
        g.mkdp_preview_options = {
            disable_sync_scroll = 0,
            disable_filename = 1
        }
    end,
}

```

**Comment by EdgarPezoa** [comment]
> In case anyone is in trouble with:
> 
> > Error: Cannot find module 'tslib'
> 
> What solved for me was installing tslib inside mardown-preview folder (%USERPROFILE%\AppData\Local\nvim-data\lazy\markdown-preview.nvim), note I'm on windows:
> 
> 1. Open terminal
> 2. cd %USERPROFILE%\AppData\Local\nvim-data\lazy\markdown-preview.nvim
> 3. npm install tslib
> 
> Also, an extra for people installing with lazy.nvim. these are my configurations:
> 
> ```
> return {
>     "iamcco/markdown-preview.nvim",
>     ft = "markdown",
>     build = function()
>         vim.fn["mkdp#util#install"]()
>     end,
>     init = function()
>         local g = vim.g
>         g.mkdp_auto_start = 0
>         g.mkdp_auto_close = 1
>         g.mkdp_refresh_slow = 0
>         g.mkdp_command_for_global = 0
>         g.mkdp_open_to_the_world = 0
>         g.mkdp_open_ip = ''
>         g.mkdp_browser = 'chrome'
>         g.mkdp_echo_preview_url = 0
>         g.mkdp_browserfunc = ''
>         g.mkdp_theme = 'dark'
>         g.mkdp_filetypes = { "markdown" }
>         g.mkdp_page_title = "${name}.md"
>         g.mkdp_preview_options = {
>             disable_sync_scroll = 0,
>             disable_filename = 1
>         }
>     end,
> }
> ```
It worked for me, i'm using packer
is the same process but packer is in this folder
%USERPROFILE%\AppData\Local\nvim-data\site\pack\packer\start\markdown-preview.nvim -  _WINDOWS_

**Comment by johnnymatthews** [comment]
For anyone else who's running into this issue on MacOS (or for myself reading this in the future):

1. Open a `.md` file in Neovim and run `:MarkdownPreview`.
2. Run `:mess`. You should see a long error message:

    ```plaintext
    node:internal/modules/cjs/loader:1152
      throw err;
      ^
    Error: Cannot find module 'tslib'
    Require stack:
    - /Users/johnny/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js
    
    ...
    ```

3. Go to where the MarkdownPreview plugin for Neovim is installed:

    ```shell
    cd ~/.vim/plugged/markdown-preview.nvim
    ```

4. Install the dependencies:

    ```shell
    npm install
    ```

5. You should be good now.

**Comment by Ketan194** [comment]
> For anyone else who's running into this issue on MacOS (or for myself reading this in the future):
> 
> 1. Open a `.md` file in Neovim and run `:MarkdownPreview`.
> 2. Run `:mess`. You should see a long error message:
>    ```
>    node:internal/modules/cjs/loader:1152
>      throw err;
>      ^
>    Error: Cannot find module 'tslib'
>    Require stack:
>    - /Users/johnny/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js
>    
>    ...
>    ```
> 3. Go to where the MarkdownPreview plugin for Neovim is installed:
>    ```shell
>    cd ~/.vim/plugged/markdown-preview.nvim
>    ```
> 4. Install the dependencies:
>    ```shell
>    npm install
>    ```
> 5. You should be good now.

This finally worked for me using Lazy, thank you for explaining it so clearly!!

**Comment by grgmiranda** [comment]
Guys, I tried all solutions given here and still getting the same error. I'm on Fedora.

**Comment by pipx2** [comment]
> For anyone else who's running into this issue on MacOS (or for myself reading this in the future):
> 
>     1. Open a `.md` file in Neovim and run `:MarkdownPreview`.
> 
>     2. Run `:mess`. You should see a long error message:
>        ```
>        node:internal/modules/cjs/loader:1152
>          throw err;
>          ^
>        Error: Cannot find module 'tslib'
>        Require stack:
>        - /Users/johnny/.vim/plugged/markdown-preview.nvim/app/lib/app/index.js
>        
>        ...
>        ```
> 
>     3. Go to where the MarkdownPreview plugin for Neovim is installed:
>        ```shell
>        cd ~/.vim/plugged/markdown-preview.nvim
>        ```
> 
>     4. Install the dependencies:
>        ```shell
>        npm install
>        ```
> 
>     5. You should be good now.

Thanks! This solved it for me!
I installed 'markdown-preview' on Ubuntu using the Lazy manager with the following:

```lua
{
    "iamcco/markdown-preview.nvim",
    cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
    ft = { "markdown" },
    build = function() vim.fn["mkdp#util#install"]() end,
}
```

And then did what the quote tells me to do.
Fixed it.

**Comment by sankargorthi** [comment]
To avoid manual intervention, this is what works for me with Lazy:


```
	{
		"iamcco/markdown-preview.nvim",
		lazy = "VeryLazy",
		cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
		ft = { "markdown" },
		build = function(plugin)
			vim.fn.system({ 'yarn' }, plugin.dir .. '/app')

			vim.opt.rtp:prepend(plugin.dir)
			vim.fn["mkdp#util#install"]()
		end,
	},
```

If you'd rather use `npm`, you can change the system command to `vim.fn.system({ 'npm', 'install'}, plugin.dir .. '/app')`
