### ISSUE TITLE
empty markdown css effect equation render?

### ISSUE THREAD

**Issue by forest0** [iamcco/markdown-preview.nvim#149]
## configuration

```vim
let g:mkdp_markdown_css = ''
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {
    \    'macros': {
    \        '\norm': '\left\lVert#1\right\rVert',
    \    },
    \ },
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {},
    \ 'flowchart_diagrams': {}
    \ }
```

## markdown content

```markdown
$$
\frac{1}{\norm{1}}
$$

some text

- a list

some text again

$$
-\frac{y_i}{2}
$$
```

## render result

![image](https://user-images.githubusercontent.com/20063987/76482291-b67b9300-644e-11ea-8891-8f3eca0658df.png)
the horizontal line of fraction is missing.

the weird thing is that, **if we delete any one of the two text lines or the list,
the last equation will be rendered as expect**

---

after I customized my markdown css, i.e., `let g:mkdp_markdown_css = 'xxx.css'`,
the problem disappeared.

**Comment by iamcco** [comment]
No idea. I can not reproduce this issue.

**Comment by forest0** [comment]
Now I can not reproduce either.
