### ISSUE TITLE
edit ipynb via jupytext.vim 

### ISSUE THREAD

**Issue by BenSYZ** [iamcco/markdown-preview.nvim#151]
## help wanted
I use [goerz/jupytext.vim](https://github.com/goerz/jupytext.vim) to convert `ipynb` to `md` automatically. Then I can edit the jupyter notebook like markdown. But I cannot use `:MarkdownPreview` to preview the file. I wonder if there exist any setting to achieve this.

 Thanks you!

**Comment by iamcco** [comment]
checkout option `g:mkdp_command_for_global` on readme.

**Comment by BenSYZ** [comment]
Oh! I'm so sorry to bother you. I should have checked the readme first. Thank you!

For others, I suggest you change the `Plug` line like the following, for not loading this plugin for other files. This is also the initial purpose of `let g:mkdp_command_for_global = 0`

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } ,'for': ['ipynb','markdown']}
```
