### ISSUE TITLE
无法使用firefox进行预览

### ISSUE THREAD

**Issue by weiguoquan422** [iamcco/markdown-preview.nvim#153]
系统是debian10，nvim v0.3.4
vimrc配置如下
" set to 1, nvim will open the preview window after entering the markdown buffer
let g:mkdp_auto_start = 1
" specify browser to open preview page
let g:mkdp_browser = '/usr/bin/firefox'
使用vim打开.md文件后， :MarkdowmPreview 无法打开firefox预览，没有任何反应。
是我哪里搞错了吗？

**Comment by iamcco** [comment]
命令行打开firfox的命令是啥？填那个试试

**Comment by victorwinson** [comment]
pop OS（ubuntu 内核） 18.04 也遇到同样的问题，firefox chromium都不行，不管是打开的命令或者绝对路径的都试过了
call plug#begin('~/.nvim/plugged')

Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
let g:vmt_auto_update_on_save = 0

Plug 'mzlogin/vim-markdown-toc'

Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
let g:mkdp_browser = 'chromium-browser'
let g:mkdp_auto_start = 1

Plug 'neoclide/coc.nvim', {'branch': 'release'}

难道配置有冲突吗

**Comment by iamcco** [comment]
执行命令后 `:mess` 查看有报错么？

**Comment by weiguoquan422** [comment]
> 命令行打开firfox的命令是啥？填那个试试

我的问题已经解决，是安装插件的时候没安装全。使用nvim的checkhealth命令显示缺失可执行文件。重新安装插件后问题解决了。安装这个插件特别慢，出现好多次的安装失败。

**Comment by iamcco** [comment]
下载慢基本都是因为国内的网络原因，最好可以使用代理
