### ISSUE TITLE
[vim-node-rpc] pre build and node not found!

### ISSUE THREAD

**Issue by maoliq** [iamcco/markdown-preview.nvim#154]
Macos catalina 10.15.5, vim 8.1 ,When I run [markdown] in vim, there is a error message:"[vim-node-rpc] pre build and node not found!", I do not know how to fix it, help me please.

**Comment by iamcco** [comment]
`:call mkdp#util#install()` to download pre build bundle.

**Comment by maoliq** [comment]
thanks, maybe there is some problem that I install markdown-preview-macos error
