### ISSUE TITLE
Im using vim 8 + dont use pluging managers

### ISSUE THREAD

**Issue by ReK2Fernandez** [iamcco/markdown-preview.nvim#159]
Can I install without any third party plugin manager? is this ready for vim 8 ?

**Comment by iamcco** [comment]
It's not ready for vim8, it require vim version >= 8.1. If you wan to install checkout https://github.com/iamcco/markdown-preview.nvim/issues/56#issuecomment-492070154

**Comment by ReK2Fernandez** [comment]
@iamcco thank you that seem to have worked
