### ISSUE TITLE
No matching autocommands

### ISSUE THREAD

**Issue by hzfmer** [iamcco/markdown-preview.nvim#16]
为什么安装了运行MarkdownPreview显示 “No matching autocommands”？
用的是vim8.1， 通过vim-plug安装。

**Comment by iamcco** [comment]
插件没安装完全，你怎么安装的，或者手动执行 `:call mkdp#util#install()`

**Comment by hzfmer** [comment]
我是在vimrc里加了
`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}`。
之后运行:PlugInstall，之后也没有错误提示， 但是无法运行。

我试了在vimrc里手动 `:call mkdp#util#install()`， 但是提示`./install.sh: line 67: cd: bin: No such file or directory`,

**Comment by iamcco** [comment]
应该这句执行失败了 `mkdir -p bin` 没创建成 bin目录，然后 `cd bin`这句提示没有目录，不知道是不是权限问题.

**Comment by hzfmer** [comment]
我试了重装，发现通过vim-plug安装，不会创建bin目录，也失败在67行的`cd`。
但我手动`:call mkdp#util#install()`之后，在我的`～/.vim/plugged/markdown-preview.nvim/app`目录下确实已经有了一个空的bin目录，说明`mkdir`似乎没问题。 然而之后的`cd`却失败了。 很奇怪。。

**Comment by iamcco** [comment]
这就更奇怪了，我有时间了看下能不能复现，今天进城务工都在路上没时间

**Comment by iamcco** [comment]
看了下，还是无法复现，你用的什么系统

**Comment by hzfmer** [comment]
mac 系统+zsh

**Comment by hzfmer** [comment]
算是解决了，应该是curl的问题。mac里有好几个curl，不知道在update什么的时候curl链接的library换成了一个9.0版本的，所以安装过程中其实curl不能运行。不过报错提示在了一个奇怪的地方。。
