### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by luhuanxml** [iamcco/markdown-preview.nvim#160]
Post-update hook for markdown-preview.nvim...Exit status:127

**Comment by iamcco** [comment]
没有更多信息，没法提供帮助

**Comment by luhuanxml** [comment]
我的系统是Ubuntu18.04  当我使用mkdp 方式去装的时候貌似安装成功了，可以预览命令没有起效果，
而且我也不知道怎么设置我安装的Google Chrome去打开。这里怎么配置用户的浏览器，能不能介绍下。
然后我换了一种方式使用yarn安装 就一直停留在 info There appears to be trouble with you network conection. Retrying.....

我之前用过你的preview.vim。现在尝试使用neovim.发现这个装起来有些麻烦。

**Comment by luhuanxml** [comment]
关键是我非常喜欢这一款，颜色和语法辨识度都要比vim那款漂亮很多

**Comment by iamcco** [comment]
看这提示，网不行。要么设个代理 然后执行 `:call mkdp#util#install()` 下载大好的包，要么npm 换国内的源装。

**Comment by luhuanxml** [comment]
谢谢，我使用yarn的方式又重新安装了几次，现在应该是成功了，可以预览了。使用的默认浏览器。非常感谢这么晚了还回我的提问。

**Comment by iamcco** [comment]
要设置浏览器就改这个，换成可以打开的浏览器命令 `let g:mkdp_browser = ''`
