### ISSUE TITLE
No matching autocommands

### ISSUE THREAD

**Issue by Augists-ZDCZ** [iamcco/markdown-preview.nvim#161]
* Installed correctly, but it doesn't work. 
* I have tried ' :call xxxx ' as you recommended in other issues, and it turns out everything is OK. All installation finished.
* But when I ' :MarkdownPreview ', I receive as same as my title **No matching autocommands**.
* There is a file named markdown-preview-macos in .vim/plugged/markdown-preview.nvim/app/bin

---

system: macOS 10.15.3
use: vim 8.1.1312
plug manager: vim-plug

---

Thanks

---
---

* 我安装的没啥问题啊，安装是等finish才关的
* 我也试过了其他回答说的那个指令，但是没啥用……他显示的是我安装好了
* 然后我预览的时候，他还显示没有这个指令
* 我的那个目录底下有那个文件，不存在别的问题下面说的那个问题

---

我用的：
macOS 10.15.3
vim 8.1.1312
vim-plug
vim新手，现在莫名其妙的……这东西我安装了好几次了安装不好……愁死了

---

谢谢

**Comment by iamcco** [comment]
看这个 https://github.com/iamcco/markdown-preview.nvim/issues/45

**Comment by Augists-ZDCZ** [comment]
谢谢🙏🙏🙏
我是在app目录下npm install之后好了的
太感谢了🙏
小白还不太懂，刚入门

**Comment by iamcco** [comment]
客气
