### ISSUE TITLE
图床的图片无法显示

### ISSUE THREAD

**Issue by mgdreamingstar** [iamcco/markdown-preview.nvim#162]
403 Forbidden: You don't have permission to access the URL on this server.
图片是放在七牛云上，地址有 https。

**Comment by iamcco** [comment]
着你得自己搞啊，你的图片有外链权限么。。。。没有你自己加上。

**Comment by mgdreamingstar** [comment]
图片好像是可以外链的，公开存储。
在博客也是可以显示的……

**Comment by iamcco** [comment]
能不能访问我控制不了，这个图片预览就是在网页上插入你的图片，至于能不能访问你的图片服务器说了算

**Comment by mgdreamingstar** [comment]
另外问一下，Typora 是可以看到图片的，这是不是可以外链呢？
如果不是，我再研究下。不好意思，打扰了。

**Comment by iamcco** [comment]
能不能外链，服务器决定的啊，比如服务器只让它决定的几个网站可以外链图片，或者你的图片服务器就是不让ip地址直接访问的网页外链。这里没做任何处理，就是吧你的图片地址插到预览页面，然后浏览器根据地址获取，然后你图片服务器说不行。
