### ISSUE TITLE
highlight js css background color overridden by markdown css

### ISSUE THREAD

**Issue by frankieliu** [iamcco/markdown-preview.nvim#169]
When using a css for highlight.js such as vs2015.css

It has a dark background:

 .hljs {
    display: block;
    overflow-x: auto;
    padding: 0.5em;
    background: #1E1E1E;
    color: #DCDCDC;
  }

This is not being picked up, instead it defaults to markdown.css 's

.markdown-body pre {
...
 background-color:
}

Is there a workaround so that the markdown.css <pre> background and color doesn't override highlight.css <code>?

**Comment by iamcco** [comment]
You can change any style in highlight css

**Comment by frankieliu** [comment]
I have: I got one from highlight.js website and used that one, however the one set by markdown.css is interfering with it, and I am not sure which of the parameters I should change for the markdown.css.  Could you also post the generated markdown.css since I believe it is generated.

**Comment by iamcco** [comment]
https://github.com/iamcco/markdown-preview.nvim/blob/master/app/_static/markdown.css
