### ISSUE TITLE
作者你好windows8提示这个应该怎么解决啊

### ISSUE THREAD

**Issue by yyy33** [iamcco/markdown-preview.nvim#170]
![image](https://user-images.githubusercontent.com/51548147/78454527-13274200-76cb-11ea-9f65-2fa58e28d988.png)

**Comment by yyy33** [comment]
![无标题](https://user-images.githubusercontent.com/51548147/78454572-68fbea00-76cb-11ea-81fa-e1170f0affa4.png)

**Comment by yyy33** [comment]
记事本正常的 是不是需要安装什么字体啊
![image](https://user-images.githubusercontent.com/51548147/78454699-43bbab80-76cc-11ea-9096-c525f725414d.png)

**Comment by yyy33** [comment]
![无标题](https://user-images.githubusercontent.com/51548147/78454716-61891080-76cc-11ea-8fc4-abd72e8c3532.png)

**Comment by iamcco** [comment]
你的vim不能正确识别 UTF-8 编码
