### ISSUE TITLE
gvim 8.2 can not run preview

### ISSUE THREAD

**Issue by paul-platte** [iamcco/markdown-preview.nvim#177]
1)Install with vim-plug

Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }

2) config with default

3) :MarkdownPreview
show error
Not an editor command:MarkdownPreview

Thanks!

**Comment by iamcco** [comment]
What's your system? seems pre bundle download is not complete, run `:call mkdp#util#install()` again.

**Comment by iamcco** [comment]
No, it's not pre bundle download issue, it's the plugin install incomplete

**Comment by paul-platte** [comment]
With node.js and yarn，re-install it. It's OK!

Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }

Thanks.
