### ISSUE TITLE
footnote is not rendered correctly

### ISSUE THREAD

**Issue by jdhao** [iamcco/markdown-preview.nvim#18]
Currently, the footnote is not rendered and is shown as is.

![image](https://user-images.githubusercontent.com/16662357/52894463-ae6a0900-31e4-11e9-949c-605f8728c67b.png)

Can you add the ability to render it?

**Comment by iamcco** [comment]
support it https://github.com/iamcco/markdown-preview.nvim/commit/253515a3f992ee0cf28193af0e7c03c9cc149a00

update the plugin

**Comment by jdhao** [comment]
Thanks, updated!

**Comment by whytong** [comment]
It seems the footnote is not rendered again. Same observation as @jdhao stated. 
tested on minimal vim configuration with vim-plug updated to latest commit ``96c0bc72252f87c4fcafaa672352a91730dee61d``
