### ISSUE TITLE
作者你好我每次执行markdownpreview都弹出这个错误,麻烦你看一下

### ISSUE THREAD

**Issue by yyy33** [iamcco/markdown-preview.nvim#181]
````
[vim-node-rpc] rpc error: (node:10913) Warning: Accessing non-existent property 'padLevels' of module exports inside circular de
pendency
[vim-node-rpc] rpc error: (Use `node --trace-warnings ...` to show where the warning was created)
(node:10924) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
````
````
(ins)[yyy@x550vc-yyy ~]$ node --trace-warnings node:10924
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module '/home/yyy/node:10924'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

````

**Comment by iamcco** [comment]
怎么装的？重新装下

**Comment by huanghehg** [comment]
我有同样的问题，下面是我vimrc插件的配置，我使用的是Vundle
```
 19 set rtp+=~/.vim/bundle/Vundle.vim
 20 call vundle#begin()
 21 " alternatively, pass a path where Vundle should install plugins
 22 "call vundle#begin('~/some/path/here')
 23
 24 " let Vundle manage Vundle, required
 25 Plugin 'VundleVim/Vundle.vim'
 26 Plugin 'scrooloose/nerdtree'
 27 " The following are examples of different formats supported.
 28 " Keep Plugin commands between vundle#begin/end.
 29 " plugin on GitHub repo
 30 Plugin 'tpope/vim-fugitive'
 31 " plugin from http://vim-scripts.org/vim/scripts.html
 32 " Plugin 'L9'
 33 " Git plugin not hosted on GitHub
 34 Plugin 'git://git.wincent.com/command-t.git'
 35 " git repos on your local machine (i.e. when working on your own plugin)
 36 " Plugin 'file:///home/gmarik/path/to/plugin'
 37 " The sparkup vim script is in a subdirectory of this repo called vim.
 38 " Pass the path to set the runtimepath properly.
 39 Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
 40 " Install L9 and avoid a Naming conflict if you've already installed a
 41 " different version somewhere else.
 42 " Plugin 'ascenator/L9', {'name': 'newL9'}
 43 Plugin 'w0rp/ale'
 44 Plugin 'vim-scripts/indentpython.vim'
 45 Plugin 'vim-airline/vim-airline'
 46 Plugin 'arcticicestudio/nord-vim'
 47 Plugin 'ycm-core/YouCompleteMe'
 48 Plugin 'mbbill/undotree'
 49 Plugin 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
 50 Plugin 'Xuyuanp/nerdtree-git-plugin'
 51 call vundle#end()            " required
 52 filetype plugin indent on    " required
```
我已经尝试过在app目录下执行`yarn install`

![image](https://user-images.githubusercontent.com/13210719/81245784-80225480-9048-11ea-9502-6e185e451ca9.png)

执行完成后，在使用`:MarkdownPreview`

![image](https://user-images.githubusercontent.com/13210719/81245910-cb3c6780-9048-11ea-91d6-c8af700c7267.png)

我的系统是：`macOS Mojava 10.14.6`

下面是我的工具版本：

![image](https://user-images.githubusercontent.com/13210719/81246060-2f5f2b80-9049-11ea-97ad-2d9aac6a5f58.png)
![image](https://user-images.githubusercontent.com/13210719/81246192-777e4e00-9049-11ea-9d28-e41e53ae1391.png)

请帮忙看下

**Comment by mzlogin** [comment]
我这里遇到的报错貌似也是一样的：

```
[vim-node-rpc] rpc error: (node:52682) Warning: Accessing non-existent property 'padLevels' of module e
xports inside circular dependency
[vim-node-rpc] rpc error: (Use `node --trace-warnings ...` to show where the warning was created)
(node:52683) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dep
endency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52698) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dep
endency
(Use `node --trace-warnings ...` to show where the warning was created)
```

也是 MacVim

**Comment by iamcco** [comment]
你们是不是都是 node 14？

**Comment by mzlogin** [comment]
我是 node v14.0.0

**Comment by iamcco** [comment]
还没升 node 14，不知道是什么问题。先用预编译 `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }`

**Comment by huanghehg** [comment]
> 还没升 node 14，不知道是什么问题。先用预编译 `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }`

多谢回复，使用预编译已经搞定

**Comment by nickjj** [comment]
> Ok, in fact, the function is normal, but there is an error prompt that is more annoying

It's more than just a warning message, because it won't spawn the preview in a browser when you run `:MarkdownPreview`.

I just upgraded to Node 14 and I'm seeing the same error here too.

Running `:messages` in Vim 8.1 on Ubuntu 20.04 shows this when running: `:MarkdownPreview`

```
[vim-node-rpc] rpc error: (node:2861) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
[vim-node-rpc] rpc error: (Use `node --trace-warnings ...` to show where the warning was created)
(node:2999) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[markdown-preview.vim] uncaught exception: Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Starslayerx** [comment]
每次MarkdownPreview vim都会报错：
```
(Use `node --trace-warnings ...` to show where the warning was created)
```
尝试了楼上预编译办法还是有报错,nodejs是14.3版本
不影响使用，但每次都会报错很不舒服..

**Comment by AlexHappyCode** [comment]
same problem

`❯ node --trace-warnings ...
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '/home/bolo/AnalysisOfAlgorithms/homework/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`

**Comment by ACupofAir** [comment]
same problem :
![image](https://user-images.githubusercontent.com/58850527/103520158-b3580480-4eb1-11eb-9f0e-0a7ec06bd9f8.png)
预编译之后报错一样

**Comment by HanleyLee** [comment]
同样遇到了这个问题, MacVim, node 15.9.0

![himg](https://tva1.sinaimg.cn/large/008eGmZEgy1gnxdovlp6tj31uu0awaim.jpg)

**Comment by ACupofAir** [comment]
> 同样遇到了这个问题, MacVim, node 15.9.0
> 
> 
> 
> ![himg](https://tva1.sinaimg.cn/large/008eGmZEgy1gnxdovlp6tj31uu0awaim.jpg)

我改用vim-instant-markdown 了

**Comment by MatchLittle** [comment]
> vim-instant-markdown



> > 同样遇到了这个问题, MacVim, node 15.9.0
> > ![himg](https://camo.githubusercontent.com/bdaa11a620952477760a04303c63bde86efaf2c6088c45aecbda0d7ff7adbf3e/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303865476d5a45677931676e78646f766c7036746a3331757530617761696d2e6a7067)
> 
> 我改用vim-instant-markdown 了
>我搞这个搞了两天，一次都没成功过。。。。。。。。。。
>然后改用vim-instant-markdown ，几分钟搞好。。。。。。。
>这就很无奈de

**Comment by resoliwan** [comment]
It is only worked at node
v10.24.1
-> v12.22.10
v14.17.5
v16.13.2

**Comment by iamcco** [comment]
已经把 vim-node-rpc 删了，问题应该没有了
