### ISSUE TITLE
For someone who is using minpac package manager

### ISSUE THREAD

**Issue by yanzhang0219** [iamcco/markdown-preview.nvim#183]
If someone is now using minpac package manager and wants to install this amazing plugin, just use this: `call minpac#add('iamcco/markdown-preview.nvim', {'do': 'call mkdp#util#install()'})`. 

Hi @iamcco, 
First, thank you for developing this powerful plugin. **Could you please add this installation instruction for minpac users in the README page**. Just in case you're not familiar with it, minpac is a minimal package manager which uses the vim8 built-in packages feature and the jobs feature. Its user base is not that large and the instruction about post-update hook is very brief and terse. I'm afraid someone using minpac would get trouble in installing this plugin. 

Thank you very much!

**Comment by iamcco** [comment]
Thanks, I have update the readme.

**Comment by iamcco** [comment]
Thanks, I have update the readme.

**Comment by yanzhang0219** [comment]
Hi @iamcco 
I will update the install instruction for minpac users. The previous one above is not working now.
Please change it to `call minpac#add('iamcco/markdown-preview.nvim', {'do': 'packloadall! | call mkdp#util#install()'})`
Thank you.

**Comment by iamcco** [comment]
Thanks! I have changed the README.
