### ISSUE TITLE
MarkdownPreview doesn't always work

### ISSUE THREAD

**Issue by Remiol** [iamcco/markdown-preview.nvim#184]
I've installed the plugin but 
MarkdownPreview does work once in a while.
I don't know why. Sometimes it works fine, sometimes it doesn't.

I use vim8.1
win10

I use this in my vimrc:
`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown.pandoc', 'on': 'MarkdownPreview' }`

What can I do to make this always work?
Does it conflict with other plugins like `conornewton/vim-pandoc-markdown-preview`?
Does it only work with markdown filetype? (I tried this also)
I use `ft=markdown.pandoc`

Does the plugin need Admin rights? If yes, how can I let it work without Admin rights?

**Comment by iamcco** [comment]
Checkout out the option `g:mkdp_command_for_global`, it only support Markdown file by default.

**Comment by iamcco** [comment]
I does not need Admin rights
