### ISSUE TITLE
在预览界面打开当地文件的链接

### ISSUE THREAD

**Issue by pacmanzou** [iamcco/markdown-preview.nvim#186]
你好，
我想知道现在具备这个功能吗？当我点击当地文件的链接时，页面是404,如果没有的话，我只能使用vnote来看md文件,用这个来写md了。

**Comment by iamcco** [comment]
还不具备。

**Comment by pacmanzou** [comment]
嗯 如果加上这个的话，那这个vim插件就太完美了。
