### ISSUE TITLE
[Feature request] Support for option in browser command

### ISSUE THREAD

**Issue by 00sapo** [iamcco/markdown-preview.nvim#19]
I really like this plugin! It's great! The only thing that I need more is the support for specifying browser options such as the "chromium --app=%U" for Chromium. As of now, it simply fails if `g:mkdp_browser` contains spaces, at least in Linux.

A workaround is a simple shell script:
```sh
#!/bin/sh
chromium --app=$@
```

**Comment by iamcco** [comment]
you can use the `g:mkdp_browserfunc` option to open preview page.

this is example works on mac:

```viml
function! g:Open_browser(url)
    silent exe 'silent !open -a "Google Chrome" ' . a:url
endfunction
let g:mkdp_browserfunc = 'g:Open_browser'
```

**Comment by 00sapo** [comment]
Thanks! This worked for me on Linux, but to launch it in the background you need some plugin such as `vim-dispatch`:

```vim
" Run commands in the background (Asyncrun breaks vim-surround)
Plug 'tpope/vim-dispatch'

Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}

function! g:Open_browser(url)
    exec "Start! chromium --app=" . a:url
endfunction
let g:mkdp_browserfunc = 'g:Open_browser'

autocmd FIleType markdown nmap <leader>o :MarkdownPreview<CR>
````

**Comment by reavessm** [comment]
FWIW, Firefox also works with the following:

```vim
function! g:Open_browser(url)
  exec "Start! firefox --new-window " . a:url
  " Alternatively, without vim-dispatch
  "silent exec "firefox --new-window " . a:url . " &"
endfunction
let g:mkdp_browserfunc = 'g:Open_browser'
```

**Comment by AidanUnhappy** [comment]
Mine works with:
function! g:Open_browser(url)
    silent exec "!google-chrome-stable --new-window " . a:url
endfunction
