### ISSUE TITLE
Could add a navigate bar when write markdown?

### ISSUE THREAD

**Issue by happysmile12321** [iamcco/markdown-preview.nvim#195]
Hi,I am using a vim plug `vim-markdown-toc`,which can help me to auto gennerate toc(table of content--which is a inner page link to this markdown file.),and I usually type ```:GenToGFM``` when I in the markdown file.And I press ```r``` to laugch your markdown preview plug.
But I want my navigate bar in the left display in the browser when I write markdown.So it's easy ,
just detect this code```<!-- TOC GFM -->balabala<!-- TOC GFM -->  ```,and just display it's content on the left(which display in the way of  navigate bar).
So Can I custom it,or can you look this as a new feature of your plug?

**Comment by iamcco** [comment]
I don't have much spare time to do this. PR is welcome.

**Comment by happysmile12321** [comment]
ok.could you please tell me how to get debug information(such as print var's value).Because I am not familar with js's framestructure.

**Comment by iamcco** [comment]
Setting log file:

```vim
let $NVIM_MKDP_LOG_FILE = expand('~/mkdp-log.log')
let $NVIM_MKDP_LOG_LEVEL = 'debug'
```

Using logger to print log https://github.com/iamcco/markdown-preview.nvim/blob/master/app/server.js#L36

**Comment by iamcco** [comment]
for browser side just using `console.log()`  to print log to browser console.
