### ISSUE TITLE
opening .md file is needed to preview .plantuml file

### ISSUE THREAD

**Issue by ShujiMikami** [iamcco/markdown-preview.nvim#197]
Hi, I use this plugin to preview plantuml with neovim.

It works almost perfect, but one small issue.

When I open plantuml file(extention is .plantuml), I can't use MarkdownPreview command.
('Not an editor command' error message)

Of course, g:mkdp_command_for_global is set to 1.

But, once I open any md file(extention is .md), MarkdownPreview command works to preview plantuml file.

The timing of opening md file doesn't affect to the result. 
plantuml after md is OK, also,  md  after plantuml is OK.

It's not a big issue, but if fixed, usability is much better.

Thanks.

**Comment by iamcco** [comment]
Can not reproduce, make sure that you don't load the plugin with lazy load for markdown filetype.

**Comment by ShujiMikami** [comment]
Thank you for the comment. 

The 'on_ft' option of dein was the root cause.

I added plantuml to on_ft candidates, then solved.
