### ISSUE TITLE
Running MarkdownPreview throws uncaught exception: Error: spawn xdg-open ENOENT in WSL 2 with terminal Vim

### ISSUE THREAD

**Issue by nickjj** [iamcco/markdown-preview.nvim#199]
Hi,

I'm using Vim 8.1 inside of Ubuntu 20.04 running in WSL 2 using the latest pull from master at the time of writing this comment.

Inside of WSL 1 this plugin worked great. It would open my default browser when running that command without having to do anything custom.

But now within WSL 2 it fails to run `:MarkdownPreview` with:

```
[markdown-preview.vim] uncaught exception: Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Turns out you need to install `sudo apt-get install -y xdg-utils`, and then things work fine. Although there is a ~5 second delay before it opens where as with WSL 1 it was instant.

Might be worth adding something to the docs or wiki for such an issue in a WSL section.

**Comment by iamcco** [comment]
I have update README and improve the error message

**Comment by mrbeardad** [comment]
> Turns out you need to install `sudo apt-get install -y xdg-utils`, and then things work fine. Although there is a ~5 second delay before it opens where as with WSL 1 it was instant.


It doesn't work well for me now in WSL2.  
I have changed ip and port, when I execute `:MarkdownPreview`, my chrome on windows10 will open with site `http://172.30.39.164:8854/page/1`, and warn me :
> This site can’t be reached  
> 172.30.39.164 refused to connect.  
> Try:  
> Checking the connection  
> Checking the proxy and the firewall  
> ERR_CONNECTION_REFUSED

What can I do to solve it?

**Comment by nickjj** [comment]
I'm not sure. I didn't change my ip:port and it works here with an address of `http://127.0.0.1:8576/page/1`, although there is still a multi-second delay for it to open. I'm running commit `faacfbcefe88badb0a5bee3290ec690373552f2b` of this plugin.

**Comment by mrbeardad** [comment]
hahahahahhahaha... I have solved it!

I have execute `lsof -i` in WSL2, and this plugin is listening `localhost` but not `IP address`, WSL2 treats Windows as a stand-alone host, so the connection from Windows is refused.  

Add `let g:mkdp_open_to_the_world = 1` to init.vim will solve this problem!

@iamcco 可以把这加文档里啦，老哥。换windows可搞死我了，wsl（我死了）:joy:

**Comment by iamcco** [comment]
@mrbeardad README 有链接链到这里了

**Comment by ndaman** [comment]
I just wanted to mention, using WSL2 (Arch if that makes a difference) the above methods did not work for me.

What DID work was to install [wslu](https://github.com/wslutilities/wslu) and set
`g:mkdp_browser='wslview'`
in my vimrc (well, init.vim). I have not experienced the multi-second delays the others are talking about using this approach.

**Comment by caoshenghui** [comment]
There is my solution：
sudo ln -s /mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe /usr/bin/edge
let let g:mkdp_browser = 'edge'

**Comment by XeonChow** [comment]
> I just wanted to mention, using WSL2 (Arch if that makes a difference) the above methods did not work for me.
> 
> What DID work was to install [wslu](https://github.com/wslutilities/wslu) and set
> `g:mkdp_browser='wslview'`
> in my vimrc (well, init.vim). I have not experienced the multi-second delays the others are talking about using this approach.

it works on my debian wsl2, mostly perfect except that my terminal window will go blank after i start preview, then it gradually reloads everything when i make some mouse or keyboard movement. no big deal but kinda annoying.

**Comment by qingbyin** [comment]
@XeonChow it can be solved by using [wsl-open](https://github.com/4U6U57/wsl-open) instead of `wslview`. Install `wsl-open` and set `g:mkdp_browser='wsl-open'`

If you prefer a general vim setting to a WSL specified one, use this trick without modifying `g:mkdp_browser`

```bash
sudo rm $(which xdg-open)
sudo ln -s $(which wsl-open) /usr/local/bin/xdg-open
```

Just run `:MarkdownPreview` and you should be good to go.

**Comment by XeonChow** [comment]
> @XeonChow it can be solved by using [wsl-open](https://github.com/4U6U57/wsl-open) instead of `wslview`. Install `wsl-open` and set `g:mkdp_browser='wsl-open'`
> 
> If you prefer a general vim setting to a WSL specified one, use this trick without modifying `g:mkdp_browser`
> 
> ```shell
> sudo rm $(which xdg-open)
> sudo ln -s $(which wsl-open) /usr/local/bin/xdg-open
> ```
> 
> Just run `:MarkdownPreview` and you should be good to go.

@qingbyin 
thank yuo so much, i followed your instruction and it works flawlessly.

**Comment by johnsonkee** [comment]
I use this plugin in WSL1, ubuntu. Every time I input `:MarkdownPreview`, the statusline shows " **openning 'http://127.0.0.1:8781/page/5' ... done! (xdg-open)**". And I have to type this address in my browser to view my markdown. 

I would like to ask how to make the preview page show automatically? Thank you very much.

**Comment by CharlesChiuGit** [comment]
None of above methods works, my temporary workaround is to set `vim.g.mkdp_echo_preview_url = 1` and manually click the url.

I notice one interesting thing, few weeks ago when I use markdown-preview in wsl2(Ubuntu22.04), calling `:MarkdownPreview` did auto open a new window in my Win11 brave browser. I don't even need to setup anything, I could also include `MarkdownPreview` in my autocmds.

But things go south when I try to rewrite my nvim configs in lua, autocmd as `vim.cmd [[]]` won't recognize `MarkdownPreview` as a editor command and nothing happens when I type `:MarkdownPreview` in command mode (although I can tab completion the command), and notging shows in `:messages` too.

I think there are some bugs when one set their mkdp configs in lua. The lua api might unable to do exact things vim-script does, like I ran into [the same issue in another plugin](https://github.com/f-person/git-blame.nvim/issues/51).

Hope this could provide some helpful insight to the @iamcco and thank you for the great plugin!

fyi, My mkdp config:

<details>
  <summary>mkdp.lua</summary>
      ```lua

      -- local status, markdown_preview = pcall(require, "markdown-preview")
      -- if (not status) then return end
      
      -- set to 1, nvim will open the preview window after entering the markdown buffer
      -- default: 0
      vim.g.mkdp_auto_start = 1 -- doesn't seem to work, use autocmd instead
      
      -- set to 1, the nvim will auto close current preview window when change
      -- from markdown buffer to another buffer
      -- default: 1
      vim.g.mkdp_auto_close = 0
      
      -- set to 1, the vim will refresh markdown when save the buffer or
      -- leave from insert mode, default 0 is auto refresh markdown as you edit or
      -- move the cursor
      -- default: 0
      vim.g.mkdp_refresh_slow = 0
      
      -- set to 1, the MarkdownPreview command can be use for all files,
      -- by default it can be use in markdown file
      -- default: 0
      vim.g.mkdp_command_for_global = 0
      
      -- set to 1, preview server available to others in your network
      -- by default, the server listens on localhost (127.0.0.1)
      -- default: 0
      vim.g.mkdp_open_to_the_world = 1
      
      -- use custom IP to open preview page
      -- useful when you work in remote vim and preview on local browser
      -- more detail see: https://github.com/iamcco/markdown-preview.nvim/pull/9
      -- default empty
      vim.g.mkdp_open_ip = ""
      
      -- specify browser to open preview page
      -- :for path with space
      -- valid: `/path/with\ space/xxx`
      -- invalid: `/path/with\\ space/xxx`
      -- default: ''
      vim.g.mkdp_browser = ""
      
      -- set to 1, echo preview page url in command line when open preview page
      -- default is 0
      vim.g.mkdp_echo_preview_url = 1
      
      -- a custom vim function name to open preview page
      -- this function will receive url as param
      -- default is empty
      -- vim.g.mkdp_browserfunc = ""
      
      -- options for markdown render
      -- mkit: markdown-it options for render
      -- katex: katex options for math
      -- uml: markdown-it-plantuml options
      -- maid: mermaid options
      -- disable_sync_scroll: if disable sync scroll, default 0
      -- sync_scroll_type: 'middle', 'top' or 'relative', default value is 'middle'
      --   middle: mean the cursor position alway show at the middle of the preview page
      --   top: mean the vim top viewport alway show at the top of the preview page
      --   relative: mean the cursor position alway show at the relative positon of the preview page
      -- hide_yaml_meta: if hide yaml metadata, default is 1
      -- sequence_diagrams: js-sequence-diagrams options
      -- content_editable: if enable content editable for preview page, default: v:false
      -- disable_filename: if disable filename header for preview page, default: 0
      -- vim.g.mkdp_preview_options = {
      -- 	mkit = {},
      -- 	katex = {},
      -- 	uml = {},
      -- 	maid = {},
      -- 	disable_sync_scroll = 0,
      -- 	sync_scroll_type = "middle",
      -- 	hide_yaml_meta = 1,
      -- 	sequence_diagrams = {},
      -- 	flowchart_diagrams = {},
      -- 	content_editable = false,
      -- 	disable_filename = 0,
      -- 	toc = {},
      -- }
      
      -- use a custom markdown style must be absolute path
      -- like '/Users/username/markdown.css' or expand('~/markdown.css')
      -- vim.g.mkdp_markdown_css = vim.env.HOME .. "/.config/nvim/lua/github-markdown-css/github-markdown-dark.css"
      
      -- use a custom highlight style must absolute path
      -- like '/Users/username/highlight.css' or expand('~/highlight.css')
      -- using https://github.com/sindresorhus/github-markdown-css
      --vim.g.mkdp_highlight_css = fnameescape($HOME).'/.config/nvim/github-markdown-css/github-markdown.css'
      
      -- use a custom port to start server or empty for random
      vim.g.mkdp_port = "8765"
      
      -- preview page title
      -- ${name} will be replace with the file name
      -- vim.g.mkdp_page_title = "「${name}」"
      
      -- recognized filetypes
      -- these filetypes will have MarkdownPreview... commands
      -- vim.g.mkdp_filetypes = { "markdown" }
      
      -- set default theme (dark or light)
      -- By default the theme is define according to the preferences of the system
      -- vim.g.mkdp_theme = "dark"
      ```
</details>

My autocmd:

```lua
vim.cmd [[
  " Open md files with toc if there's one.
  au BufRead *.md :call OpenMd()

  function! OpenMd()
    setlocal foldlevel=1
    " :MarkdownPreview
    SymbolsOutline
  endfunction
]]
```

**Comment by timsu92** [comment]
> @ndaman it works on my debian wsl2, mostly perfect except that my terminal window will go blank after i start preview, then it gradually reloads everything when i make some mouse or keyboard movement. no big deal but kinda annoying.

@XeonChow Another way to solve is to `redraw!` in the last line of the function pointed by `g:mkdp_browserfunc`
<details>

This is working on WSL2(Ubuntu 22.04) on a x64 machine.
This opens using Chrome by default, and switch to Edge if Chrome not found.
```vim
function! MdpOpenPreview(url) abort
	let l:mdp_browser = '/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe'
	let l:mdp_browser_opts = '--new-window'
	if !filereadable(substitute(l:mdp_browser, '\\ ', ' ', 'g'))
		let l:mdp_browser = '/mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe'
		let l:mdp_browser_opts = '--new-window'
	endif
	execute join(['silent! !', l:mdp_browser, l:mdp_browser_opts, a:url])
	redraw!
endfunction

let g:mkdp_browserfunc = 'MdpOpenPreview'
```
</details>

**Comment by Moxie1337** [comment]
> > @ndaman it works on my debian wsl2, mostly perfect except that my terminal window will go blank after i start preview, then it gradually reloads everything when i make some mouse or keyboard movement. no big deal but kinda annoying.
> 
> @XeonChow Another way to solve is to `redraw!` in the last line of the function pointed by `g:mkdp_browserfunc`
> 
> This is working on WSL2(Ubuntu 22.04) on a x64 machine. This opens using Chrome by default, and switch to Edge if Chrome not found.
> 
> ```viml
> function! MdpOpenPreview(url) abort
> 	let l:mdp_browser = '/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe'
> 	let l:mdp_browser_opts = '--new-window'
> 	if !filereadable(substitute(l:mdp_browser, '\\ ', ' ', 'g'))
> 		let l:mdp_browser = '/mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe'
> 		let l:mdp_browser_opts = '--new-window'
> 	endif
> 	execute join(['silent! !', l:mdp_browser, l:mdp_browser_opts, a:url])
> 	redraw!
> endfunction
> 
> let g:mkdp_browserfunc = 'MdpOpenPreview'
> ```

You solve my problem! Thank you
