### ISSUE TITLE
Link to a filename containing spaces

### ISSUE THREAD

**Issue by gbcreation** [iamcco/markdown-preview.nvim#2]
First of all, thank you very much for this great plugin! It is very useful.

Here is a little bug I found regarding links. With this markdown:

```markdown
* [page](page.md)
* [a page](a page.md)
* [another page](another\ page.md)
```

I get the following preview:

![markdown-preview-nvim](https://user-images.githubusercontent.com/454315/49829352-84ccd580-fd8e-11e8-8870-d02d27a0d270.png)

As you can see, the second link is not correctly rendered in the preview. It is due to the space character in the filename specified in parenthesis. If spaces are escaped as the third link, the rendering is correct.

Would it be possible to consider that all characters between parenthesis, including spaces, are part of the filename?

Thank you.

**Comment by iamcco** [comment]
> s you can see, the second link is not correctly rendered in the preview. It is due to the space character in the filename specified in parenthesis. 

it's not a bug https://github.com/markdown-it/markdown-it/issues/147.

`page.md` rendered as a link is because the default option `linkify` for markdown-it is true. you can disable this by setting:

```viml
let g:mkdp_preview_options = {
      \ 'mkit': {
      \    'linkify': v:false,
      \  },
      \ }
```

**Comment by iamcco** [comment]
close, feel free to open if you have any problem

**Comment by gbcreation** [comment]
Setting linkify to false does not resolve the issue. With this option, no more markdown links are rendered as HTML links.

**Comment by iamcco** [comment]
<img width="529" alt="2018-12-14 9 02 17" src="https://user-images.githubusercontent.com/5492542/49976929-126f1780-ff7f-11e8-9618-8fd3d764b678.png">

no issue for me.
