### ISSUE TITLE
Error while running post update hook

### ISSUE THREAD

**Issue by GohioAC** [iamcco/markdown-preview.nvim#20]
The following error is generated when running PlugUpdate/PlugInstall :

```
Post-update hook for markdown-preview.nvim ... Vim(if):E117: Unknown function: trim
```

**Comment by iamcco** [comment]
What version vim are you using ? It seems your vim is older then v8.0.1630 which is not support by the plugin.

**Comment by iamcco** [comment]
Closed, feel free to reopen if you still have any problem

**Comment by iamcco** [comment]
i found neovim older than 0.3.2 is not support trim, fix it

**Comment by GohioAC** [comment]
Apologies for the delay in responding. I am using Neovim v0.3.1 and the trim function fix solved the problem. Thanks for taking care of it.
