### ISSUE TITLE
Ability to remove CJK Brackets (「 」 ) from title output

### ISSUE THREAD

**Issue by tya99** [iamcco/markdown-preview.nvim#21]
Hi,

Let me say you've done an awesome job with this! ❤️

Is there any chance you could add an option to not put the `「 」 ` CJK brackets in the heading of the page? Perhaps there could be an option in vimrc.

I like to save the HTML output. I use a standard 104/105-key PC keyboard and don't have these characters so it's kind of annoying when editing markdown files in the shell and then wanting to open/move etc the HTML files.

Also you should have a Bitcoin donation option 😀.

**Comment by iamcco** [comment]
add `g:mkdp_page_title` option to setup preview page title.

```viml
" ${name} will be replace with the file name
let g:mkdp_page_title = '「${name}」'
```
