### ISSUE TITLE
Is there a way to make it work on another device?

### ISSUE THREAD

**Issue by danielfalbo** [iamcco/markdown-preview.nvim#215]
Is there a way to make it work on the browser of another device connected to the same wifi or something ? I'm really not into networking stuff, sorry.

Anyway thanks for the amazing plugin ! :)

**Comment by iamcco** [comment]
set `let g:mkdp_open_to_the_world = 1` option.

**Comment by danielfalbo** [comment]
Works : ) Thank you much
