### ISSUE TITLE
[help] work with temporary buffer

### ISSUE THREAD

**Issue by roachsinai** [iamcco/markdown-preview.nvim#216]
我需要临时生成一个markdown文件，不想保存到磁盘上。就想着生成到临时的buffer上，就是nofile类型。

但是这样的话就没有办法执行Preview命令，直接运行`call mkdp#util#open_preview_page()`得到的是一个空白的网页。

所以想问一下有办法强行在临时的buffer上执行预览么？谢谢！

**Comment by iamcco** [comment]
没法复现，只要是 markdown 类型，不管是不是 nofile buffer 命令都是可用的，并且可以预览

**Comment by roachsinai** [comment]
感谢回复，好像是是额外的`nobuflisted`设置导致无法预览。就是下面函数中的：

`setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile filetype=markdown`

想问一下通过`vnew`创建buffer,然后设置filetype为markdown，这个时候是不会加载`MarkdownPreview`命令的么？

---

下面是创建临时buffer的函数代码（不过可能不太需要）
```
{#@@ https://gist.github.com/romainl/eae0a260ab9c135390c30cd370c20cd7 @@#}
function! Redir(cmd, rng, start, end)
	for win in range(1, winnr('$'))
		if getwinvar(win, 'scratch')
			execute win . 'windo close'
		endif
	endfor
	if a:cmd =~ '^!'
		let cmd = a:cmd =~' %'
			\ ? matchstr(substitute(a:cmd, ' %', ' ' . expand('%:p'), ''), '^!\zs.*')
			\ : matchstr(a:cmd, '^!\zs.*')
		if a:rng == 0
			let output = systemlist(cmd)
		else
			let joined_lines = join(getline(a:start, a:end), '\n')
			let cleaned_lines = substitute(shellescape(joined_lines), "'\\\\''", "\\\\'", 'g')
			let output = systemlist(cmd . " <<< $" . cleaned_lines)
		endif
	else
		redir => output
		execute a:cmd
		redir END
		let output = split(output, "\n")
	endif
	vnew
	let w:scratch = 1
	setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile filetype=markdown
	call setline(1, output)
endfunction
```

**Comment by roachsinai** [comment]
看了plugin/mkdp.vim是了是了，感谢.

**Comment by roachsinai** [comment]
不过是`call mkdp#util#open_preview_page()`是由于设置`nobuflisted`的原因么？

**Comment by iamcco** [comment]
不懂，我这里 `call mkdp#util#open_preview_page()` 是可以 的

**Comment by roachsinai** [comment]
嗯嗯，好吧。

**Comment by roachsinai** [comment]
在设置了`nobuflisted`会有下面的错误信息：

```
[markdown-preview.nvim] UnhandledRejection
TypeError: Cannot read property 'name' of undefined
```

**Comment by iamcco** [comment]
唯一有可能这个报错就在这里 https://github.com/iamcco/markdown-preview.nvim/blob/master/src/attach/index.ts#L48

如果是这里的话就是拿不到这个buffer，但是我这里是没问题的，我用的 neovim 0.5.0

**Comment by roachsinai** [comment]
好的。
