### ISSUE TITLE
Toggle Scroll Syncing?

### ISSUE THREAD

**Issue by jessebett** [iamcco/markdown-preview.nvim#217]
What is the best way to toggle scroll syncing? Since it's inside the `mkdp_preview_options` list I'm not sure how to toggle easily.

**Comment by iamcco** [comment]
`let g:mkdp_preview_options.disable_sync_scroll = !g:mkdp_preview_optionsdisable_sync_scroll`

**Comment by tex** [comment]
I tried it now, and it works.

But, It would be better if there was a checkbox in the html page itself where you could disable / enable the sync-scrolling. Next to the button with the Dark Mode.
