### ISSUE TITLE
您好，作者我在使用MarkdownPreview命令时，没有反应，然后输入:mess输出了下面log，google了一圈没有找到解决方法，您看一下是什么原因，谢谢

### ISSUE THREAD

**Issue by inexts1996** [iamcco/markdown-preview.nvim#218]
![image](https://user-images.githubusercontent.com/43948140/88389195-94c0ee00-cde8-11ea-86ff-0e476e05b1a2.png)

**Comment by iamcco** [comment]
用什么方式安装的？这个错误是没装依赖，到插件目录 app 文件夹下yarn install 或 npm install 安装依赖

**Comment by inexts1996** [comment]
> 用什么方式安装的？这个错误是没装依赖，到插件目录 app 文件夹下yarn install 或 npm install 安装依赖

好了，谢谢大佬
