### ISSUE TITLE
can't open a browser to previerw the realtime .md or .markdown file

### ISSUE THREAD

**Issue by MengShengHui** [iamcco/markdown-preview.nvim#222]
my OS :linux(based on debian)
my vim:  version>=8.2
my browser:chromium
all my settings are followed the author's,    
but it can't work like what it should be.
and i have reinstalled server times,failed again and again.
please help.

**Comment by iamcco** [comment]
What's the error message?

**Comment by MengShengHui** [comment]
> What's the error message?

see your dear name is chinese ,so 我还是中文吧，就是我编辑了一个.md文件后，在命令模式下输入:markdownprevire，报出的错误是：没有匹配的自动命令

**Comment by iamcco** [comment]
看这个 https://github.com/iamcco/markdown-preview.nvim/issues/45

**Comment by MengShengHui** [comment]
> 看这个 #45

执行了：call mkdp#util#install()就成功了。太谢谢你了，真的很感激你。搞了一天了，安了好几个markdown的插件，都没成功。终于还是您帮助了我。（笔芯）

**Comment by iamcco** [comment]
客气
