### ISSUE TITLE
plug and dein examples entries should be using && not &

### ISSUE THREAD

**Issue by derekschrock** [iamcco/markdown-preview.nvim#226]
Unless if I'm missing something you're expecting on install if we can successfully cd to the app directory run `yarn install`.

However, README.md has `cd app & yarn install`  which exec cd in the background and runs `yarn install` in the base directory.   This doesn't seem correct to me so should the `&` be `&&`.

**Comment by iamcco** [comment]
It's a mistake, I have updated the Readme

**Comment by derekschrock** [comment]
Confirmed.  Thanks.
