### ISSUE TITLE
Is it possible to convert markdown to html ?

### ISSUE THREAD

**Issue by strogiyotec** [iamcco/markdown-preview.nvim#228]
Good day, I use this plugin a lot in addition to vim-wiki, right now I want to save my .md notes as pdf files. In order to do it I use
[grip](https://github.com/joeyespo/grip) that could accept markdown file and convert it to html and then I pipe this html to wkhtmltopdf. I'm not sure how this project works internally, if it can display my markdown file in the browser then could it pipe html into the file?
Let's say something like this
1. Open index.md using vim
2. Execute a command something like ":MarkdownToHtml" ans save this markdown as html

Please let me know if it's possible to achieve using this plugin. Thank you in advance

**Comment by iamcco** [comment]
The markdown convert to html (also Mermaid, floatchart, katex and so on) is in the browser, so it not possible to do that.

**Comment by strogiyotec** [comment]
Got it , thank you for fast response
