### ISSUE TITLE
Using latex functions within links

### ISSUE THREAD

**Issue by elizabethhsy** [iamcco/markdown-preview.nvim#230]
Hello, thank you for your work!

I was wondering if it would be possible to embed LaTex functions (the ones with backslashes) in markdown links.

Currently, things like [$x^2$](link) work, but things like [$\frac{1}{2}$](link) do not. On the live preview, both show up as a blue clickable link, but within the editor, only the first one becomes a legitimate link.

This would be useful because it would allow me to use chemical equations/formulae as links to new pages (e.g. [$\ce{H2O2}$](link).

Thank you!

(It's my first time reporting an issue, so sorry if there's any ambiguity)

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/93185434-f9a51e80-f76f-11ea-86e2-fec09786c32f.png)

Seems it works for me ?
