### ISSUE TITLE
axisFormat doesn;t work

### ISSUE THREAD

**Issue by 00sapo** [iamcco/markdown-preview.nvim#24]
Command `axisFormat` in mermaid gantts doesn't work. Maybe you should just update mermaid:

    ```mermaid
    gantt
        dateFormat DD-MM-YYY
        axisFormat %m/%y

        title Example
        section example section
        activity :active, 01-02-2019, 03-08-2019
    ```

Test it [here](https://mermaidjs.github.io/mermaid-live-editor/)

**Comment by iamcco** [comment]
Thanks to report. I have upgrade mermaid to v8.0.0 and it seems works well.

<img width="856" alt="2019-03-02 10 33 12" src="https://user-images.githubusercontent.com/5492542/53675945-face4200-3cd6-11e9-915f-6806ec7a8bd2.png">
