### ISSUE TITLE
Bug: Cant draw $\neq$ correctly

### ISSUE THREAD

**Issue by Cassin01** [iamcco/markdown-preview.nvim#240]
**Screenshots**

screenshots1(neovim)
<img width="611" alt="スクリーンショット 2020-10-05 19 33 00" src="https://user-images.githubusercontent.com/42632201/95069430-9ccecf80-0741-11eb-9073-98fdedaa4201.png">

screenshots2(preview(Safari))
<img width="675" alt="スクリーンショット 2020-10-05 19 31 15" src="https://user-images.githubusercontent.com/42632201/95069229-5a0cf780-0741-11eb-946d-a3b2535aa3d8.png">

**Desktop**
 - OS: macOS Catalina, Version 10.15.6

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/95537230-bd3baa00-0a1f-11eb-86a2-a93e1d97cd3e.png)


It seems Katex issue on Safari. I test on chrome and it works well.

**Comment by iamcco** [comment]
I have upgrade katex to v0.12.0, It should be fixed now.
