### ISSUE TITLE
Installation: E117: Unknown function: mkdp#util#install

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [iamcco/markdown-preview.nvim#241]
OS Version: macos 10.15.7
Vim Version: 8.1 (2018 May 18, compiled Jun 5 2020)
Vim-Plug Version: up-to-date (2020 Oct 8)

Install command:
`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}`

Error Message:
`Post-update hook for markdown-preview.nvim ... Vim(return):E117: Unknown function: mkdp#util#install`

**Comment by iamcco** [comment]
Can no reproduce.

**Comment by Shawn-Guo-CN** [comment]
My bad, I did something stupid. Ignore this issue please.

**Comment by MengShengHui** [comment]
how do u resolve it?

**Comment by Shawn-Guo-CN** [comment]
Just put the line between `call plug#begin` and `call plug#end`.
