### ISSUE TITLE
切换文件时的问题

### ISSUE THREAD

**Issue by niuiic** [iamcco/markdown-preview.nvim#246]
单文件的渲染效果很不错，只是当焦点转到tagbar、filetree等地方时浏览器会自动关闭。虽然这点可以通过设置auto_close解决，但是这样对多文件切换时保持渲染不利（会打开很多个）。

如果同时设置自动启动以及自动关闭，勉强可以在多文件中切换。不过一来速度有点慢，二来如果切换时，也就是浏览器关闭到重新开启这段时间无键盘响应，焦点就会被浏览器抢走。三来，浏览器开关太频繁有可能卡住。

除上面的设置之外似乎没有什么好的切换办法。如果禁用自动关闭，并且手动为每个文件启动渲染，当后一个开启时，前一个就会失效。

浏览器直接关闭的问题可以通过在浏览器中留一个tab解决，这样就只是tab的开关。

不过又发现一个问题。设置自动开关之后，当呼出vim-which-key的提示界面后，焦点丢失，tab未关闭。当重新聚焦于编辑页面时，重新打开了一个tab。这个问题可能也存在于其他情况。

PS：关闭和开启应该和焦点没什么关系，只是借此阐述一下现象。不过如果能在关闭和开启的过程中一直保持聚焦在vim上就更好了。

还有，不知能否设置一个手动更新的命令，主要是为了再次加载文件。以防止在开启插件之后加入的图片无法自动刷新。虽然重启也能达到效果，不过还是比较费时。

**Comment by iamcco** [comment]
其实就是打开一个预览页面，切换vim的buffer到不同markdown自动把预览切换过去吧？目前还没有这个功能。

> 还有，不知能否设置一个手动更新的命令，主要是为了再次加载文件。以防止在开启插件之后加入的图片无法自动刷新。虽然重启也能达到效果，不过还是比较费时。

这个没懂

**Comment by niuiic** [comment]
其实前面问题比较大的是预览受tagbar、filetree还有各种浮动窗口的影响。话说这真的很影响体验感。至于自动切换预览的基本功能其实是有的，只是不太流畅。不知能否通过改变判断开关预览的条件解决这个问题。

最后这个问题其实就是当开启预览后，新截一张图，保存，再在markdown中调用，无法显示，需要重启预览。
