### ISSUE TITLE
my setting doesn't apply at all

### ISSUE THREAD

**Issue by oO-z** [iamcco/markdown-preview.nvim#250]
thanks heaps for the work!! I like the plugin a lot indeed! Having said that, I came to realize that my personal setting seemed no working at all.

for instance, I would like the preview window to be opened with medge, regardless how I set up with "let g:mkdp_brower = 'microsoft-edge-dev -inprivate'" and "let g:mkdp_path_to_chrome = "open -a microsoft-edge-dev -inprivate"", it would just consistently open with firefox until I eventually uninstalled firefox. As you may noticed in my setting, I would prefer it could launch under inprivate mode, again it still launches all the time under normal mode.

Also, I really want it could start out on a new window instead of a new tab. Is there a way for me to do so?

It seemed to me that all my setting has been completely ignored and has no effect at all to its performance. It would be greatly appreciated if you may help address the issue. Many thanks!!

**Comment by iamcco** [comment]
Use your own function to open preview page use option `let g:mkdp_browserfunc = ''`

**Comment by oO-z** [comment]
thanks heaps for the response! would you care to elaborate how I may define "mkdp_browserfunc"? It seemed not work at all regardless whatever I set up though.

**Comment by iamcco** [comment]
```vim
function g:open_preview_page(url)
  " open preview page by the url
endfunction

let g:mkdp_browserfunc = 'g:open_preview_page'
```

**Comment by mikkelrask** [comment]
> for instance, I would like the preview window to be opened with medge, regardless how I set up with "let g:mkdp_brower = 'microsoft-edge-dev -inprivate'" 

If this was copied from your init.vim it's probably due to the mistype of _browser_ :1st_place_medal:

**Comment by oO-z** [comment]
cowabunga!! everything now works beautifully, thanks a bunch for the help!
