### ISSUE TITLE
Can't get the :MarkdownPreview command anymore

### ISSUE THREAD

**Issue by iGormilhit** [iamcco/markdown-preview.nvim#254]
**Describe the bug**
I'm using `:MarkdownPreview` since a few years in neovim, mostly without any issues. But today, I cannot use it, the `:MarkdownPreview` command doesn't show up anymore. I don't use the markdown preview every day, so I don't know since when it doesn't work as expected.

I'm running archlinux (regularly updated).
I'm using neovim `v0.4.4`, Markdown preview is up to date.
Node v.12.8.3.
Checkhealth is fine.

I tried to reinstall my plugins and to use a minimal init.vim for testing purpose:

```
" plugins (vim-plug)
call plug#begin('~/.config/nvim/plugged')
Plug 'arcticicestudio/nord-vim'                     " Nord color scheme
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-sensible'                           " default settings
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }     " Markdown preview
Plug 'vim-pandoc/vim-pandoc'                        " pandoc support 
Plug 'vim-pandoc/vim-pandoc-syntax'                 " markdown syntax support 
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Filetype detection
filetype plugin on

" Format indentation
if has("autocmd")
  filetype plugin indent on
endif

" Python provider in a pyenv
let g:python3_host_prog='/home/igor/.pyenv/versions/neovim3/bin/python'

" Pandoc
let g:pandoc#formatting#mode = "hA"

" airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#wordcount#filetypes = 'pandoc\|text\|' "Add support when pandoc is activated
let g:airline_theme='nord'

" Syntax coloration and color theme
syntax enable
set background=dark
colorscheme nord
```

**Comment by iamcco** [comment]
Using `:mess` to see error message.

**Comment by iGormilhit** [comment]
@iamcco Thanks. Using `:mess` do not display any message at all. Maybe I don't use it correctely. I opened a `.md` file, verified that the markdown preview plugin is loaded and typed `:mess`. I tried also `:messages`. But I didn't get any message.

**Comment by iamcco** [comment]
Make sure run `:mess` after `MarkdownPreview`

**Comment by iGormilhit** [comment]
:slightly_smiling_face: 

The problem is that the command `:MarkdownPreview` is no where to by found. That's my issue. And I can't understand why as the plugin is up to date and loaded.

**Comment by iamcco** [comment]
Seems doest not install correctly. Enter markdown file and run `:echo &rtp` to see if it's in the run time path.

**Comment by iGormilhit** [comment]
Yes it is: `/home/igor/.vim/plugged/markdown-preview.nvim`, same path as the other plugins.

**Comment by iamcco** [comment]
Have no idea. Never meet this before.

**Comment by iGormilhit** [comment]
Ok, thanks anyway. If I find something, I will post it here.

**Comment by Giatroo** [comment]
I'm having the same problem. I thought it could be the vimwiki plugin I'm using, but that's not the case. I removed vimwiki completely and now nvim is recognizing correctly that I'm in a markdown file, but still `:MarkdownPreview` or any other commands don't work properly. Even `<Plug>MarkdownPreview`, `<Plug>MarkdownPreviewToggle` or letting `g:mkdp_auto_start = 1` doesn't open my browser. 

I also tried to change the `g:mkdp_browser` to `'/bin/google-chrome/'` but I don't know if that's the expected value for that variable.

I tried using `:mess` after `:MarkdownPreview` but nothing happened. And running `:echo &rtp` shows the plugin path.

**Comment by Giatroo** [comment]
I tried to remove all of my plugins and just let `godlygeek/tabular`, `plasticboy/vim-markdown` and `iamcco/markdown-preview.nvim` and it's still not working. (Even just with the markdown-preview, it doesn't work, so I think that's not a incompatibility).

It's probably some new change in the plugin, since other people have the same problem.

**Comment by iamcco** [comment]
Seems it does not recognizing the correct filetype.  Have no idea, this code does not change for a long time.

![image](https://user-images.githubusercontent.com/5492542/98319852-a38c8300-201c-11eb-87e3-d860f350cc93.png)

**Comment by Giatroo** [comment]
Sadly =/ 
Do you intend to try to fix it? The plugin was so useful and there's no other autoscroll markdown plugin for vim.

**Comment by Giatroo** [comment]
If it was a recognizing problem, the `g:mkdp_command_for_global` variable should fix it, right? I tried to set it to 1, but the plugin is still not working. 
I tried to call the `open_preview_page()` function directly, but it also didn't work. Are you sure the problem is the plugin not recognizing the right filetype?

**Comment by iamcco** [comment]
I can not reproduce the issue, so I don't know how to fix it.

**Comment by iGormilhit** [comment]
@iamcco On my side it seems that the issue is related to [vim-pandoc](https://github.com/vim-pandoc). It set the filetype for markdown files to `pandoc`, which is not recognized by `markdown-preview`. If I disactivate `vim-pandoc` or `:setfiletype markdown`, then the preview is working fine.

I tried the `let g:pandoc#filetypes#pandoc_markdown = 0` without much success, as the author of vim-pandoc/vim-pandoc#382 tried too.

**Comment by iGormilhit** [comment]
There is many things to be read on the vim-pandoc repo. So I tried to move the `let g:pandoc#filetypes#pandoc_markdown = 0 ` before loading the vim-pandoc pluging and I can get the filetype I want. But, then, I don't get any markdown formatting.

Would it be possible, and a good idea, that `markdown-preview` could have a setting to recognize the `pandoc` or `markdown.pandoc` filetype ?

**Comment by iamcco** [comment]
@iGormilhit Update and set `let g:mkdp_filetypes = ['markdown']` filetypes you want.
