### ISSUE TITLE
Display math in lists defines a new line implicitly | 在列表中使用display math时会断行

### ISSUE THREAD

**Issue by lygamac** [iamcco/markdown-preview.nvim#257]
![image](https://user-images.githubusercontent.com/49118209/98487533-ce94f380-2223-11eb-8ccb-86cb22628e1b.png)

如图，在display math后面的item已经不算在前面的item list里面了。

**Comment by iamcco** [comment]
`$$x+y=z$$` 本来就是块级的，你要行内的就用 `$x+y=z$`

**Comment by lygamac** [comment]
不，如果在前面留点空格的话是不会强制断行的

![image](https://user-images.githubusercontent.com/49118209/98666705-ac979000-234d-11eb-8e85-8c5cd32da751.png)

（不过好像其他markdown预览也有这个问题）
