### ISSUE TITLE
markdown-preview.nvim 运行报错

### ISSUE THREAD

**Issue by heguohui2018** [iamcco/markdown-preview.nvim#259]
当我正要引入一张本地图片的时候，出现了如下错误。

错误提示：
[markdown-preview.nvim] uncaught exception: Error: EISDIR: illegal operation on a directory, read

截图:

<img width="1440" alt="Screen Shot 2020-11-12 at 19 25 08" src="https://user-images.githubusercontent.com/35359288/98935763-f5eb0980-251e-11eb-84c5-25c07408bbe6.png">

页面无法渲染：

<img width="814" alt="Screen Shot 2020-11-12 at 19 41 54" src="https://user-images.githubusercontent.com/35359288/98935934-39457800-251f-11eb-8928-b9ee1c435bd3.png">

**Comment by iamcco** [comment]
这图片是不是没有，而且名字有空格，\ 转义下看看

**Comment by heguohui2018** [comment]
我是在neovim使用自动补全路径，不会错，然后我就尝试了使用图床工具来把图片网址粘贴进去，也不能正常显示图片，

我到网上去下了个GUI markdown软件来弄也不能正常显示，

哦我也没排查出究竟是我的电脑故障还是插件原因。

**Comment by iamcco** [comment]
不懂，没遇到过
