### ISSUE TITLE
html 标签中 katex 不能正常预览

### ISSUE THREAD

**Issue by Voghost** [iamcco/markdown-preview.nvim#260]
作者你好，我在使用 html的表格时，发现公式不能正常显示，似乎所有有html标签包裹的公式的都不能显示

像下面的公式
```html
<div> $a_b$ </div>
```
![Screenshot_20201118_224914](https://user-images.githubusercontent.com/49421354/99545381-49ae9480-29f0-11eb-8c68-729db703706c.png)

**Comment by iamcco** [comment]
html包着就是html内容，不支持
