### ISSUE TITLE
Vundle installation

### ISSUE THREAD

**Issue by ennmichael** [iamcco/markdown-preview.nvim#261]
Could you add instructions for installing via Vundle? They're missing from the readme, and I think they'd be useful to many people, as Vundle is a popular plugin manager.

**Comment by iamcco** [comment]
I don't use Vundle so I don't know what's right way to install plug. PR is welcome if you use Vundle.

**Comment by ennmichael** [comment]
Right, thanks. Will make a PR.

**Comment by ennmichael** [comment]
I don't think Vundle can do this (specify a command to run after installing the plugin). Isn't there a cross-manager way to do this, such as checking if the command was run and if not, then running the command during plugin initialization? I'm pretty sure I've seen other plugins do it that way.

**Comment by abhinavdhere** [comment]
I faced the same issue as @ennmichael , as I have been Vundle and it seemed redundant to install Plug just for this one packaged. I figured out the way to get this working with Vundle. I can send a PR to add instructions to README, if you say, @iamcco .

My environment : 
neovim v.0.4.3 , terminal - bash with Ubuntu 20.04

Instructions to install:
1. Add following to your .vimrc or ~/.config/nvim/init.vim, 
`Plugin 'iamcco/markdown-preview.nvim'`

2. Source the ~/.vimrc file and run :PluginInstall
At this point, Vundle will the show the plugin as installed but it won't work yet.

3. Run `:call mkdp#util#install()` from vim

**Comment by iamcco** [comment]
> I faced the same issue as @ennmichael , as I have been using Vundle and it seemed redundant to install Plug just for this one package. I figured out the way to get this working with Vundle. I can send a PR to add instructions to README, if you say, @iamcco .
> 
> My environment :
> neovim v.0.4.3 , terminal - bash with Ubuntu 20.04
> 
> Instructions to install:
> 
> 1. Add following to your .vimrc or ~/.config/nvim/init.vim,
>    `Plugin 'iamcco/markdown-preview.nvim'`
> 2. Source the ~/.vimrc file and run :PluginInstall
>    At this point, Vundle will the show the plugin as installed but it won't work yet.
> 3. Run `:call mkdp#util#install()` from vim

@abhinavdhere PR is welcome

**Comment by ennmichael** [comment]
@iamcco @abhinavdhere That's not really a solution... any other plugin I've ever installed, I've never had to run an extra command after installing it. And all of those plugins work just as well with any plugin manager. I think that this should be fixed instead of just being "documented"
