### ISSUE TITLE
Open Preview in a New Window

### ISSUE THREAD

**Issue by Tritaya** [iamcco/markdown-preview.nvim#262]
Is this possible to open a markdown preview in a new window, and not in another tab of the existing browser?

I use Chrome and I tried to edit:
```
let g:mkdp_browser = ''
```
to:
```
let g:mkdp_browser = 'chrome /new-window'
```
but that doesn't help.

**Comment by iamcco** [comment]
use your own function to open preview page.

``` vim
" a custom vim function name to open preview page
" this function will receive url as param
" default is empty
let g:mkdp_browserfunc = ''
```

**Comment by victorbr92** [comment]
Doing like suggested here https://github.com/iamcco/markdown-preview.nvim/issues/19#issuecomment-464344382 with `vim-dispatch` works perfectly on Linux.

**Comment by iamcco** [comment]
```vim
  function OpenMarkdownPreview (url)
    execute "silent ! firefox --new-window " . a:url
  endfunction
  let g:mkdp_browserfunc = 'OpenMarkdownPreview'
```

**Comment by ret2src** [comment]
Here's a pretty dirty "Lua implementation" for you folks that try to go full Lua:

``` lua
vim.cmd(
[[
function OpenMarkdownPreview (url)
  execute "silent ! chromium --new-window --app=" . a:url
endfunction
]]
)

vim.g.mkdp_browserfunc = 'OpenMarkdownPreview'
```

Oh well. Not particularly aesthetic, but at least it seems to work.

Suggestions on how to re-implement the above in pure Lua are welcome.
