### ISSUE TITLE
处理function <SNR>55_serverStart[10]..mkdp#browserStart[2]..<SNR>85_broswerStart 时发生错误

### ISSUE THREAD

**Issue by wangpeihere** [iamcco/markdown-preview.nvim#266]
**Describe the bug**
处理function <SNR>55_serverStart[10]..mkdp#browserStart[2]..<SNR>85_broswerStart 时发生错误：
第 19行：
E371：找不到命令

**To Reproduce**
系统环境：Windows 10，Gvim8.2
打开运行MardownPreview
**Expected behavior**
调用chrome打开预览

**Screenshots**
![image](https://user-images.githubusercontent.com/5195404/100518194-12e43580-31cb-11eb-8902-6e6bee9162c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Vim: gVim8.2

**Comment by iamcco** [comment]
是不是搞错插件了，旧版本的才有这个函数

旧 https://github.com/iamcco/markdown-preview.vim
新 https://github.com/iamcco/markdown-preview.nvim

这两个是不同的插件
