### ISSUE TITLE
E17:unkown function mkdp#util#install()

### ISSUE THREAD

**Issue by MengShengHui** [iamcco/markdown-preview.nvim#267]
安装好了之后 ，输入markdownpreview 没有智能补全，也就 是说没有这个命令，输入mess也没什么报错，就只是输出，简体中文消息维护者。
我的环境：deepin，基于 debian
 vim  version=8.1
谢谢大佬 ，帮看下

**Comment by iamcco** [comment]
怎么安装的，用的什么系统
