### ISSUE TITLE
WSL support?

### ISSUE THREAD

**Issue by roachsinai** [iamcco/markdown-preview.nvim#27]
Could you please add support for WSL?

**Comment by iamcco** [comment]
It's possible to support WSL, but i don't have the WSL environment. i have to setup the environment when i have time.

**Comment by roachsinai** [comment]
Okay!

**Comment by nickjj** [comment]
Everything is working here with WSL on Windows 10 Pro 18.09 (stable).

My environment is:

- WSL Ubuntu 18.04
- Terminal Vim 8.0 is installed inside of WSL (Ubuntu 18.04's repo)
- Node v8.10.0 is installed in WSL (Ubuntu 18.04's repos)
- Chrome is installed directly in Windows (not in WSL)

Upon loading a markdown file with Vim and and running `:MarkdownPreview` this plugin will either open a brand new Chrome window if one doesn't exist, or open a new tab in an existing Chrome window.

I didn't have to do anything extra to get all of this to work. It worked out of the box. My dotfiles are at https://github.com/nickjj/dotfiles which contains my vimrc, etc..

**Comment by roachsinai** [comment]
@iamcco @nickjj Thanks a lot. So sorry that I forgot to install `yarn`.

And now it worked.

**Comment by 0re5ama** [comment]
In my case, the server starts, but it doesn't load in a browser. Using the option: `let g:mkdp_echo_preview_url = 1`, I can see the url and open in the browser manually though.

**Comment by 0re5ama** [comment]
@roachsinai , Thank you. I did do that. I just found the solution from this comment in issue 309. https://github.com/iamcco/markdown-preview.nvim/issues/309#issuecomment-830646726

Seems I had installed mono at some time and I wasn't using that, so removed it and now, it works.

**Comment by MOISESOROAROLITEC** [comment]
a
