### ISSUE TITLE
Set global not working

### ISSUE THREAD

**Issue by fecet** [iamcco/markdown-preview.nvim#275]
I set let g:mkdp_command_for_global = 1 in init.vim, but still return E492: Not an editor command: MarkdownPreview in .rmd file, following is my minimal init.vim

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
let g:mkdp_browser = 'msedge'
let g:mkdp_command_for_global = 1
```

**Comment by iamcco** [comment]
Can't reproduce, what's your vim or neovim version?

**Comment by iamcco** [comment]
OK I see, remove the code `'for': ['markdown', 'vim-plug']`
