### ISSUE TITLE
./install.sh 报错

### ISSUE THREAD

**Issue by KylinskyChen** [iamcco/markdown-preview.nvim#277]
jerome@jerome:~/.vim/plugged/markdown-preview.nvim/app$ ./install.sh 
 Fetching latest release.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 rate limit exceeded
 Command failed (exit code 22): curl --fail -L https://api.github.com/repos/iamcco/markdown-preview.nvim/releases/latest
 Downloading binary from https://github.com/iamcco/markdown-preview.nvim/releases/download//markdown-preview-linux.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
 Command failed (exit code 22): curl --fail -L https://github.com/iamcco/markdown-preview.nvim/releases/download//markdown-preview-linux.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
! Binary not available for now, please wait for a few minutes.

一直出现这个情况，请问这个是咋回事？

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/104123341-af325800-5385-11eb-89aa-a327952d4c0e.png)

你的网络访问github有问题
