### ISSUE TITLE
Error：Cannot find module "tslib"

### ISSUE THREAD

**Issue by acnx** [iamcco/markdown-preview.nvim#278]
hi, when I installed it, the information is as follows:
[![rNYPlq.png](https://s3.ax1x.com/2020/12/19/rNYPlq.png)](https://imgchr.com/i/rNYPlq)
How can I solve it？

**Comment by iamcco** [comment]
Go to the plugins/app direction and run `yarn install` or `npm install`

**Comment by acnx** [comment]
Thank you very much. It's already running
