### ISSUE TITLE
E475: Invalid argument: Channel id must be a positive integer

### ISSUE THREAD

**Issue by steadystatic** [iamcco/markdown-preview.nvim#28]
Really excited about this plugin - thanks!

I had a successful session but the last two times have run into this error:

Error detected while processing function <SNR>304_try_open_preview_page[4]..mkdp#rpc#stop_server:
line   19:
E475: Invalid argument: Channel id must be a positive integer

Environment is NVIM v0.3.4 on macOS inside of a tmux session

I tried kill -9 $(pgrep node) and killed the process, but then restarting but same error.

**Comment by iamcco** [comment]
seems you use an old version. try to update the plugin to see if it still have the problem

**Comment by iamcco** [comment]
closed, reopen if you still have any question.
