### ISSUE TITLE
nothing showup after : MarkdownPreview

### ISSUE THREAD

**Issue by sunbowei1986** [iamcco/markdown-preview.nvim#281]
**Describe the bug**
My log is attached,and installation success but when I try to use it , nothing show up.,I use ubuntu 20.04lts neovim via Sudo apt install neovim check for python3 ok and other things also ok,but nothing work with mkdp

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

Log:

```
```
[faq.txt](https://github.com/iamcco/markdown-preview.nvim/files/5773391/faq.txt)

**Comment by iamcco** [comment]
删了重装下看看，看着像是缺少东西

**Comment by sunbowei1986** [comment]
> Try remove and reinstall, seems it missing some files.

Thanks and it works!
