### ISSUE TITLE
Preview fails to start.

### ISSUE THREAD

**Issue by GideonWolfe** [iamcco/markdown-preview.nvim#286]
**Describe the bug**

When I try and launch markdown preview, I get the following errors, and the entire neovim buffer freezes and must be killed. 

![image](https://user-images.githubusercontent.com/32942052/104347406-6e396100-54b5-11eb-86e9-329772d5e639.png)

When I launch vim with `nvim -V10nvim.log test.md` and try to launch the preview, I see lines like

```
line 4: sourcing "/home/gideon/.vim/plugged/markdown-preview.nvim/autoload/mkdp/rpc.vim"
finished sourcing /home/gideon/.vim/plugged/markdown-preview.nvim/autoload/mkdp/rpc.vim
continuing in function mkdp#util#toggle_preview[2]..mkdp#util#open_preview_page
[markdown-preview.nvim] uncaught exception: Error: listen EADDRINUSE 127.0.0.1:3456
    at Server.setupListenHandle [as _listen2] (net.js:1327:14)
    at listenInCluster (net.js:1375:12)
    at doListen (net.js:1501:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**To Reproduce**
1. Open markdown file in neovim
2. Activate markdown preview 
3. see error
4. Try and launch markdown preview again
5. Get error in screenshot, nvim freezes

**Expected behavior**
Preview opens in next available Firefox window.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Arch Linux

Log:

```
above
```

Note: This was literally working perfectly not 12 hours ago. I went to bed, woke up, and now it doesn't work. I'm honestly struggling to find out what broke. It looks like the address is in use, but where?

**Comment by KalStormBYU** [comment]
My situation is not very similar, but in the same vein. I've tried installing this plugin a number of ways, and I can never actually get the preview started. I don't have access to the :MarkdownPreview command, even after installing with Vim-Plug, and with the :call method. Was there some other step I needed to do to activate it?

**Comment by GideonWolfe** [comment]
Hmm, I'm not sure about that, I haven't had any real issues in the months since I successfully installed it via `vim-plug`. My configuration is [here](https://github.com/GideonWolfe/vim.reaper) for reference.

**Comment by KalStormBYU** [comment]
I can't really see anything different in yours than mine. I guess I'll keep trying things out. Thanks.

**Comment by GideonWolfe** [comment]
A system reboot fixed the issue.
