### ISSUE TITLE
在msys2中使用插件时出现的问题和解决方法

### ISSUE THREAD

**Issue by vermilion-bird** [iamcco/markdown-preview.nvim#291]
首先感谢作者提供这么棒的插件！

**Describe the bug**
在win10 20H2上的msys2平台中使用插件时调用MarkdownPreview没有反应，使用的是msys2平台下的vim 8.2(包含补丁1-1895）和windows平台下的nodejs 14.15.1和yarn 1.22.10。

**To Reproduce**
1. 根据插件readme添加配置：
![屏幕截图 2021-01-26 211641](https://user-images.githubusercontent.com/50539935/105862187-7a333000-602a-11eb-8e9f-6e5b728187d9.png)

2. 使用PlugInstall安装后，编辑markdown文件时出现问题：
![屏幕截图 2021-01-26 211404](https://user-images.githubusercontent.com/50539935/105862321-9df67600-602a-11eb-81c4-8d37810da130.png)
![屏幕截图 2021-01-26 211456](https://user-images.githubusercontent.com/50539935/105862780-2543e980-602b-11eb-82d8-c2781aa90491.png)

3. 查找其他issue后发现应该是安装不完整，仅使用yarn安装似乎不行（下图显示yarn安装成功了，但是仍存在这个问题）：
![屏幕截图 2021-01-26 211327](https://user-images.githubusercontent.com/50539935/105862586-e9108900-602a-11eb-8f4d-33eee0ed80bc.png)

4. 将配置文件修改成：
![屏幕截图 2021-01-26 212340](https://user-images.githubusercontent.com/50539935/105862406-b49ccd00-602a-11eb-820e-6c488080fddb.png)
后重新安装插件，编辑markdown文件时不再报错，但使用MarkdownPreview没有反应。

5. 继续查找issue，发现有人也遇到过类似的问题，参考 #220 后发现应该是插件未能正确识别当前平台导致的，将插件中 ```autoload/mkdp/nvim/rpc.vim``` 文件的第6行
```
let s:is_win = has("win32") || has("win64")
```
修改为
```
let s:is_win = has("win32") || has("win64") || has("win32unix")
```
后问题解决，能够正常使用插件。

* 目前按上述步骤设置后在我的电脑上使用是没有问题的，也没有发现这样会引起其他什么问题，作者有空的话请看看这样是否能解决这个问题。

* 顺便一提，使用时发现要调用edge浏览器的话需要将浏览器指定为
```
let g:mkdp_browser = 'msedge'
```

**Comment by iamcco** [comment]
欢迎提 PR

**Comment by iamcco** [comment]
https://github.com/iamcco/markdown-preview.nvim/pull/304
