### ISSUE TITLE
[Feature request] Support GitHub dark mode

### ISSUE THREAD

**Issue by MisanthropicBit** [iamcco/markdown-preview.nvim#297]
Thanks for this awesome plugin!

Although it is still in beta as of this writing, GitHub now supports a dark mode that can be enabled in the settings. Consequently, it would be great to have a preview that renders in dark mode. For example:

`:MarkdownPreview [dark|light]` (where a missing argument defaults to `light` mode)

**Comment by reegnz** [comment]
This was not made toggle-able as the issue requested, but uses the OS-preferred light/dark mode instead. I propose a reopen or continue implementing allowing toggling in #306.
