### ISSUE TITLE
Local image not displayed on Firefox

### ISSUE THREAD

**Issue by gbcreation** [iamcco/markdown-preview.nvim#3]
Content of the `test.md` file:

```markdown
![image](image.png)
```

The `image.png` is in the same folder as the `test.md` file, but it is not visible in the preview. The link of the `img` element in the HTML preview is `http://127.0.0.1:8568/_local_image_image.png`.

However, it works on Chromium.

**Comment by iamcco** [comment]
I can't reproduce this with firefox v64.0

> The link of the img element in the HTML preview is http://127.0.0.1:8568/_local_image_image.png.

it's correct.

you can set the following to you init.vim and upload the log file:

```viml
let $NVIM_MKDP_LOG_FILE = expand('~/mkdp.log')
let $NVIM_MKDP_LOG_LEVEL = 'debug'
```
