### ISSUE TITLE
yarn install not working

### ISSUE THREAD

**Issue by OneiricJansky** [iamcco/markdown-preview.nvim#30]
Hi, when using vim-plug or by installing by hand, yarn is breaking:
:!cd app & yarn install

Calling shell to execute: "cd app & yarn install"
shell returned 1

I'm using the vim-plug instructions from the README.md.

Thoughts?

Thanks!

**Comment by OneiricJansky** [comment]
I was able to fix it by installing the latest yarn on ubuntu by using these instructions:

https://yarnpkg.com/lang/en/docs/install/#debian-stable

Thanks

**Comment by iamcco** [comment]
Not sure what happen the shell returned 1. But it's not support by hand to execute `:!cd app & yarn install` in command line, because it need to execute this command in the plugin directory.
