### ISSUE TITLE
能否添加 graph-easy 绘制 ascii 图功能？

### ISSUE THREAD

**Issue by QMHTMY** [iamcco/markdown-preview.nvim#300]
![ascii](https://user-images.githubusercontent.com/20437653/107489946-314faf80-6bc4-11eb-8fef-64fc3a0bc559.png)

**Comment by QMHTMY** [comment]
大佬的这个插件不错，不知能否支持在markdown 里绘制这种 ascii 图？

**Comment by iamcco** [comment]
搜了下这个不是js实现的，目前渲染都是在浏览器端实现的，看其他人有没有办法

**Comment by QMHTMY** [comment]
多谢，祝新年快乐！
