### ISSUE TITLE
无法预览

### ISSUE THREAD

**Issue by limeiwang** [iamcco/markdown-preview.nvim#305]
```
" vimrc文件
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
 
Plugin 'vim-airline/vim-airline'
Plugin 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install_sync() }, 'for' :['markdown', 'vim-plug'] }

call vundle#end()
filetype plugin indent on


" ===
" === MarkdownPreview
" ===
let g:mkdp_auto_start = 0
let g:mkdp_auto_close = 1
let g:mkdp_refresh_slow = 0
let g:mkdp_command_for_global = 0
let g:mkdp_open_to_the_world = 0
let g:mkdp_open_ip = ''
let g:mkdp_browser = 'chromium'
let g:mkdp_echo_preview_url = 0
let g:mkdp_browserfunc = ''
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1
    \ }
let g:mkdp_markdown_css = ''
let g:mkdp_highlight_css = ''
let g:mkdp_port = ''
let g:mkdp_page_title = '「${name}」'
```
这是我的vimrc文件，插件安装完以后。执行:MarkdownPreview
提示：no matching autocommands

**Comment by lmw0221** [comment]
求助求助！！

**Comment by iamcco** [comment]
执行完命令后 `:mess` 看下有啥报错信息

**Comment by limeiwang** [comment]
Messages maintainer: Bram Moolenaar <Br
am@vim.org>
"nodejs.md" 58L, 1151C
1 change; before #1  2 seconds ago
[vim-node-rpc] rpc error: internal/modu
les/cjs/loader.js:883
[vim-node-rpc] rpc error:   throw err;
[vim-node-rpc] rpc error:   ^
[vim-node-rpc] rpc error:
[vim-node-rpc] rpc error: Error: Cannot
 find module 'tslib'
[vim-node-rpc] rpc error: Require stack
:
[vim-node-rpc] rpc error: - /Users/dxm/
.vim/bundle/markdown-preview.nvim/app/l
ib/app/index.js
[vim-node-rpc] rpc error: - /Users/dxm/
.vim/bundle/markdown-preview.nvim/app/i
ndex.js
[vim-node-rpc] rpc error:     at Functi
on.Module._resolveFilename (internal/mo
dules/cjs/loader.js:880:15)
-- More -- SPACE/d/j: screen/page/line

**Comment by iamcco** [comment]
插件目录app目录下执行 `yarn install` 或者 `npm install`

**Comment by iamcco** [comment]
或者 打开 vim 后执行 `:call mkdp#util#install_sync()`

**Comment by limeiwang** [comment]
chmod: markdown-preview-macos: No such file or directory

**Comment by limeiwang** [comment]
vim 后执行 :call mkdp#util#install_sync() 
报错：
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
 Command failed (exit code 35): curl --fail -L https://github.com/iamcco/markdown-preview.nvim/releases/download/v0.0.9/markdown-preview-macos.tar.gz

**Comment by iamcco** [comment]
> vim 后执行 :call mkdp#util#install_sync()
> 报错：
> curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
> Command failed (exit code 35): curl --fail -L https://github.com/iamcco/markdown-preview.nvim/releases/download/v0.0.9/markdown-preview-macos.tar.gz

你的网络不行，国内环境下载github的release资源不太行。你还是插件目录的app文件夹下 `yarn install` 或 `npm install`

**Comment by brucejuz** [comment]
我出现同样问题，用这个方法“vim 后执行 :call mkdp#util#install_sync()”解决了，在不同时间段试试，开始出现报错，后来突然网络好了，就可以了。
