### ISSUE TITLE
Allow for toggling dark-mode in the preview window

### ISSUE THREAD

**Issue by reegnz** [iamcco/markdown-preview.nvim#306]
**Describe the bug**
I'm using dark-mode in my OS, however the dark mode preview for markdown is pretty annoying to me.
I want to be able to preview in light mode as well, because I want to see how my markdown looks both in dark mode and light mode. Now I can only do that by disabling dark-mode in my entire OS.

https://github.com/iamcco/markdown-preview.nvim/pull/302 introduced dark-mode for when an OS is set to dark mode.
It would be great to make a toggle on the preview window, and default to the OS color scheme, but allow switching between light and dark right in the preview window.

**Comment by shoichiaizawa** [comment]
Same here 🙋 I have just toggled the preview literally right now and have found that the dark mode preview had been introduced. I also use the Dark mode in my OS (macOS) but prefer the light mode for Markdown Preview.

**Comment by jotix16** [comment]
any solution ye? how to turn it off?

**Comment by reegnz** [comment]
My solution was to just go into the vim plugin and delete the CSS. I'd rather have a cleaner solution though, than to fork it for my own purposes.

**Comment by jotix16** [comment]
thank you @reegnz

**Comment by iamcco** [comment]
It's supported
