### ISSUE TITLE
如何使用katex设置里的布尔变量？

### ISSUE THREAD

**Issue by lygamac** [iamcco/markdown-preview.nvim#311]
katex的官方[doc](https://katex.org/docs/options.html)里的示例：
```
katex.render("c = \\pm\\sqrt{a^2 + b^2}\\in\\RR", element, {
  displayMode: true,
  macros: {
    "\\RR": "\\mathbb{R}"
  }
});
```
这是我设置文件里的设置：
```
\ 'katex': {
\ 	'displayMode': true, " <--- 这里
\ 	'macros': {
\ 		"\\RR": "\\mathbb{R}"
\ 	}
\ },
```

macros可以使用，没有问题。displayMode不带引号会报错，带了引号或者替换为1跟0都没有任何效果。

**Comment by iamcco** [comment]
`'displayMode': v:true` 这样呢

**Comment by lygamac** [comment]
不会报错，但是无效
![image](https://user-images.githubusercontent.com/49118209/110243711-cc397080-7f5b-11eb-8796-87ef954b2214.png)

**Comment by iamcco** [comment]
传值应该是没问题的，不过现在如果你用inline 方式`$\int$` displayMode 默认是false的，display方式`$$\int$$`默认是开启的

可以添加个判断，不覆盖用户的配置

![image](https://user-images.githubusercontent.com/5492542/110244464-be0a4500-7f99-11eb-82c5-62b483447db8.png)
