### ISSUE TITLE
插件安装错误--Could not load library winpty64.dll

### ISSUE THREAD

**Issue by blue-cloak** [iamcco/markdown-preview.nvim#32]
问题描述：
执行`call mkdp#util#install()`
出现`Could not load library winpty64.dll`

运行环境：
Windows 10, gVim 8.1 64bit with python and python3 support for 64 bit

我斗胆猜测是因为我的Vim是64位的……

**Comment by iamcco** [comment]
感觉是 gvim 本身安装的有问题，是不是缺少了这个？貌似 `winpty64` 是vim自己在用 https://github.com/vim/vim/pull/1978

**Comment by blue-cloak** [comment]
@iamcco 厉害厉害，我重新下载了最新版本的Vim编译后就好了。
Case closed by using Vim after patch 8.0.0949, many thanks.
