### ISSUE TITLE
preview multi files support

### ISSUE THREAD

**Issue by durd07** [iamcco/markdown-preview.nvim#326]
when I open markdown-preview, it shows the preview in http://127.0.0.1:8929/page/1
then I open another file, it shows in another chrome tab like http://127.0.0.1:8929/page/3,

Is it possible to preview always in one chrome tab and auto refresh it when I open another file?

like what does https://github.com/euclio/vim-markdown-composer works?

**Comment by durd07** [comment]
dup with https://github.com/iamcco/markdown-preview.nvim/issues/284

**Comment by durd07** [comment]
like what does https://github.com/euclio/vim-markdown-composer works?

**Comment by RocketMaDev** [comment]
@iamcco great plugin, so plz add this function! I scrolled between files today and sadly found that I have to adjust the browser tabs every time. A cup of milktea has sent to you, hope that could stir up your ethusiasm to improve this repo!😉

**Comment by iamcco** [comment]
```vim
" combine preview window
" default: 0
" if enable it will reuse previous opened preview window when you preview markdown file.
" ensure to set let g:mkdp_auto_close = 0 if you have enable this option
let g:mkdp_combine_preview = 0
```

**Comment by RocketMaDev** [comment]
It seems that i need to switch on mkdp auto start in order to have a fluent experience.

**Comment by iamcco** [comment]
I have add `g:mkdp_combine_preview_auto_refresh` option which default is 1.

**Comment by RocketMaDev** [comment]
非常好改进，爱来自火箭😉
