### ISSUE TITLE
[With possible workaround] Node warning when opening the preview

### ISSUE THREAD

**Issue by kqwyf** [iamcco/markdown-preview.nvim#335]
**Describe the bug**
When opening the preview, a warning occurs: `Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`. While the preview still works, this is very annoying.

![图片](https://user-images.githubusercontent.com/22416169/117394233-5d12d500-af28-11eb-90ca-d5486266cea8.png)

**To Reproduce**
1. Install the plugin.
2. Set `let g:mkdp_auto_start = 1`. (didn't test if it still occurs when this variable is 0)
3. Open a Markdown document.

**Expected behavior**
Preview works without warning prompt.

**Environment:**
 - OS: Manjaro KDE (2021.05.07)
 - Nodejs: v16.0.0
 - npm: 7.12.0
 - yarn: 1.22.10

**Possible solution/workaround:**
- Run `cd app && yarn upgrade` after installation.

The reason seems to be an old version of package `winston`, which is required by package `neovim`. See [winston#1797](https://github.com/winstonjs/winston/issues/1797). A simple `cd app && yarn upgrade` get me on the way.

Since I'm not familiar with nodejs programming, I'm not sure whether this is an elegant solution. Hoping anyone provide a final solution and commit it. Thanks!

**Comment by iamcco** [comment]
fix with latest version
