### ISSUE TITLE
Auto close vim using `vim +PlugInstall +qall`

### ISSUE THREAD

**Issue by yutakatay** [iamcco/markdown-preview.nvim#34]
I installed using this commad `vim +PlugInstall +qall`.
It closed vim automatically after installed plugins.

But It does not close with the following message :cry:

```
!./install.sh v0.0.9 [running]
[markdown-preview.nvim]: install completed
```

I also checked neovim. neovim is OK.

## Info

VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  6 2019 21:38:32)

config

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}
```

**Comment by iamcco** [comment]
> I also checked neovim. neovim is OK.

I think it is just exit neovim and the install is not completed

I have add `mkdp#util#install_sync` and use it instead if you want to do sync

``` vim
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install_sync() }}
```

**Comment by yutakatay** [comment]
Thank you for replay :smile:

I changed to ` mkdp#util#install_sync()`.
It got better :wink:

But
```
Press ENTER or type command to continue
```
was displayed.

I don't like it. Can I suppress this message?

**Comment by iamcco** [comment]
Use `mkdp#util#install_sync(v:true)` if you don't want to see the process output.

**Comment by yutakatay** [comment]
Perfect!!

Thank you very much :joy:
