### ISSUE TITLE
Support for Packer

### ISSUE THREAD

**Issue by kdrahul** [iamcco/markdown-preview.nvim#354]
Hey,
Now that Neovim has switched to 0.5.0. A lot of people are using packer as their package manager.
So will there be support for using Markdown-Preview through packer?

I'm fairly new to lua so there's a good chance that I'm missing how to configure it.
Please do update the README if packer option already exists

**Comment by msricher** [comment]
Hi, I just came here looking for a solution to this problem myself, and I ended up getting it working with this `packer.use` declaration:
`use {'iamcco/markdown-preview.nvim', run = [[sh -c 'cd app && yarn install']]}`

**Comment by kdrahul** [comment]
The installation part of it works, even without the run part. But when I do `:MarkdownPreview` it doesn't do anything.

**Comment by JavaLich** [comment]
I had the same issue as @kdrahul, which was fixed by manually running yarn install in the directory where markdown-preview is installed by packer.

**Comment by vuki656** [comment]
Had the same issue. After going into the folder manually and running `yarn` it produced some errors regarding not being able to get some packages.

The hacky fix was to delete `yarn.lock` and run `yarn`

**Comment by marcustut** [comment]
It turns out that it might be we haven't load the plugin. 

just run `:PackerLoad markdown-preview.nvim` 

then it will work

**Comment by kdrahul** [comment]
Nope that didn't work either.

**Comment by Utkarsh-khambra** [comment]
I use this in packer 
`use({
		"iamcco/markdown-preview.nvim",
		run = "cd app && npm install",
		setup = function()
			vim.g.mkdp_filetypes = { "markdown" }
		end,
		ft = { "markdown" },
	})`

**Comment by kdrahul** [comment]
Thanks that works.
