### ISSUE TITLE
Vim 打开预览失败

### ISSUE THREAD

**Issue by mrbeardad** [iamcco/markdown-preview.nvim#359]
**Describe the bug**
报错：
```
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '/home/beardad/.cache/vimfiles/repos/github.com'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**To Reproduce**
1. ·cd app && yarn install`
2. `vim ../README.md`
3. `:MarkdownPreview`

**Expected behavior**
像neovim一样正常启动浏览器

**Screenshots**
![image](https://user-images.githubusercontent.com/54128430/125890023-60c2790b-5e95-4a97-84fb-9b31af53e135.png)

**Desktop (please complete the following information):**
 - OS: Linux heachxiong-PC0 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
- OS: Linux manjaro 5.10.49-1-MANJARO #1 SMP PREEMPT Sun Jul 11 12:59:43 UTC 2021 x86_64 GNU/Linux

Log:
```
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module '/home/beardad/.cache/vimfiles/repos/github.com'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by feng2r200** [comment]
I had some error like this, I deleted the yarn.lock in markdown-preview.nvim and markdown-preview.nvim/app. then use yarn install && yarn upgrade in markdown-preview.nvim. It works

**Comment by CrazyGriferman** [comment]
Thanks! I met the same problem and solved by manually installing this plugin.

**Comment by iamcco** [comment]
fix with latest version
