### ISSUE TITLE
About the math of typesetting

### ISSUE THREAD

**Issue by howie6879** [iamcco/markdown-preview.nvim#36]
Hi:

Thanks for your great job,  I have a problem with typesetting math.

For example:
``` txt
 $x=(x\_{1},x\_{2},...,x\_{j})$
```
it can work well in this project: https://github.com/iamcco/markdown-preview.vim

![image](https://user-images.githubusercontent.com/17047388/54812163-69466480-4cc5-11e9-967b-828aee314a4b.png)

But not in this case

![image](https://user-images.githubusercontent.com/17047388/54812069-2e443100-4cc5-11e9-851a-4f1c0d4f1adb.png)

I knew the problem was caused by the escape character, but I couldn't avoid it during the [rendering process](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML).

Do you have a solution?

**Comment by iamcco** [comment]
Maybe a test on https://katex.org/#demo to see if it works ?  The new plugin use Katex for typesetting math.

**Comment by howie6879** [comment]
Do you think that the '\' character will have an effect?
This project named https://github.com/iamcco/markdown-preview.vim can solve the problem
Unfortunately, It was abandoned.

**Comment by iamcco** [comment]
> Do you think that the '\' character will have an effect?

`$x=(x_{1},x_{2},...,x_{j})$` seem works well.

**Comment by howie6879** [comment]
> `$x=(x_{1},x_{2},...,x_{j})$` seem works well.

No, The raw HTML is `$x=(x\_{1},x\_{2},...,x\_{j})$`, it works well under the https://github.com/iamcco/markdown-preview.vim

But not in this project~

**Comment by iamcco** [comment]
I don't know if it's a bug. if so you can report it to https://github.com/KaTeX/KaTeX or  https://github.com/waylonflinn/markdown-it-katex

**Comment by howie6879** [comment]
Hi @iamcco : 

My blog is based on Hugo, I found the problem caused by Hugo's Markdown rendering engine.

Especially in the support of escape characters, `mmark` will be more friendly.

So all I have to do is set it up like this
```
markup: mmark
```

Thanks a lot
