### ISSUE TITLE
vim-plun 转 dein 出现的问题。

### ISSUE THREAD

**Issue by hyaray** [iamcco/markdown-preview.nvim#372]
安装配置，官方说是
call dein#add('iamcco/markdown-preview.nvim', {'on_ft': ['markdown', 'pandoc.markdown', 'rmd'],
					\ 'build': 'sh -c "cd app && yarn install"' })
这应该是Linux的配置，windows 下 sh -c 是不行的，直接用 'cd app && yarn instal' 可行？
:MarkdownPreview 后，功能正常，但是有错误提示，不知道是什么原因。请求帮助：
环境win10，vim8

[vim-node-rpc] rpc error: (node: 7020 Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
[vim-node-rpc] rpc error:Use `node --trace-warnings ...` to show where the warning was created)
(node: 18284) Warning: Accessing non-existent property 'padLevels'c module exports inside circular dependency
(Use `node --trace-warings ...` to show where the warning was created)

**Comment by hyaray** [comment]
似乎是node版本太高的原因，用的14.17.5，希望能修复下，谢谢！

**Comment by oeyoews** [comment]
> 似乎是node版本太高的原因，用的14.17.5，希望能修复下，谢谢！
我使用nvm切换低版本后， 确实是这个原因

**Comment by resoliwan** [comment]
It is only worked at node
v10.24.1
-> v12.22.10
v14.17.5
v16.13.2

**Comment by hyaray** [comment]
用了最新的v16.13.2，还是同样的错误提示，功能正常，也就不太上心了，官方有心就修复下。

**Comment by iamcco** [comment]
`vim-node-rpc` 的问题，已经去掉了
