### ISSUE TITLE
Error: nvim_call_function : Vim:E117: Unknown function: open

### ISSUE THREAD

**Issue by zzLinus** [iamcco/markdown-preview.nvim#380]
用vim-plug安装插件，可以打:MarkdownPreview命令，但是会报标题错误．．．

**Comment by zzLinus** [comment]
我是通过　Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
安装的插件，安装过程没有报错

**Comment by zzLinus** [comment]
天哪．．．我好蠢．．．．自己写的脚本出问题了，实在不好意思打扰了．．．．

**Comment by VictorWinson** [comment]
@zzLinus Excuse me! What mistake did you make? How did you solve that? I've encountered something similar.
p.s. I can understand Chinese, just I don't have pinyin input method on this laptop right now.
