### ISSUE TITLE
Is it passiable to extract a packge that could convert markdown to html from this project

### ISSUE THREAD

**Issue by mrbeardad** [iamcco/markdown-preview.nvim#386]
I'm new in js and react, I have found some package that could convert markdown to html or react component.
But all of them don't work as well as markdown-preview,nvim does, so I'm think about is it passiable to extract a packge that could convert markdown to html from this project

**Comment by iamcco** [comment]
没有简单的方法，目前很多功能都是依赖浏览器的，所以目前还办不到直接转换
