### ISSUE TITLE
MarkdownPreview 命令打不开浏览器

### ISSUE THREAD

**Issue by ztby74** [iamcco/markdown-preview.nvim#389]
前天还能使用MarkdownPreview命令打开浏览器，今天就不行了。不知道怎么了，我尝试了卸载，重装，可还是不行。没有任何错误报告，能告诉我怎么解决？

**Comment by jashawnyu** [comment]
platform

**Comment by Littlesharkcug** [comment]
我也遇到了同样的问题，我一直无法使用MarkdownPreview命令打开浏览器。我使用了packer.nvim 包管理器 平台是Manjaro。

**Comment by siriusy** [comment]
我也是同样的问题，manjaro+firefox.

**Comment by zhaogangang** [comment]
i meet same problem above, it's normal just a few days ago, OS: ubuntu 20.4, vim:neovim 0.6, Web: chrome

**Comment by siriusy** [comment]
my problem solved by the follow steps:
`
cd ~/.vim/plugged/markdown-preview.nvim/app/
./install.sh
`
good luck!

**Comment by zhaogangang** [comment]
> 



> my problem solved by the following steps:
> 
> `cd ~/.vim/plugged/markdown-preview.nvim/app/`
> 
> `./install.sh`
> 
> good luck!

thank you, so do i

**Comment by zhaogangang** [comment]
> my problem solved by the following steps:
> 
> `cd ~/.vim/plugged/markdown-preview.nvim/app/`
> 
> `./install.sh`
> 
> good luck!

i am solved this problem yet, just follow above steps.

**Comment by Jiiiiiin** [comment]
同样的问题 macos packer

**Comment by thegxi** [comment]
> 
我也是Mac，我是这样解决的
```shell
cd ~/.config/nvim/plugged/markdown-preview.nvim/app
yarn install 
```

**Comment by iamcco** [comment]
报 `E492: Not an editor command: MarkdownPreview` 的话，确保你的 markdown 文件的 filetype 是 `markdown`

或者设置 `let g:mkdp_command_for_global = 1` 为所有文件启用

**Comment by Hustoking** [comment]
我的arch系统，输入MarkdownPrevie后什么都没有发生，浏览器没有打开也没有任何报错

**Comment by Brannua** [comment]
In archlinux, do `cd $XDG_DATA_HOME/nvim/plugged/markdown-preview.nvim/app`, then do `./install.sh`, done.
btw, do `echo $XDG_DATA_HOME` should be => `/home/username/.local/share`.

**Comment by Ghost-50** [comment]
![Uploading Screenshot_20230208161933.jpg…]()

**Comment by dirac-lee** [comment]
我是 MacOS 系统，使用的是 Astronvim，输入MarkdownPrevie 后什么都没有发生，浏览器没有打开也没有任何报错

**Comment by Tardouse** [comment]
> 我是 MacOS 系统，使用的是 Astronvim，输入MarkdownPrevie 后什么都没有发生，浏览器没有打开也没有任何报错

我也是macos，我现在是用手动的方法自己打开。
在init.vim中添加
```shell
let g:mkdp_open_to_the_world = 1
let g:mkdp_open_ip = '127.0.0.1' "
let g:mkdp_port = 4399
function! g:EchoUrl(url)
    :echo a:url
endfunction
let g:mkdp_browserfunc = 'g:EchoUrl'
```
然后再使用MarkdownPreview后，会给出地址，直接输入到浏览器就可以了。
