### ISSUE TITLE
Error when running :MarkdownPreview using vim

### ISSUE THREAD

**Issue by hansondr** [iamcco/markdown-preview.nvim#39]
When running :MarkdownPreview I get:

```
Error detected while processing function mkdp#util#open_preview_page[6]..mkdp#rpc#start_server[2]..<SNR>97_start_vim_node_rpc[4]..mkdp#nvim#rpc#start_server:
line   25:
E475: Invalid argument: env
```

I followed the nodejs and yarn vim-plug install instructions, 

`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }`

and the post install ran through Yarn successfully.

**Additional details**

NodeJS: v8.11.3
Yarn: 1.15.2
Vim: 8.0.550
vim-plug: 0.10.0
markdown-preview.nvim: v0.0.9

**Comment by iamcco** [comment]
> Vim: 8.0.550

This plugin works with vim >= 8.1

> markdown-preview.nvim: v0.0.9

You should use lastest master branch  instead of release version, the release version it's for the pre build loader.

**Comment by hansondr** [comment]
Thank you @iamcco!  I apologize, I missed the "It only works on vim >= 8.1 and neovim" right there in the README in my haste yesterday.  Updated vim and everything works swimmingly

**Comment by iamcco** [comment]
No problem.
