### ISSUE TITLE
plantuml opt not work

### ISSUE THREAD

**Issue by linc01** [iamcco/markdown-preview.nvim#398]
Hi there,

Is this the rightway to pass opt to plantuml parser?
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {
                imageFormat: 'png',
                server: https://your.server/plant-uml
               },
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {},
    \ 'flowchart_diagrams': {},
    \ 'content_editable': v:false,
    \ 'disable_filename': 0
    \ }
There's no change in the image format after the congiguration, still the default svg. The server is not set up yet, just want to know if there's an opt to replace the default one. Thanks.

**Comment by iamcco** [comment]
you config format for `uml` is invalid, break line should start with `\`

**Comment by zhuzhzh** [comment]
@iamcco I use vim in one intranet enviroment. so plantuml server is not accesable.
but I can install one internal plantuml server. how can I set the server for plantuml and mermaid?
