### ISSUE TITLE
Request:  Instructions for installation/configuration with Packer

### ISSUE THREAD

**Issue by syntaxman** [iamcco/markdown-preview.nvim#399]
A lot of neovim users are moving to an init.lua configuration and Packer as their plugin manager.  It would be very helpful to have an example of how to install markdown-preview.nvim in that environment.

**Comment by thallium** [comment]
It's actually an example in the readme of packer.nvim

**Comment by matrixersp** [comment]
The example https://github.com/wbthomason/packer.nvim/blob/851c62c5ecd3b5adc91665feda8f977e104162a5/README.md?plain=1#L139

**Comment by Utkarsh-khambra** [comment]
I use this 
`use({ "iamcco/markdown-preview.nvim", run = "cd app && npm install", setup = function() vim.g.mkdp_filetypes = { "markdown" } end, ft = { "markdown" }, })`
with packer and it's been working fine
