### ISSUE TITLE
预览同步问题

### ISSUE THREAD

**Issue by pzxbc** [iamcco/markdown-preview.nvim#4]
首先说一下，这个插件的模式才是`vim`下`markdow`预览的正确工作方式。看了很多其他插件，基本都是调用本地浏览器渲染。但是基本上还在`vim`上折腾的都是服务端的，哪有浏览器调用（即使装了，也没桌面环境啊...）

在Windows的Chrome浏览器打开对应预览地址，预览没有问题，但是编辑位置同步的比较慢，而且Chrome中的预览没有正确定位到文尾，`vim`中光标已经到文尾了，但是Chrome中没拖到最后。

![problem](https://user-images.githubusercontent.com/1167393/51100110-7baca980-180f-11e9-930b-12511c0db59c.gif)

另外希望在输入`:MarkdownPreview`后显示出`url`地址。翻了代码才知道`url`规则是`http://ip:port/page/buffer_number`

**Comment by iamcco** [comment]
同因为 vim 没有 scroll 事件，所以步滚动使用的是 cursorhold 事件进行更新的，也就是说 updatetime 设置的越小，同步滚动越灵活。可以试着把 updatetime 设置为一个比较小的值。

目前的同步滚动是通过对齐 视口的顶部 同步的，所以即使光标在底部，同步的还是视口头部。这个应该可以优化下。

关于显示url，这个可以加个选项。

**Comment by iamcco** [comment]
插件没有自动打开 chrome？

**Comment by pzxbc** [comment]
> 插件没有自动打开 chrome？

我的vim在linux服务器上，没有chrome

updatetime值在哪设置呢，配置选项中没看到这个

**Comment by iamcco** [comment]
增加了 `g:mkdp_echo_preview_url` 选项，设置为 1，在打开预览的时候会回显 url

**Comment by pzxbc** [comment]
> 增加了 `g:mkdp_echo_preview_url` 选项，设置为 1，在打开预览的时候会回显 url

更新后测试没有问题，感谢~

**Comment by hgneer** [comment]
由于现在预览同步还有问题未解决，我想问下该怎么关闭同步滚动？
如果不关闭同步滚动，这个同步滚动反而会影响自己用鼠标滚动或者浏览器用vimium插件进行滚动。

**Comment by iamcco** [comment]
增加了 `g:mkdp_preview_options.disable_sync_scroll` 选项，设置为 1 关闭同步滚动

**Comment by iamcco** [comment]
fix. 更多同步滚动配置看 README 的 `sync_scroll_type` 配置项

**Comment by hgneer** [comment]
> fix. 更多同步滚动配置看 README 的 `sync_scroll_type` 配置项

:+1:

**Comment by miaomiao-ocean** [comment]
我在docker环境下打开(类似服务器模式)， 访问url地址，报  Empty reply from server。 有人碰到这个问题吗？
