### ISSUE TITLE
Cannot display a picture in relative path.

### ISSUE THREAD

**Issue by xy-xin** [iamcco/markdown-preview.nvim#40]
A case like \!\[Pic\](./a/relative/path.png)

**Comment by iamcco** [comment]
It works for me. What's your platform and (neo)vim version ?

**Comment by xy-xin** [comment]
@iamcco Thanks for the reply.

I got the answer. It's not the relative path problem, but the syntax i use. I use the below syntax to include a picture

```js
<p align="center">
<img src="./xxx.png" width = 60% height = 60% div align=center/>
</p>
```

because i want to resize the picture in the final web display.

**Comment by iamcco** [comment]
fix, update and have a try.

**Comment by xy-xin** [comment]
Very quick fix! Thanks!
