### ISSUE TITLE
No license means no rights for anyone to do anything with this code

### ISSUE THREAD

**Issue by ghost** [iamcco/markdown-preview.nvim#406]
**Describe the bug**
This (neo)vim plugin has no license file and is therefore copyrighted  without giving anyone the rights to use, study, modify and (re)distribute according to EU and US law. You should add a LICENSE file to make it Free and Open Source Software if that is your intention with having the source up on Github. On the other hand, if you do not want anyone to use your software in any way, having no license is fine.

**To Reproduce**
Look for a LICENSE file or information about license in the Readme.md

**Expected behavior**
A software license should be specified in a LICENSE file and also mentioned in the Readme. Otherwise, the users do not have the freedom to use, study, modify and (re)distribute the software. It is not open source and not free software if you do not add a FOSS License even if people can read the source code. Source available is not the same as open source. All code is copyrighted by their creators by default under US and EU law and no right to do anything with that code is given to anyone without a license. Even if you live in another jurisdiction, EU and US law on intellectual property is important to follow to allow people in those jurisdictions the right to contribute to and use your software.

Not having a license means contributions to your project will also be copyrighted by their authors and no rights to those contributions are handed back to the project. Anyone involved can at any time sue this project for distributing the code or using it in the first place since it is not clear that people have licensed anyone to do anything with the code. Adding a license secures both the project against abuse and the project's users against the same. If you like free software and want the software never to be made proprietary by anyone in the future, then GPL or AGPL might be apropriate. If you like anyone, including big tech companies that contribute nothing back, to be able to make this software proprietary (not open source and not free software) at any time, then BSD or MIT might be appropriate licenses.

The license of your dependencies might also decide if you are free to choose a license yourself or if you need to use the same license as those dependencies. Copylefted code (GPL, AGPL...) cannot be used as part of a larger project without the rest of the project also being copylefted with the same license. Permissively licensed code (MIT, BSD...) give other projects the right to use any license, including to make the code proprietary (not free software and not open source). You have to look into the licenses of your dependencies to figure out if your projects are under any obligations as to what license to use based on those.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GNU/Linux

Log:

```
```

**Comment by iamcco** [comment]
closes by https://github.com/iamcco/markdown-preview.nvim/pull/435
