### ISSUE TITLE
Do not installed/updated when vim-plug with more options by using Win10 Gvim8.1!

### ISSUE THREAD

**Issue by StarryLeo** [iamcco/markdown-preview.nvim#41]
Hi, friends！

This plugin is work well after successfully installed.
`" If you don't have nodejs and yarn
" use pre build`
  `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}`

But, When I use more options which vim-plug provide, like `'for'`, `'on'`, it can not installed/update even I use `!` 
`                Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown', 'on': 'MarkdownPreview' }
`
`:PlugUpdate! markdown-preview.nvim`

![snipaste20190330_205928](https://user-images.githubusercontent.com/25200758/55277199-60463a80-5338-11e9-96de-649167c6d20f.png)
![snipaste20190330_205928](https://user-images.githubusercontent.com/25200758/55277208-6f2ced00-5338-11e9-8829-0a443e2d922b.gif)

Then, I test more, I find use the vim command `:call mkdp#util#install()`  can work well !
the `install.cmd` can successfully run, and the plugin will lazy loading

![snipaste20190330_212135](https://user-images.githubusercontent.com/25200758/55277334-e44cf200-5339-11e9-9635-b43195f22997.png)
![snipaste20190330_212135](https://user-images.githubusercontent.com/25200758/55277339-fc247600-5339-11e9-98c7-590109994d80.gif)

`Plug 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()', 'for': 'markdown', 'on': 'MarkdownPreview' }`

I don not  know how is work, but I think this is helpful to yours

**Comment by iamcco** [comment]
You can't use the `mkdp#util#install` hook to update the plugin when you use lazy load. Because the plugin is not in the runtime path when you update, so the `mkdp#util#install` is not exists. You have to write your own function to call the install script if you use lazy load.

**Comment by StarryLeo** [comment]
Eh, I I guess maybe you didn't see it clearly. I mean 
`Plug 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()', 'for': 'markdown', 'on': 'MarkdownPreview' }`
can work well with lazy load and normally execute post-update hooks after the plugin updated, why use
`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown', 'on': 'MarkdownPreview' }` 
can not execute post-update hooks after the plugin updated.
And when I check the function about install. I find [mkdp#util#pre_build_version()](https://github.com/iamcco/markdown-preview.nvim/blob/master/autoload/mkdp/util.vim#L162) do not work with win10, it means app/bin will update after plugin updated even it do not need, You may want to add `.exe` for win10
![20190331](https://user-images.githubusercontent.com/25200758/55290255-8c7abd80-5403-11e9-9ffe-f53b057b56ba.gif)
I done this to [pull requests#42](https://github.com/iamcco/markdown-preview.nvim/pull/42)

**Comment by iamcco** [comment]
OK, I got it. Thank you.
