### ISSUE TITLE
Markdown-preview shows not loaded

### ISSUE THREAD

**Issue by dlj2019** [iamcco/markdown-preview.nvim#411]
Markdown-preview works only when it first installed. Once i close Nvim and open again the plugin does not load. 

I am following chris@machine 'Neovim-Plugin IDE from Scratch" | Markdown-preview.nvim video, but i am not able to preview. Do you guys know how to fix this ? 

https://www.youtube.com/watch?v=gd_wapDL0V0&t=1312s | timeline=>  20:40

![pic-selected-211228-1057-53](https://user-images.githubusercontent.com/30886694/147993073-bfff7a69-7391-4c47-b00d-9591bfb485c8.png)

I have npm and yarn. I also tried to installed manually (app/)

![pic-selected-211229-1828-36](https://user-images.githubusercontent.com/30886694/148230428-39679fa0-38de-4299-b705-98b40531b768.png)

Unfortunately, the "Markdown plugin" stops working once i close nvim. I've noticed that when i reinstall it and use the command right the way it works, but once i close "nvim" and reopen again the error persists. 

![pic-selected-211229-1840-08](https://user-images.githubusercontent.com/30886694/148230678-d42ebc45-10e4-4127-965e-120f3fad2d0e.png)

=> Any suggestions ?

**Comment by Utkarsh-khambra** [comment]
How do you load the plugin via packer?

**Comment by dlj2019** [comment]
> 

I had do add following line => _"ft ='markdow',"_ 

It seems not all plugins go well with packer. I have added "ft ='markdow'," and it fixed the issue with - Markdow-preview-nvim 

`use {
  'iamcco/markdown-preview.nvim',
  ft = 'markdown',
  run = 'cd app && yarn install'
}`

**Comment by youkoucoding** [comment]
> > 
> 
> I had do add following line => _"ft ='markdow',"_
> 
> It seems not all plugins go well with packer. I have added "ft ='markdow'," and it fixed the issue with - Markdow-preview-nvim
> 
> `use { 'iamcco/markdown-preview.nvim', ft = 'markdown', run = 'cd app && yarn install' }`

Thank you very much!  This worked for me.

**Comment by iamcco** [comment]
set `let g:mkdp_command_for_global = 1` if you want to enable with all filetypes.
