### ISSUE TITLE
MarkdownPreview is not an editor command.不是编辑器命令，但是自动预览可以用。

### ISSUE THREAD

**Issue by AGou-ops** [iamcco/markdown-preview.nvim#414]
info:

- os: macos 12.1
- nvim: 0.6

自动预览可以用：

![2022-01-14 16-43-11 2022-01-14 16_43_53](https://user-images.githubusercontent.com/57939102/149483893-afa9ed25-cc7b-4625-a9c0-8fea4065b306.gif)

但是手动命令不可以：

![image](https://user-images.githubusercontent.com/57939102/149480116-4b3c72e9-308f-4aae-802e-8c4679a40763.png)

用的默认配置，只改了`let g:mkdp_auto_start = 1`选项，参考过 #255 

尝试过：

- 删除重装插件
- 手动`yarn`安装

![image](https://user-images.githubusercontent.com/57939102/149485536-71080d30-7a9f-4012-bf55-cda933d289eb.png)

**Comment by iamcco** [comment]
确保你文件的类型是 markdown

**Comment by AGou-ops** [comment]
确定是的，`.md`和`.markdown`都试过，就是没有`:MarkdownPreview `这个命令，真奇怪.😅

**Comment by iamcco** [comment]
不是的，你这个只是后缀名字，你打开 markdown 文件运行 `echo &filetype` 看看是什么类型，或者手动设置 `set filetype=markdown`

**Comment by AGou-ops** [comment]
喔喔，我明白了，我这里`:echo $filetype`输出的是`markdown.mkd`，然后设置下`g:mkdp_filetypes`就可以了.

谢谢大佬~
