### ISSUE TITLE
Clarification of the install process

### ISSUE THREAD

**Issue by Francicoria** [iamcco/markdown-preview.nvim#419]
Hi, I was just wondering, why do i need to put
`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}`
into init.vim and not just
`Plug 'iamcco/markdown-preview.nvim'` ?
Thanks.

**Comment by Utkarsh-khambra** [comment]
This plugin requires some extra binaries other than this plugin, the line `-> mkdp#util#install()`, calls a vim script function and installs those dependencies for you.

**Comment by Utkarsh-khambra** [comment]
Also you should be able do install it with `Plug 'iamcco/markdown-preview.nvim'` as well but the you have to manually  run `cd app && yarn install` in the markdown-preview directory. Every time you update or reinstall the plugin.

**Comment by Francicoria** [comment]
Oh got it now, thanks!
