### ISSUE TITLE
I can't run markdown-preview with lua (Packer Packages Manager)

### ISSUE THREAD

**Issue by di4m0nds** [iamcco/markdown-preview.nvim#420]
I already tried with: 
```
use {'iamcco/markdown-preview.nvim', run = 'cd app && yarn install', cmd = 'MarkdownPreview'}
```
and
```
use {
    'iamcco/markdown-preview.nvim', run = function() vim.fn['mkdp#util#install']() end, ft = {'markdown'}
  }
```
and just
```
use 'iam/markdown-preview.nvim'
```
but nothings happens.. any know why?

I got NPM and Yarn Globally installed...

**Comment by Utkarsh-khambra** [comment]
Can you try this

https://github.com/iamcco/markdown-preview.nvim/issues/354#issuecomment-929855445

**Comment by di4m0nds** [comment]
> Can you try this
> 
> https://github.com/iamcco/markdown-preview.nvim/issues/354#issuecomment-929855445

Thanks you bro! Works well now! 🦾
