### ISSUE TITLE
Only images from github are displaying

### ISSUE THREAD

**Issue by PenaflorPhi** [iamcco/markdown-preview.nvim#421]
I'm trying to display an image in the preview but I'm not sure if I'm doing something wrong. If I upload the image to github it displays correctly. What I'm doing on my file is

```
![1](https://imgur.com/Image.png)
![2](/home/user/path/to/file/Image.png)
![3](./path/to/file/Image.png)
![4](https://camo.githubusercontent.com/verylongstringofnumbers) 
```

1 - 3 don't work, the browser (Firefox, Firefox-Nightly and Chromium) either display nothing (not even the string of text) or they display an empty rectangle. The fourth one works but it's the link that GitHub gives after putting the first one in the readme, is there way I can display images without putting them in GitHub?

**Comment by eeeXun** [comment]
Markdown code.
```markdown
# hello

![hello](https://i.imgur.com/W7jfX9h.png)
```
And I got this error. How to fix that

![image](https://user-images.githubusercontent.com/58657914/168282363-3d1d69d6-cddd-40de-9091-b8ca8f3af569.png)

**Comment by iamcco** [comment]
The image (https://i.imgur.com/W7jfX9h.png) you insert in the markdown file is forbidden to display by imgur

**Comment by iamcco** [comment]
Change 127.0.0.1 to `localhost` to see if it can display. I don't know if it's because imgur block IP website

**Comment by eeeXun** [comment]
Yes, change `localhost` would work
