### ISSUE TITLE
An unexpected error has occurred in Vim 8.2

### ISSUE THREAD

**Issue by lpvm** [iamcco/markdown-preview.nvim#422]
I'm using Vim version 8.2.3745 on a FreeBSD amd64 system.
I've installed this plugin through `Plug`, as 

```
call plug#begin('~/.vim/plugged')
        Plug 'plasticboy/vim-markdown'
        Plug 'iamcco/markdown-preview.nvim', {'do': 'cd app & yarn install'}
call plug#end()
```

When trying `:MarkdownPreview`, a pink message shows up at the bottom of vim saying:

`node --trace-warnings .....where the warning was created`

The default browser, Otter, for the address `http://127.0.0.1:8691/page/1`, says that
`An unexpected error has occurred.`

**Comment by resoliwan** [comment]
It is only worked at node 
       v10.24.1
->    v12.22.10
       v14.17.5
       v16.13.2

**Comment by TruncatedDinosour** [comment]
Happens on my hardened firefox, try a less hardened browser profile

**Comment by iamcco** [comment]
Try latest version.
