### ISSUE TITLE
preview时候，总有一个图标显示

### ISSUE THREAD

**Issue by customtiy13** [iamcco/markdown-preview.nvim#423]
![2022-02-09_01-02-1644340750](https://user-images.githubusercontent.com/97291621/153042258-0acb9a71-a1f3-48f9-8af3-000e184d1aff.jpg)
打开浏览器时候，总会有上面这个图标，因为我想直接在浏览器里面打印pdf, 但是 总是多出来这个东西。firefox,chrome,qutebrowser, 全都有这个东西。能否消除这个图标

**Comment by iamcco** [comment]
添加自定义 css 文件

" use a custom markdown style must be absolute path
" like '/Users/username/markdown.css' or expand('~/markdown.css')
let g:mkdp_markdown_css = ''

文件内容
```
#page-header svg {
  display: none;
}
```
