### ISSUE TITLE
:MarkdownPreview command does not respond, installed with packer.nvim

### ISSUE THREAD

**Issue by ethanh6** [iamcco/markdown-preview.nvim#424]
**Describe the bug**
Installed with packer.nvim
```
use {'iamcco/markdown-preview.nvim', run = 'cd app && yarn install'}
```
But the `:MarkdownPreview` command is not responding

**To Reproduce**
1. If installed, remove MarkdownPreview completely
2. Install with the above options (no lazyloading)
3. When installed, run `:MarkdownPreview`, it does not respond

**Expected behavior**
A markdown preview page will popup in the browser.

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL)
 - Editor: Neovim v0.6.1

**Comment by ethanh6** [comment]
Fix it my manually install with `install.sh` 

```
$ cd ~/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/app/
$ ./install.sh
```

**Comment by BilyZ98** [comment]
met the same problem, solve it with manually execute ```./install.sh ```
thanks

**Comment by Jiiiiiin** [comment]
my reinstallation will be solved later

**Comment by keevee09** [comment]
An update to this issue.
I updating LunarVim today and on re-installing markdown-preview I see that it is installed to
` ~/.local/share/nvim/site/pack/packer/opt/markdown-preview.nvim`
so is in _opt_ rather than _start_:
`~/.local/share/nvim/site/pack/packer/start`
I entered `.../opt/markdown-preview/app` and ran `./install.sh` but this did not work.
Instead this worked:
`$ cd ~/.local/share/lunarvim/site/pack/packer/start/markdown-preview.nvim/app`
`$ ./install.sh`

**Comment by Ceobe33** [comment]
> Fix it by manually installing with `install.sh` 
> 
> ```
> $ cd ~/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/app/
> $ ./install.sh
> ```

⚠️  when use cmd
if u didn't use packer plug manager, **modified the path** and use
or use filter in vim
`:filter markdown-preview scriptnames` and cut down useful part to use

for example i use lazyvim:
`$ cd ~/.local/share/nvim/**lazy**/markdown-preview.nvim/app/`
`$ ./install.sh`

**Comment by SpamixOfficial** [comment]
Using `install.sh` also solved it for me. How come this doesnt get triggered by default on installation? Should be noted, I use vim-plug

**Comment by Mitcnath** [comment]
> An update to this issue. I updated LunarVim today and on re-installing markdown-preview I see that it is installed to ` ~/.local/share/nvim/site/pack/packer/opt/markdown-preview.nvim` so is in _opt_ rather than _start_: `~/.local/share/nvim/site/pack/packer/start` I entered `.../opt/markdown-preview/app` and ran `./install.sh` but this did not work. Instead this worked: `$ cd ~/.local/share/lunarvim/site/pack/packer/start/markdown-preview.nvim/app` `$ ./install.sh`

This solved my problem instantly, thank you! =)
