### ISSUE TITLE
No matching autocommands

### ISSUE THREAD

**Issue by frank777777777** [iamcco/markdown-preview.nvim#43]
vim version: 8.1
Plugin management tool: Vundle

`~/.vimrc` config:
For installation, so far I have tried:
`Plugin 'iamcco/markdown-preview.nvim'`
`Plugin 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()', 'for': 'markdown', 'on': 'MarkdownPreview' }`
`Plugin 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }`

> Start the preview
> `:MarkdownPreview`

I got
> No matching autocommands

Is it because it does not support Vundle?

**Comment by JuanVqz** [comment]
hi @frank777777777 

I'm using pathogen and only run `:call mkdp#util#install()` in to vim, this command download support for your SO, later restard and open `vim README.md` and finally `:MarkdownPreview` and works.

You can follow same steps, regards!

**Comment by iamcco** [comment]
Vundle doesn't support plugin's install hook, so you have to call `mkdp#util#install()` after install the plugin.

**Comment by frank777777777** [comment]
@JuanVqz  @iamcco Thanks for helping out, its working now.

If I am to uninstall it in the future, do I need to call any other command? Or I can just simply uninstall it like normal `:PlugClean`?

**Comment by JuanVqz** [comment]
@frank777777777 I'm sorry, don't help you because I'm using pathogen.

**Comment by iamcco** [comment]
> If I am to uninstall it in the future, do I need to call any other command? Or I can just simply uninstall it like normal `:PlugClean`?

Yes, `PlugClean` works because the download pre build is in the plugin directory.

**Comment by 01kuc** [comment]
I apologize for commentin on a close issue, but I have a little question.

> hi @frank777777777
> 
> I'm using pathogen and only run `:call mkdp#util#install()` in to vim, this command download support for your SO, later restard and open `vim README.md` and finally `:MarkdownPreview` and works.
> 
> You can follow same steps, regards!

Dear @JuanVqz , your instructions worked for me with Pathogen. Thank you very much.
But I am new in VIM, could you please explain the commands `call mkdp#util#install()` ? 
I oberserved that it installed some things about Markdown Preview nvim package. But I did not need that command for any other plugin that I installed.

Thanks again for your tip.
Best Regards
Hakki

**Comment by JuanVqz** [comment]
@01kuc it’s a call for a function into the plugin.

**Comment by iamcco** [comment]
> I oberserved that it installed some things about Markdown Preview nvim package. But I did not need that command for any other plugin that I installed.

It download the prebuild bundle of the plugin therefor you don't need to install nodejs and npm.

**Comment by caixxiong** [comment]
I have met the same question with same environment(vim 8.1 vundle). I solved this now by use `yarn`.
Firstly, type `:mess` in vim, if you get some errors about node.js , then you probably not install the plugin correctly. You can install yarn for your os and `cd ~/.vim/bundle/markdown-preview.nvim/app && yarn`.

**Comment by caixxiong** [comment]
Today, I updated my ubuntu os to 20.04. When I run `MarkdownPreview` in vim,  this     error `no matching autocommands` occurs again. I run `:call mkdp#util#install()`     and failed to download because the network is not stable. Therefore, I download `markdown-preview-linux.tar.gz ` from [here][1], and move this tar.gz file to `~/.vim/bundle/markdown-preview/app/bin/`, and unzip this file(you can also refer to app/install.sh). Successfully.

[1]: https://github.com/iamcco/markdown-preview.nvim/releases/download/v0.0.9/markdown-preview-linux.tar.gz

**Comment by ArmandXiao** [comment]
## **IF U INSTALL LIKE THIS**
`Plugin 'iamcco/markdown-preview.nvim'`
- This one is in vimrc

`:VundleInstall`
- vim command

### The easiest solution
1. `cd ~/.vim/bundle/markdown-preview.nvim/app`
2. `bash ./install.sh`

Then follow other configs!
I had the same problem and perfectly solved 👍 
hope this can help those who use Vundle

**Comment by maniac-en** [comment]
> Vundle doesn't support plugin's install hook, so you have to call `mkdp#util#install()` after install the plugin.

This is also needed if someone is using vim8's default plugin manager!
