### ISSUE TITLE
Localhost just show "404"

### ISSUE THREAD

**Issue by dylanfierro** [iamcco/markdown-preview.nvim#437]
**ss**
![image](https://user-images.githubusercontent.com/56775416/157350833-67ffdf9a-6337-414c-8cef-595e89d43da2.png)

**OS:**
-Parrot OS 5.0 (LTS) x86_64 Debian
-Node v16.14.0
-Yarn 1.22.17
When i run `:MarkdownPreview` not show any error

**Comment by revue-starlight** [comment]
met the same problem just now, sounds like the actual URL may be `http://localhost:8080/page/<number>`

**Comment by Hexancer** [comment]
Can't work, wasted the whole afternoon, same issue.
