### ISSUE TITLE
Local images not rendering [chrome]

### ISSUE THREAD

**Issue by cabaalexander** [iamcco/markdown-preview.nvim#44]
Here's a capture to try to provide more info. 😢 

![image](https://user-images.githubusercontent.com/12496574/55454693-cb00ab80-55ae-11e9-9e3f-cbcc336444d4.png)

**Comment by iamcco** [comment]
`_local_Image_` is correct. But the image path in your markdown is `/imgs/logo.png`.  Is that exists (which is absolute path) ?

**Comment by cabaalexander** [comment]
Yes, it exists.

If it is helpful here is the repo I'm using as the example 👇 

https://github.com/cabaalexander/dotfiles

----

And here is how my file structure in my system looks like.

![image](https://user-images.githubusercontent.com/12496574/55483080-de823580-55f3-11e9-9d0d-dcf3acaa8e17.png)

**Comment by iamcco** [comment]
> Yes, it exists.
> 
> If it is helpful here is the repo I'm using as the example 👇
> 
> https://github.com/cabaalexander/dotfiles
> 
> And here is how my file structure in my system looks like.

You can't use `/imgs/logo.png`. It's absolute path like `/User/home/xxxx`. You should use `./imgs/logo.png` instead.

**Comment by cabaalexander** [comment]
Niceeeee, It was it . Thank you.

Byt the way, this is a piece of a plugin 💯
