### ISSUE TITLE
Issue: cant

### ISSUE THREAD

**Issue by epiphany546** [iamcco/markdown-preview.nvim#444]

**Comment by epiphany546** [comment]
I use Mac and vim 8.2, and I also have yarn installed in my compute, but I can't use markdownPreview. The error listed below.
`E492: Not an editor command: MarkdownPreview`
Does anyone know how to deal with that?

**Comment by bhsiung** [comment]
+1

**Comment by iamcco** [comment]
Set your markdown filetype to `markdown`
