### ISSUE TITLE
MarkdownPreview stops working after neovim restart

### ISSUE THREAD

**Issue by bcl1713** [iamcco/markdown-preview.nvim#445]
**Describe the bug**
Using packer to install markdown-preview.nvim results in the command `MarkdownPreview` working during that session only.  When exiting neovim and reloading, the command is no longer recognized.  

**To Reproduce**
1. Add the following lines to your packer config:
```
--Markdown Preview
use {
    'iamcco/markdown-preview.nvim',
    run = 'cd app && yarn install',
    cmd = 'MarkdownPreview'}
```
2. Run `PackerInstall`
3. Open a `.md` file
4. run `MarkdownPreview`
5. browser opens and markdown preview works.
6. close neovim
7. reopen neovim with markdown file
8. run `MarkdownPreview`
9. tab completion of the command doesn't work, and the result is `E492: Not an editor command: Markdown Preview`

**Expected behavior**
`MarkdownPreview` and related commands should persist through restarts of neovim

**Desktop (please complete the following information):**
 - OS: Arch

**Comment by Utkarsh-khambra** [comment]
`use({ "iamcco/markdown-preview.nvim", run = "cd app && yarn install", setup = function() vim.g.mkdp_filetypes = { "markdown" } end, ft = { "markdown" }, })`

Can you try this snippet for packer

**Comment by ozgun** [comment]
Hi @Utkarsh-khambra , I was having the same issue as @bcl1713 , your solution fixed it on my side. Thank you :)

**Comment by bcl1713** [comment]
This also fixed for me.  Thank you @Utkarsh-khambra! May I ask how you came up with this solution?  Were we doing something wrong before?

**Comment by Utkarsh-khambra** [comment]
I encountered this problem when I switched from single init.vim to seperate lua files for in neovim.
