### ISSUE TITLE
Plantuml: word breakdown structure

### ISSUE THREAD

**Issue by Erik-Hoffmann** [iamcco/markdown-preview.nvim#447]
In Plantuml there is a diagram type named "word breakdown structure".

According to reference, you use it like this:
```
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
``` 

should produce something like this:

![grafik](https://user-images.githubusercontent.com/90474419/163714355-51575079-a404-4d34-882b-3238e163ccaf.png)

but if I try, it is not escaped at all. Other diagram types using @startuml annotation work as intended.

So is there support for wbs and I'm doing it wrong? If not, will there be support for wbs?

**Comment by EvaristeFan** [comment]
try add( ```plantuml) at begin 

and (```) on the end

**Comment by Erik-Hoffmann** [comment]
Works like a charm, thank you so much :heart_eyes: 

In case somebody trying as well:

<pre>
```
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
```
</pre>
