### ISSUE TITLE
E492: Not an editor command: MarkdownPreview

### ISSUE THREAD

**Issue by zim0369** [iamcco/markdown-preview.nvim#448]
1. Open a single markdown file.
2. The plugin doesn't work.
3. Open another markdown file.
4. Plugin works.
5. Close the second markdown file(keep only one open)
6. The plugin works.

**Comment by Utkarsh-khambra** [comment]
Can you share your config file?

**Comment by rkmiec** [comment]
What is the extension of the first file? Maybe it is not properly recognized.
Once you open first file, run `set filetype=markdown` and check if preview command is available.

**Comment by iamcco** [comment]
Please set your markdown filetype to `markdown` as above.
