### ISSUE TITLE
没有匹配的自动命令

### ISSUE THREAD

**Issue by GuangzheJiang** [iamcco/markdown-preview.nvim#45]
安装 markdown-preview.nvim 和 mathjax-support-for-mkdp 成功后，打开一个已经写好的 markdown 文件输入 `:MarkdownPreview`， vim 提示 `没有匹配的自动命令`。请问这有可能是什么情况造成的？

**Comment by iamcco** [comment]
你怎么安装的，因该是没装成功。还有你用的什么版本的vim

**Comment by dianbanjiu** [comment]
使用 vim-plug 安装的  
```
Plug 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()', 'for': 'markdown', 'on': 'MarkdownPreview' }
Plug 'iamcco/mathjax-support-for-mkdp'
```
在 vim 里面使用 `PlugInstall` 提示安装完成。  

使用的是 Arch Linux 下的 Vim，版本号是 8.1

**Comment by iamcco** [comment]
`:mess` 看下报什么错，应该是没装成功，可以手动执行下 `:call mkdp#util#install()`

另外，不需要 `Plug 'iamcco/mathjax-support-for-mkdp'`

**Comment by dianbanjiu** [comment]
`:mess` 没有报错，提示 `简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>`  
`:call mkdp#util#install` 提示 
```
:call mkdp#util#install()
命令已结束
处理 function mkdp#util#install[1]..mkdp#util#pre_build_version 时发生错误:
第    8 行:
E684: List 索引超出范围: 0
请按 ENTER 或其它命令继续
```

**Comment by iamcco** [comment]
执行 `MarkdownPreview` 命令后 `:mess` 没报错？

**Comment by dianbanjiu** [comment]
这个还真的没有，就是只提示 `没有匹配的自动命令‘

**Comment by iamcco** [comment]
你用的是不是 32 位系统？目前 release 的二进制只支持64位系统。如果想用的话得从源码装 `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install ' }

**Comment by dianbanjiu** [comment]
是 64 位的，使用 `uname -a` 显示 `x86_64 GNU/Linux`

**Comment by iamcco** [comment]
删除插件重新这样装一下，`Plug 'iamcco/markdown-preview.nvim', { 'do': mkdp#util#install_sync() } }`

如果还是不行，可能就是预编译那个二进制包在你的系统运行不了，我得有时间后用我 linux 试下

**Comment by dianbanjiu** [comment]
试了一下还是不可以。
其实我之前是装成功过一次的，不过后来再重装系统之后就不能用了。

**Comment by keer2345** [comment]
我的也是报这个错误，执行`:MarkdownPreview` 提示**没有匹配的自动命令** ，然后执行`:mess`显示如下：

```
简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>
"a.md" 1L, 8C
[vim-node-rpc] rpc error: internal/modules/cjs/loader.js:615
[vim-node-rpc] rpc error:     throw err;
[vim-node-rpc] rpc error:     ^
[vim-node-rpc] rpc error: 
[vim-node-rpc] rpc error: Error: Cannot find module 'tslib'
[vim-node-rpc] rpc error:     at Function.Module._resolveFilename (internal/modu
les/cjs/loader.js:613:15)
[vim-node-rpc] rpc error:     at Function.Module._load (internal/modules/cjs/loa
der.js:539:25)
[vim-node-rpc] rpc error:     at Module.require (internal/modules/cjs/loader.js:
667:17)
[vim-node-rpc] rpc error:     at require (internal/modules/cjs/helpers.js:20:18)

[vim-node-rpc] rpc error:     at Object.<anonymous> (/home/qinjh/.vim/bundle/mar
kdown-preview.nvim/app/lib/app/index.js:3:17)
[vim-node-rpc] rpc error:     at Module._compile (internal/modules/cjs/loader.js
:738:30)
[vim-node-rpc] rpc error:     at Object.Module._extensions..js (internal/modules
/cjs/loader.js:749:10)
[vim-node-rpc] rpc error:     at Module.load (internal/modules/cjs/loader.js:630
:32)
```

**Comment by iamcco** [comment]
@keer2345 你这个是没安装完成，到插件的 app 目录执行 `yarn install` 着删了重新装。

有可能是你没有 yarn，那就缓存 npm

**Comment by keer2345** [comment]
@iamcco 太好了，谢谢您。在插件目录下执行 `yarn` 后就可以实时预览了。

**Comment by ZythonNera** [comment]
@iamcco 谢谢您，新手折腾了一天，终于搞定了。

**Comment by x-a-97** [comment]
安装后遇到类似问题, 原来是yarn没装, 手动安装yarn, 然后重装插件就好了
感谢@iamcco 提供这么方便的插件

**Comment by aGVsZWk** [comment]
谢谢，我也一样的问题！

**Comment by LuoshuiTianyi** [comment]
@iamcco 您好，我遇到了同样的问题但是 `mess` 的报错如下：

[vim-node-rpc] rpc error: Pkg: Error reading from file.
没有匹配的自动命令

请问这个问题来自于哪里？

**Comment by iamcco** [comment]
@LuoshuiTianyi 没遇到过，你重装下或者看下是不是权限问题

**Comment by LuoshuiTianyi** [comment]
@iamcco 谢谢您，打扰了，重装一下没想到就好了 = = 。因为以前很少见重装就能解决的事情。

**Comment by roachsinai** [comment]
我是用yarn，好像网络不行。然后使用`call mkdp#util#install_sync()`或者`call mkdp#util#install()`说没有那个函数：

`E117: Unknown function: mkdp#util#install_sync`。

**Comment by roachsinai** [comment]
```
hmank ~/./p/m/app master » yarn config set registry https://registry.npm.taobao.org -g
yarn config v1.19.1
success Set "registry" to "https://registry.npm.taobao.org".
Done in 0.06s.
hmank ~/./p/m/app master » yarn config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g
yarn config v1.19.1
success Set "sass_binary_site" to "http://cdn.npm.taobao.org/dist/node-sass".
Done in 0.07s.
hmank ~/./p/m/app master » yarn install                                                                
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
```

**Comment by iamcco** [comment]
@roachsinai `E117: Unknown function: mkdp#util#install_sync` 这个提示没有函数的确保你正确安装了插件，并且没有设置什么懒加载之类的，如果设置懒加载的确保插件已经载入之后再运行。

关于 yarn install 网络不行的，我帮不了。。。

**Comment by roachsinai** [comment]
> @roachsinai `E117: Unknown function: mkdp#util#install_sync` 这个提示没有函数的确保你正确安装了插件，并且没有设置什么懒加载之类的，如果设置懒加载的确保插件已经载入之后再运行。
> 
> 关于 yarn install 网络不行的，我帮不了。。。

嗯嗯，感谢回复。不过在使用vimplug更新插件的时候会报错。在更新之前是不是先用一下markdown-preview插件就可以了。。。

**Comment by iamcco** [comment]
是不是加了懒加载，是的化把 vim-plug 加上

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
```

**Comment by roachsinai** [comment]
这次有函数了，感谢。

**Comment by roachsinai** [comment]
另外，`mkdp#util#install()`和`yarn install`这两种方式都是生成了`markdown-preview-linux`这个文件么？

---

也不是，毕竟后缀是linux。。。

**Comment by iamcco** [comment]
你是什么平台，linux 的编译包就是markdown-preview-linux

**Comment by roachsinai** [comment]
我是linux，看下载的是linux，我想问得是yarn install 的结果是什么？也是二进制还是js文件。

**Comment by iamcco** [comment]
`mkdp#util#install()` 会下载二进制，yarn不会下载，使用其一

**Comment by roachsinai** [comment]
嗯嗯，找了一下起server的代码，https://github.com/iamcco/markdown-preview.nvim/blob/5c813eaf943ed7491ba855ad0cb563c31767debf/autoload/mkdp/rpc.vim#L55

意思是如果有二进制就不会调用node了是么？这两种方式在效率上有区别么？

**Comment by iamcco** [comment]
二进制就是执行文件了，没有安装nodejs的情况也可以使用，效率上没啥区别

**Comment by roachsinai** [comment]
嗯嗯，感谢！

**Comment by NerDante** [comment]
相同问题，在插件app目录下执行 npm install 解决！！！

**Comment by caixxiong** [comment]
> @keer2345 你这个是没安装完成，到插件的 app 目录执行 `yarn install` 或着删了重新装。
> 
> 有可能是你没有 yarn，那就换成 npm

非常感谢, 我就是用vundle安装这个插件时出了问题,然后mess发现一些和node.js相关的错误,最后安装好yarn,然后在~/.vim/bundle/markdown-preview/app目录下执行yarn命令成功了.需要注意安装yarn不能直接用apt install yarn, 否则安装的是cmdtest, 找个教程安装一下就可以了.
还有就是找个插件的显示功能太强了,可以显示多行公式,代码语法高亮也很好看, 甩出vim-instant-markdon-dy一百条街

**Comment by sdttttt** [comment]
> @ keer2345你这个是没安装完成，到插件的app目录执行`yarn install`或着删了重新安装。
> 
> 有可能是你没有yarn，那就换成npm

这对于我很有用！

我是在ThinkVim中使用`markdown-preview`
当我尝试使用 `: MarkdownPreview`时： Neovim总是会向我抱怨一个错误的js脚本
```
 /home/sdttttt/.cache/vim/dein/repos/github.com/iamcco/markdown-preview.nvim/app/server.js
```

**Comment by nations-Xiong** [comment]
![02-17-10_2020-08-09](https://user-images.githubusercontent.com/57881922/89717183-7e20b680-d9e6-11ea-982e-da7baf7e23e1.png)
一直停留在building，试了很多遍了

**Comment by nations-Xiong** [comment]
![02-31-33_2020-08-09](https://user-images.githubusercontent.com/57881922/89717359-76621180-d9e8-11ea-95ea-00786dbc00bb.png)
这是怎么回事啊？？？

**Comment by iamcco** [comment]
> ![02-31-33_2020-08-09](https://user-images.githubusercontent.com/57881922/89717359-76621180-d9e8-11ea-95ea-00786dbc00bb.png)
> 这是怎么回事啊？？？

没遇到过？什么nodejs版本

**Comment by Palvehelmed** [comment]
请问如何在插件目录下执行yarn install？已经安装了yarn了

**Comment by iamcco** [comment]
@Palvehelmed 打开命令行，找到插件位置，然后执行 yarn install

**Comment by Palvehelmed** [comment]
> @Palvehelmed 打开命令行，找到插件位置，然后执行 yarn install

您好，感谢回复，我已经尝试执行yarn insall了，但是还是没有这个命令，以下是我的安装过程，您看下哪个地方出错了

Vim版本，MacVim, Version 8. 2, 1719

通过Vim-Plug下载
+ markdown-preview.nvim: remote: Compressing objects: 100% (466/466), done.        

cd ~/.vim，执行yarn install
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
success Already up-to-date.

node版本，Welcome to Node.js v14.15.1.

MacVim里打开.md文件输入命令，显示 Not an editor command: MarkdownPreview，Tab也没有自动补全

**Comment by iamcco** [comment]
说的是这个插件的文件夹，不是.vim

**Comment by Palvehelmed** [comment]
您好, 已经成功安装了, 之前正常使用, 最近突然用一两次就会弹出not an editor command, 卸载重装也不行, 偶尔第一次能用, 之后就会弹, 也在安装目录执行`yarn install`了, 也试着重装了yarn 和node, 目前都没有成功, 请问有什么解决方案吗

**Comment by Palvehelmed** [comment]
请问一下

我vimrc里配置`let g:mkdp_auto_start = 1`就可以正常使用,
但是
`let g:mkdp_auto_start = 0`就会显示not an editor command, 试着重装插件, 重启和重装yarn了, 貌似都不行

请问是哪里出问题了

**Comment by iamcco** [comment]
@Palvehelmed 不知道

**Comment by MatchLittle** [comment]
> @keer2345 你这个是没安装完成，到插件的 app 目录执行 `yarn install` 或着删了重新装。
> 
> 有可能是你没有 yarn，那就换成 npm
>我也是这样的问题，已被解决，感谢

**Comment by ranyh524** [comment]
> `:mess` 看下报什么错，应该是没装成功，可以手动执行下 `:call mkdp#util#install()`
> 
> 另外，不需要 `Plug 'iamcco/mathjax-support-for-mkdp'`

解决了，谢谢谢谢
