### ISSUE TITLE
Not working on macOS now `:MarkdownPreview` shows nothing.

### ISSUE THREAD

**Issue by nyngwang** [iamcco/markdown-preview.nvim#450]
As title. I'm using Edge: `Version 101.0.1210.32 (Official build) (x86_64)`, which just got updated, and I'm on `macOS 12.3.1`.

**Comment by fgr1986** [comment]
I believe it might be related to the 'mkdp#util#install' not being found problem

**Comment by nyngwang** [comment]
@fgr1986 Solved?

**Comment by fgr1986** [comment]
I do not think so --please search in issues for the related ones. But you can see if you get an error when calling that function.

**Comment by yaegassy** [comment]
Maybe the latest version resolves this issue, please update markdown-preview.nvim and give it a try.

**Comment by nyngwang** [comment]
Confirmed that the fix works. Thank you! @yaegassy
