### ISSUE TITLE
$NVIM_LISTEN_ADDRESS will be removed in Nvim 0.8

### ISSUE THREAD

**Issue by tomtomjhj** [iamcco/markdown-preview.nvim#452]
Neovim recently removed `$NVIM_LISTEN_ADDRESS` (https://github.com/neovim/neovim/pull/11009), and this breaks markdown-preview.nvim. After that commit, `:MarkdownPreview` doesn't do anything.

**Comment by zhaozg** [comment]
Same with https://github.com/iamcco/markdown-preview.nvim/issues/450

**Comment by richin13** [comment]
Leaving the error message here:

```
2022-05-10 11:41:27 ERROR (pid:1100002) [app/nvim] - uncaughtException Error: connect ENOENT /tmp/nvim
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
```

**Comment by rodhash** [comment]
In my case I don't get any error msg, it just don't work

**Comment by richin13** [comment]
> In my case I don't get any error msg, it just don't work

@rodhash  You should be able to receive an error if you add this to your `init.vim`:

```vim
let $NVIM_MKDP_LOG_FILE = expand('~/mkdp-log.log')
let $NVIM_MKDP_LOG_LEVEL = 'debug'
```

After attempting to unsuccessfully launch markdown-preview the file at `~/mkdp-log.log` should have the error message
