### ISSUE TITLE
Not rendering mermaid.js requirement diagram properly

### ISSUE THREAD

**Issue by maxRN** [iamcco/markdown-preview.nvim#454]
**Describe the bug**
When inserting a [mermaid requirement diagram](https://mermaid-js.github.io/mermaid/#/requirementDiagram?id=syntax) I get a parse error in the HTML.

**To Reproduce**
1. Insert new fenced codeblock with requirement diagram.
````
```mermaid
requirementDiagram

    requirement test_req {
    id: 1
    text: the test text.
    risk: high
    verifymethod: test
    }

    element test_entity {
    type: simulation
    }

    test_entity - satisfies -> test_req
```
````

2. View document in browser.
3. Get
```
Parse error on line 1:
requirementDiagram
^
Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
```
error.

**Expected behavior**
Correctly rendered requirement diagram, like in the [example](https://mermaid-js.github.io/mermaid/#/requirementDiagram?id=syntax).

**Desktop (please complete the following information):**
 - OS: macOS 12.3

**Comment by iamcco** [comment]
fix in latest version
