### ISSUE TITLE
Synchronization doesn't work well with Goyo

### ISSUE THREAD

**Issue by oblitum** [iamcco/markdown-preview.nvim#46]
I use [Goyo](https://github.com/oblitum/goyo.vim) for nice Zen mode, and it creates a new tab to provide that view. This  seems to break `:MarkdownPreview`. Running `:MarkdownPriview` before entering Goyo, instant refresh stops working once entering Goyo mode, leaving it doesn't bring it back too. It's necessary to  `:MarkdownPreviewStop`/`:MarkdownPreview` to make it work.

**Comment by iamcco** [comment]
set `let g:mkdp_auto_close = 0`, seems auto close tab is not work. some browser does not support close tab by javascript.

**Comment by oblitum** [comment]
Hmm OK. To not confuse terminology, I said Goyo uses Vim tabs, it's not browser tab related. But your plugin relates to browser tabs. So just to avoid confusion, I mentioned tabs as in Vim tabs, and it seems the problems also has to do with browser tabs by your explanation.

**Comment by oblitum** [comment]
`let g:mkdp_auto_close = 0` fixes it ;-)

**Comment by iamcco** [comment]
What i say its browser's tab. it will close browser's tab and stop refresh if you leave markdown window if that option is 1.
