### ISSUE TITLE
yarn install failed

### ISSUE THREAD

**Issue by MerliniKing** [iamcco/markdown-preview.nvim#470]
**Describe the bug**
yarn install 过程中报错：
error An unexpected error occurred: "https://registry.yarnpkg.com/fs-extra/-/fs-extra-10.1.0.tgz: unexpected end of file".

**To Reproduce**
git clone https://github.com/iamcco/markdown-preview.nvim.git
cd markdown-preview.nvim
yarn install

**Expected behavior**
install success but failed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: wsl2 ubuntu20.04 on win10

Log:

Arguments:
  /usr/bin/node /usr/share/yarn/bin/yarn.js install

PATH:
  /home/chi/.local/bin:/home/chi/bin:/bin:/home/chi/.local/bin:/home/chi/.nvm/versions/node/v16.14.2/bin:/home/chi/bin:/home/chi/clion/bin:/home/chi/flexelint:/home/chi/neovim/bin:/sbin:/snap/bin:/usr/bin:/usr/games:/usr/lib/wsl/lib:/usr/local/bin:/usr/local/games:/usr/local/sbin:/usr/sbin

Yarn version:
  1.22.19

Node version:
  14.19.3

Platform:
  linux x64

Trace:
  Error: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:187:17)

npm manifest:
  {
    "name": "markdown-preview",
    "version": "0.0.10",
    "description": "markdown preview plugin for (neo)vim",
    "bin": "./app/server.js",
    "repository": "https://github.com/iamcco/markdown-preview.nvim.git",
    "author": "年糕小豆汤 <ooiss@qq.com>",
    "license": "MIT",
    "private": true,
    "scripts": {
      "watch": "tsc -w -p ./",
      "build-app": "cd app && rm -rf ./.next && next build && next export",
      "build-lib": "tsc -p ./",
      "build": "tsc -p ./ && cd app && rm -rf ./.next && next build && next export && yarn && pkg --targets node16-linux-x64,node16-macos-x64,node16-win-x64 --out-path ./bin . && rm -rf ./node_modules ./.next"
    },
    "dependencies": {
      "@chemzqm/neovim": "^5.7.9",
      "chart.js": "^2.7.3",
      "highlight.js": "^10.4.1",
      "log4js": "^6.4.0",
      "markdown-it": "^12.3.2",
      "markdown-it-anchor": "^5.2.4",
      "markdown-it-deflist": "^2.0.3",
      "markdown-it-emoji": "^1.4.0",
      "markdown-it-footnote": "^3.0.1",
      "markdown-it-task-lists": "^2.1.1",
      "markdown-it-toc-done-right": "^4.0.1",
      "md-it-meta": "^0.0.2",
      "msgpack-lite": "^0.1.26",
      "next": "^7.0.2",
      "next-routes": "^1.4.2",
      "plantuml-encoder": "^1.4.0",
      "react": "^16.5.2",
      "react-dom": "^16.5.2",
      "socket.io": "^2.1.1",
      "socket.io-client": "^2.1.1"
    },
    "devDependencies": {
      "@types/node": "16",
      "pkg": "^5.6.0",
      "prettier": "^2.6.2",
      "tslint": "^6.1.3",
      "tslint-config-prettier": "^1.18.0",
      "tslint-plugin-prettier": "^2.3.0",
      "typescript": "^4.6.4",
      "yuuko-tsconfig": "^1.0.0"
    }
  }

yarn manifest:
  No manifest

**Comment by MerliniKing** [comment]
same issue but another file. I am behind a proxy of work space
error An unexpected error occurred: "https://registry.yarnpkg.com/graceful-fs/-/graceful-fs-4.2.10.tgz: unexpected end of file".

**Comment by MerliniKing** [comment]
I have configed the npm registry to http://registry.npm.taobao.org/

**Comment by MerliniKing** [comment]
Also I have config npm strict-ssl = false

**Comment by iamcco** [comment]
Switch another proxy to have a try, seems like it is issue of you proxy.

**Comment by MerliniKing** [comment]
thx for your reply~

**Comment by MerliniKing** [comment]
Is there any other install method that I can avoid use yarn?

**Comment by iamcco** [comment]
Download prebuilt binary bundle and unzip to `markdown-preview.nvim/app/bin` directory. I don't know if the linux prebuilt binary bundle could work in your linux.

https://github.com/iamcco/markdown-preview.nvim/releases/tag/v0.0.10
