### ISSUE TITLE
Can not open markdown preview

### ISSUE THREAD

**Issue by rag-hav** [iamcco/markdown-preview.nvim#472]
**Describe the bug**
On running the command `:MarkdownPreview`, an error is shown and preview window does not open.

    TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of Array

**To Reproduce**
1. Open a markdown file
2. Run `:MarkdownPreview`

**Expected behavior**
A new tab should open in browser with preview of markdown file.

**Screenshots**
![Screenshot from 2022-05-28 13-05-01](https://user-images.githubusercontent.com/60528983/170815709-33801d05-050e-485c-a781-98d6ad270e23.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - CheckHealth- 
 ```  
 - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.7.0
  - INFO: Node version: v17.7.2

  - INFO: Script: /home/raghav/.local/share/lunarvim/site/pack/packer/opt/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node
```

Log:

No log output produced in session

**Comment by johnnymatthews** [comment]
I had a similar issue that I managed to fix. I delete my local copy of this plugin, and then reinstalled everything.

1. Delete `~/.vim/plugged/markdown-preview.nvim`:

    ```shell
    rm ~/.vim/plugged/markdown-preview.nvim
    ```

1. Open Neovim:

    ```shell
    nvim
    ```

1. Install plugins again:

    ```shell
    :PlugInstall
    ```

1. Close Neovim and open a `.md` file.
1. Run `:MarkdownPreview`.

That's what worked for me at least.

**Comment by rag-hav** [comment]
Thanks for the help @johnnymatthews, unfortunately, this did not work for me :(

**Comment by swapfile-dev** [comment]
I support that reinstalling plugin doesn't help.

**Comment by rag-hav** [comment]
A clean run with only markdown preview works as expected so closing this.

**Comment by rag-hav** [comment]
Removing this line is what seems to have fixed the issue 

```
vim.g.mkdp_browser = { "/bin/google-chrome" }
```

I do not know the reason
