### ISSUE TITLE
relative image path

### ISSUE THREAD

**Issue by jotech** [iamcco/markdown-preview.nvim#479]
Hi,
great plugin that is really helpful to render my markdown files, thanks a lot!

My question is if there is a way to set a `root path` for image files?
```
![image.png](resources/test.png) # does not work
![image.png](/full/path/resources/test.png) # works
```
Background: I'm syncing my files between different systems and setting a relative path is thus preferred.
Do you see any any chance to manage the case?

**Comment by tacerus** [comment]
Hi,

I'm interested in this as well, to preview GitHub README.md's using relative paths.
