### ISSUE TITLE
 预览时浏览器显示：An unexpected error has occurred.

### ISSUE THREAD

**Issue by zhougts** [iamcco/markdown-preview.nvim#48]
使用plug安装：
```
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
```
执行MarkdownPreview后浏览器显示`An unexpected error has occurred.`

**Comment by iamcco** [comment]
打开任何一个 markdown 文件都复现还是特定的 markdown ？

再提供下：
- 插件的配置
- 使用的系统
- （neo)vim 版本

**Comment by zhougts** [comment]
打开任何一个markdown文件，第一次执行MarkdownPreview会出现`An unexpected error has occurred`，然后当前md文件在执行一次MarkdownPreview，浏览器再开一个tab然后是正常的
![image](https://user-images.githubusercontent.com/19857153/55851030-916d0900-5b89-11e9-9c34-c42f71a933b8.png)

![image](https://user-images.githubusercontent.com/19857153/55851049-a3e74280-5b89-11e9-954a-ebceb8d9f770.png)
![image](https://user-images.githubusercontent.com/19857153/55851065-af3a6e00-5b89-11e9-956a-b1ca61207b45.png)


插件配置是默认的
win10系统
neovim v0.3.4

**Comment by iamcco** [comment]
没有复现，我可能得找时间win10下看看能不能复现

**Comment by zhougts** [comment]
感谢

**Comment by iamcco** [comment]
抱着个错的时候，打开浏览器控制台看下有什么错误消息

**Comment by zhougts** [comment]
使用chrome没有问题，是默认浏览器的问题。

**Comment by iamcco** [comment]
默认浏览器是 edge ？
