### ISSUE TITLE
.nvim.lua

### ISSUE THREAD

**Issue by alexchaichan** [iamcco/markdown-preview.nvim#487]
Hey guys,

how you manage to fire up MrkdownPreview with nvim.lua?

I also tried to put the .vim commands into a `vim.cmd('let g: ... ')`

But nothing happens when I use the commands :/

**Comment by EvaristeFan** [comment]
Use vim.g.xxx

**Comment by FireSK7** [comment]
Hi,guys. I am a new to neovim, I wander if I need to use "require('markdown-preview').setup()" before I config this plugin, just like what I did like the other plugins?
