### ISSUE TITLE
功能请求：MarkdownPreviewToggle命令

### ISSUE THREAD

**Issue by ppnman** [iamcco/markdown-preview.nvim#49]
现在需要定义两个快捷键，一个用来运行MarkdownPreview，一个用来运行MarkdownPreviewStop。
希望有一个MarkdownPreviewToggle命令，这样只需要一个快捷键就行了。

**Comment by cabaalexander** [comment]
Hello, @ppnman and @iamcco  👋 Rignt now I'm achieving this behavior with function 👇 

![image](https://user-images.githubusercontent.com/12496574/56713907-23841e00-6701-11e9-994c-65c1e2520169.png)


And I map it to `C-p` to (p)review (Example below)

![image](https://user-images.githubusercontent.com/12496574/56713677-6265a400-6700-11e9-8163-91d5729c96ac.png)

@iamcco Maybe I can help with a PR if you like the idea. 🙂

**Comment by iamcco** [comment]
@cabaalexander 

It's OK for me, PR is welcome. 

> And I map it to C-p to (p)review (Example below)

By the way it will be better if it can let user choose what key to map.

**Comment by iamcco** [comment]
Thanks to @cabaalexander ，can use `nmap <C-p> <Plug>MarkdownPreviewToggle` now.
