### ISSUE TITLE
Not support M2 macbook air

### ISSUE THREAD

**Issue by CollieIsCute** [iamcco/markdown-preview.nvim#490]
**Describe the bug**
I use `vim-plug` to install [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim) , and both (with node/yarn or not) methods not work for me.

**To Reproduce**
## First, I use "__no node/yarn method__"
I followed the tutorial in the `README.md`, but got this message.  
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/43088530/184195978-d3fc3d47-3252-4a0a-9609-196207ee12e8.png">
So I tried to check the executable, I found that the executable cannot be executed in this machine.
<img width="424" alt="image" src="https://user-images.githubusercontent.com/43088530/184196602-9e3c6abc-b1a2-4e2a-ab02-e3121cded6d6.png">

## Second, I try the node/yarn method
I switch the script to `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }`, and try to compile the executable myself. But I still got this.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/43088530/184197221-c78e0ab0-e553-48b9-9780-bdf0978a9782.png">
I don't know why fetch "x64" files in my machine. Maybe it's the key point?
<img width="640" alt="image" src="https://user-images.githubusercontent.com/43088530/184197293-bcd15d30-bcb2-45ee-a863-5a9b5655b03f.png">

- Finally, I found that the system calls not support. Are there any good solutions to this?
- Does this issue has something to do with https://github.com/iamcco/markdown-preview.nvim/issues/287 ?

**Desktop (please complete the following information):**
 - OS: Darwin Monterey macOS 12.5

**Comment by CollieIsCute** [comment]
I don't know why, but the plug works fine in my m2 machine now. Even if I delete whole directory, the plug is installed perfectly with x86_64 executable.

**Comment by livrth** [comment]
Is there any progress towards a solution to this problem? I'm a M2 user and also have this problem.

```bash
[1/4] 🔍  Resolving packages...
success Already up-to-date.
> pkg@5.6.0
node:internal/child_process:420
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at fabricate (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/pkg/lib-es5/fabricator.js:55:51)
    at fabricateTwice (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/pkg/lib-es5/fabricator.js:120:5)
    at MultiStream._queue (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/pkg/lib-es5/producer.js:266:68)
    at MultiStream._next (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/multistream/index.js:86:12)
    at Meter.onEnd (/Users/z/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/node_modules/multistream/index.js:129:12)
    at Object.onceWrapper (node:events:627:28)
    at Meter.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by reinhrst** [comment]
> I don't know why, but the plug works fine in my m2 machine now. Even if I delete whole directory, the plug is installed perfectly with x86_64 executable.

This put in on the right track. Since it's an x86_64 executable, you need to make sure that you have rosetta installed on an M1/M2 mac. This is installed the first time you start (from ui) an intel-program; but these days you can live your life quite happily for a while without every running intel-- until you can't.

Solution is: install rosetta: `/usr/sbin/softwareupdate --install-rosetta --agree-to-license` (for MacOS Ventura at least)
