### ISSUE TITLE
Inline link does not work unless prefix with http:// or https://

### ISSUE THREAD

**Issue by jdhao** [iamcco/markdown-preview.nvim#5]
The inline link does not work unless I add `http://` or `https://` before the web address. For example, `[goolge](www.google.com)` is rendered incorrectly while `[goolge](https://www.google.com)` is correctly rendered (I can click to visit Google).

**Comment by iamcco** [comment]
Yes, it's correct behavier. The protocol (http/https/...) is part of the url, so if you dont specify the protocol it will be the  current protocol + path  + your url when you click. or if you don't want to specify the protocol, you can add `//` prefix to you url. like `[google](//www.google.com)`.
