### ISSUE TITLE
E117: Unknown function: mkdp#util#install

### ISSUE THREAD

**Issue by ppnman** [iamcco/markdown-preview.nvim#50]
安装插件的时候报错：
```
Post-update hook for markdown-preview.nvim ... Vim(return):E117: Unknown function: mkdp#util#install
```

vim是官网最新build的版本。https://github.com/vim/vim-win32-installer/releases
系统：win10

**Comment by iamcco** [comment]
你用什么插件管理插件安装的？还有用的什么命令？如果是vim-plug 试试升级 vim-plug 本身试下

**Comment by ppnman** [comment]
已经是最新的vim-plug了。
vimrc里面的命令是
```
    Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown' }
```
这个报错很奇怪，不是安装失败，而是根本找不到这个命令。

**Comment by iamcco** [comment]
把 `'for': 'markdown'`去掉看看

**Comment by iamcco** [comment]
或者改成 `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}`

**Comment by ppnman** [comment]
@iamcco 
现在电脑不在身边了，明天我尝试下。谢谢你了。

**Comment by ppnman** [comment]
@iamcco 
我借了别人电脑试了一下，果然是vim-plug中for语法的问题。写成
```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
```
就可以了。
真神奇，for不是控制一个插件安装之后是否加载它吗？按理说插件还未安装的时候，for应该是没用的呀。

**Comment by iamcco** [comment]
hook 是安装完调用的

**Comment by ppnman** [comment]
了解，感谢。

**Comment by jdhao** [comment]
我也遇到了类似的问题，使用的是 vim-plug，奇怪的是之前使用

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown' }
```

是没有问题的，最近才出现这个问题。

**Comment by iamcco** [comment]
@jdhao 

是不是加了 for markdown，需要加上 vim-plug
```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
```

**Comment by jdhao** [comment]
我家上 vim-plug，好像也有点问题，后来全部去了，就可以正常安装了。。

**Comment by iamcco** [comment]
加上 `vim-plug` 是啥问题？

**Comment by jdhao** [comment]
我刚才重新测试了一下，加上 vim-plug 没问题，之前有问题，可能是我安装插件以后没有重启 Neovim 导致的。

**Comment by AzraelWarrior** [comment]
在安装的时候遇到一个这样的问题：
Post-update hook for markdown-preview.nvim ... Vim(call):E117: Unknown function: term_start
使用vim-plug进行安装，安装方式：
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}操作系统：macOS Mojave

在macOS上就会出问题，在Ubuntu上是好使的，同样的操作方式……

**Comment by Akin909** [comment]
Is it worth adding this fix to the `README.md`? happy to make that change if you agree was having this issue for months before I found this issue

**Comment by iamcco** [comment]
@Akin909 looks good to me.

**Comment by StarryLeo** [comment]
This may be caused by post-update hook bug of vim-plug, see https://github.com/junegunn/vim-plug/issues/964, after fixed, the following line

`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }`

should work fine without adding `'for': 'vim-plug'`. Before fixed, I have been using

`Plug 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()'}`

which also is supposed by vim-plug to solve this problem.

**Comment by Akin909** [comment]
I just tried removing vim-plug from the `for` and hit the same error as before, and I'm on the latest vim plug version :cry:

**Comment by ACupofAir** [comment]
我在win10下gvim8.2按教程配置了默认.vimrc后还是报错
![image](https://user-images.githubusercontent.com/58850527/86518884-a35e5a00-be67-11ea-8be2-ca1b2fa6b3c3.png)

这是我的插件配置文件:
![image](https://user-images.githubusercontent.com/58850527/86518916-ed474000-be67-11ea-9762-59b1c42e6f31.png)

**Comment by sober-wang** [comment]
Oh, Gold! why need username and password? 
![image](https://user-images.githubusercontent.com/35804630/128656923-a76d5420-1a4e-495b-9cbd-a429c92569d0.png)

**Comment by yzymickey** [comment]
Invalid expression: > mkdp#util#install() }, 'for': ['markdown', 'vim-plug']})  what is this?

**Comment by junshoong** [comment]
Thanks! it's works for me
~/.vimrc
```
" Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown' }
```
then, `:call mkdp#util#install()`

**Comment by Crazyokd** [comment]
Consider using the plug-in manager to see if the plug-in has been successfully installed.

**Comment by diamondburned** [comment]
I'm still getting this error with both

```vim
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': 'markdown' }
```

and

```vim
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
```

I should be on latest vim-plug.

The full error is:

```
x Post-update hook for markdown-preview.nvim ... Vim(call):E117: Unknown function: mkdp#util#install
```

**Comment by ChingChang9** [comment]
I am getting this error as well. I can get past it by running `:call mkdp#util#install()` manually, but then it says
```
E903: Process failed to start: no such file or directory: "/home/elaina/.vim/plugged/markdown-preview.nvim/app/bin/markdown-preview-linux"
```
even though the file is there, with execute permission.

**Comment by m-danya** [comment]
None of the solutions above helped me, so I just switched to the second option of installing this plugin from the README — by installing npm (here I install it via [nvm](https://github.com/nvm-sh/nvm)) and yarn:

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
nvm install stable
nvm use stable
npm install -g yarn
```
with this line in my vim config:

```
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }
```

**Comment by zergzlun** [comment]
I'm still getting the same error but can solve this by manually calling `:call mkdp#util#install()` as @cocoliliace mentioned above.

**Comment by pujeromir** [comment]
x Post-update hook for markdown-preview.nvim ... Vim(call):E117: Unknown function: term_start是什么错误
