### ISSUE TITLE
Force preview window to be opened in new window

### ISSUE THREAD

**Issue by Manu343726** [iamcco/markdown-preview.nvim#51]
Hi,

I've been reviewing your code to figure out if it would be possible to launch the browser with a new window flag, like Google Chrome's `--new-window` so that my preview document is always open in its own browser window.

This would be really helpful in multi-desktop workflows where you have your browsing stuff (google, StackOverflow, etc) in one browser instance in one desktop, but want the preview window in the same desktop as the editor.

BTW thanks for your work, this plugin provides the best markdown editing experience for vim so far.

**Comment by iamcco** [comment]
use `g:mkdp_browserfunc` option.

example: https://github.com/iamcco/markdown-preview.nvim/issues/19#issuecomment-464338238

**Comment by Manu343726** [comment]
Great, thanks, that should do the job.
