### ISSUE TITLE
怎么设置可以开启预览时，鼠标的焦点不移动到浏览器，而是仍然停留在终端上，少一次切换的过程

### ISSUE THREAD

**Issue by GgoCoder** [iamcco/markdown-preview.nvim#513]
如题，
当我开启预览时，vim的输入框变成了 edge浏览器，需要我重新切换到终端上才能继续输入。希望开启预览时不用切换可以继续在终端上输入

os：wsl2
terminal：windows Terminal
浏览器： edge

**Comment by iamcco** [comment]
目前没有找到什么办法打开浏览器不失去焦点。找到了记得告诉我，先关了
