### ISSUE TITLE
OSX 使用vundle安装无法运行

### ISSUE THREAD

**Issue by HUSTWillHe** [iamcco/markdown-preview.nvim#52]
我是否应该将readme中的那些config添加到自己的vimrc中？

**Comment by HUSTWillHe** [comment]
我的默认浏览器是chrome，使用MarkdownPreview命令时不会有效果，使用MarkdownPreviewStop时，显示不是编辑器命令。我尝试了
https://github.com/iamcco/markdown-preview.vim/issues/1
中的方法，依然没有效果。
但是我使用之前那个仓库是能工作的。

**Comment by iamcco** [comment]
vundle 不支持 hook，装完后手动执行 `call mkdp#util#install()`

**Comment by HUSTWillHe** [comment]
已经可以了，感谢
