### ISSUE TITLE
Unable to open preview

### ISSUE THREAD

**Issue by mikiya09** [iamcco/markdown-preview.nvim#524]
I see this error message after using :MarkdownPreview command, and I had node.js and nom installed.
don't know if it's because I just updated to the latest macOS version Ventura

<img width="1095" alt="Screenshot 2022-11-04 at 12 00 34 AM" src="https://user-images.githubusercontent.com/94091460/199882865-9d49c793-ab4d-425a-8c99-14d348e5e6e8.png">

**Comment by zhanghailin-ones** [comment]
Got the same issue a while and couldn't find a fix

**Comment by chananababa** [comment]
I have the same issue with Monterey

**Comment by mikiya09** [comment]
I had checked the referred code from case #432, but still the same issue
<img width="972" alt="200232333-e933f6fd-daac-472c-a6c3-d648997e2851" src="https://user-images.githubusercontent.com/94091460/200385027-1f9ac20b-a155-43b1-bd17-2de1cb72a643.png">

**Comment by mikiya09** [comment]
I have reinstalled the plugin and it works right now, thanks!
