### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by kl0renzo** [iamcco/markdown-preview.nvim#542]
**XSS**
The following input triggers XSS.

`<iframe srcdoc="<script>alert('XSS')</script>"></iframe>`

**Screenshots**
![image](https://user-images.githubusercontent.com/20153276/212535297-6affa3ba-553f-4308-86da-fc1152cea7b9.png)

**I used:**
* Mozilla Firefox 108.0.1
* markdown-preview: latest commit (02cc3874738bc0f86e4b91f09b8a0ac88aef8e96)
* OS: Linux

**Comment by iamcco** [comment]
disable html tag if you want

```vim
let g:mkdp_preview_options = {
    \ 'mkit': { html: v:false },
    \ }

```
