### ISSUE TITLE
Cannot work with message "Node.js v19.6.1"

### ISSUE THREAD

**Issue by Fireond** [iamcco/markdown-preview.nvim#552]
`:MarkdownPreview` command not work with error messages "Node.js v19.6.1". 
Environment: MacBook m1, neovim v0.8.3.
Use `brew install nodejs` to install node.
Use `lazy.vim` to download plug with settings: 
```lua
{
    "iamcco/markdown-preview.nvim",
    build = "cd app && npm install",
    init = function()
      vim.g.mkdp_filetypes = { "markdown" }
    end,
    ft = { "markdown" },
},
```
or
```lua
{
    "iamcco/markdown-preview.nvim",
    build = function()
      vim.fn["mkdp#util#install"]()
    end,
    ft = "markdown",
},
```
both tried and broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/42907735/219935189-5d16681b-b57b-47cf-abd2-672ad0b21121.png)

**Comment by Azkaas** [comment]
I had the same issue as you, but just managed to fix it.

❯ cd ~/.local/share/nvim/lazy/markdown-preview.nvim
❯ cd app && yarn

**Comment by EstelZhao** [comment]
> I had the same issue as you, but just managed to fix it (Although Im on Linux)
> 
> ❯ cd ~/.local/share/nvim/lazy/markdown-preview.nvim ❯ cd app && yarn

how?

**Comment by EstelZhao** [comment]
> I had the same issue as you, but just managed to fix it (Although Im on Linux)
> 
> ❯ cd ~/.local/share/nvim/lazy/markdown-preview.nvim ❯ cd app && yarn

 you are genius! I spent a whole night dealing with it

**Comment by Azkaas** [comment]
> you are genius! I spent a whole night dealing with it

Happy to help :)

**Comment by powrhouseofthecell** [comment]
> I had the same issue as you, but just managed to fix it (Although Im on Linux)
> 
> ❯ cd ~/.local/share/nvim/lazy/markdown-preview.nvim ❯ cd app && yarn


🫡 Got the same error for node 20.11 this helped.
