### ISSUE TITLE
预览显示连接失败

### ISSUE THREAD

**Issue by xccoco** [iamcco/markdown-preview.nvim#555]
系统为 kubuntu，用 firefox 和 chrome 打开均会显示如下界面:

![](https://cdn.luogu.com.cn/upload/image_hosting/a1hdgfgc.png)

**Comment by xccoco** [comment]
https://cdn.luogu.com.cn/upload/image_hosting/a1hdgfgc.png

**Comment by iamcco** [comment]
用的是旧版插件吧？markdown-preview.vim 是旧插件，markdown-preview.nvim 是新插件
