### ISSUE TITLE
install with lazy.nvim

### ISSUE THREAD

**Issue by r3k2** [iamcco/markdown-preview.nvim#558]
Hello, I am trying diff ways to install this with the correct configuration with lazy.nvim I think is installing it but missing something because I can't get the command :MarkdownPreview as an option.

Thank you!

**Comment by sangdth** [comment]
@r3k2 have you tried this way?

```
  {
    "iamcco/markdown-preview.nvim",
    ft = "markdown",
    build = function()
      vim.fn["mkdp#util#install"]()
    end,
  },
```

**Comment by r3k2** [comment]
This works, thank you. 
Is there a way to tell what browser to use?
Thanks

**Comment by commanderh** [comment]
I am still unable to install for some odd reason. I keep getting this error when I run the command `messages`:

My course of actions thus far:
- create a markdown-preview.lua file into my plugins folder
- have these lines of code in it
```
return {
  "iamcco/markdown-preview.nvim",
  ft = "markdown",
  build = function()
    vim.fn["mkdp#util#install"]()
  end,
}
```
-write. run the source % command. quit. reload. 
and it doesnt work, and i proceed to get these in my command messages log

```
E471: Argument required
internal/modules/cjs/loader.js:934
  throw err;
  ^
Error: Cannot find module '@chemzqm/neovim'
Require stack:
- /Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/preloadmodules.js
- /Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/load.js
- /Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js
- /Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/preloadmodules.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/preloadmodules.js',
    '/Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/load.js',
    '/Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js',
    '/Users/huy/.local/share/nvim/lazy/markdown-preview.nvim/app/index.js'
  ]
}
```

**Comment by jpizzle34** [comment]
@commanderh looks like you are missing an extra pair of brackets. should be like so:
```lua
return {
  {
    "iamcco/markdown-preview.nvim",
    run = function()
      vim.fn["mkdp#util#install"]()
    end,
  },
}

```

**Comment by AXGKl** [comment]
```lua
return {
  {
    "iamcco/markdown-preview.nvim",
    ft = "markdown",
    lazy = true,
    build = "cd app && npm install && git reset --hard",
  },
}
```
worked for me.  at last it should be `build`, not `run`, imho.

**Comment by V4G4X** [comment]
This is really weirding me out as the commands appear for me but the preview does not open. 
I have configured it as: 
```
  {
    "iamcco/markdown-preview.nvim",
    ft = "markdown",
    build = function() vim.fn["mkdp#util#install"]() end,
  },
```

But when I open a markdown file and do `:MarkdownPreview`. The browser does not open the way it used to when I user Packer. 

Where can I find some logs for this?

**Comment by SureshPradhana** [comment]
> This is really weirding me out as the commands appear for me but the preview does not open. I have configured it as:
> 
> ```
>   {
>     "iamcco/markdown-preview.nvim",
>     ft = "markdown",
>     build = function() vim.fn["mkdp#util#install"]() end,
>   },
> ```
> 
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/pieces.png)
> Copy and Save
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> But when I open a markdown file and do `:MarkdownPreview`. The browser does not open the way it used to when I user Packer.
> 
> Where can I find some logs for this?

I am also facing same issue browser does not open

**Comment by FrostyNick** [comment]
This is how I configured it in Lazy and it seems to work. Converted from Packer to Lazy from Lazy docs. `npm` could probably be swapped with `yarn` too.

```lua
{"iamcco/markdown-preview.nvim",
  ft = "markdown",
  -- build = "cd app && yarn install", -- after removing Joplin one day
  build = "cd app && npm install",
  init = function() vim.g.mkdp_filetypes = { "markdown" } end,
},
```

**Comment by V4G4X** [comment]
Hi @FrostyNick , I realized I don't have yarn installed, but I did have npm installed but it still didn't work.  

😔

**Comment by FrostyNick** [comment]
Things to try:
1. In Neovim: `:checkhealth mkdp` to see any if there's any missing dependencies. It should mention there if anything is missing.

2. Does `:La` / `:Lazy` work? If it does, does it show the plugin in the plugin list?

3. In terminal: `node --version`
In my case it was v18.16.1 .. maybe your node needs to be updated.

4. I am using Librewolf (fork of Firefox). Not sure if the browser affects this.

**Comment by IgberZBN** [comment]
> Things to try:
> 
> 1. In Neovim: `:checkhealth mkdp` to see any if there's any missing dependencies. It should mention there if anything is missing.
> 2. Does `:La` / `:Lazy` work? If it does, does it show the plugin in the plugin list?
> 3. In terminal: `node --version`
>    In my case it was v18.16.1 .. maybe your node needs to be updated.
> 4. I am using Librewolf (fork of Firefox). Not sure if the browser affects this.

## still doesn't work

**1.** ![image](https://github.com/iamcco/markdown-preview.nvim/assets/118772077/59f83fe6-0778-4e5c-855b-a1b5117c8400)

**2.** ![image](https://github.com/iamcco/markdown-preview.nvim/assets/118772077/b984a936-3dde-4a0c-b46e-5f3a365998e5)

**My config:**

```lua
{
    "iamcco/markdown-preview.nvim",
    ft = "markdown",
    build = "cd app && npm install",
    init = function()
      vim.g.mkdp_filetypes = { "markdown" }
    end,
},
```

**Comment by andres-lowrie** [comment]
> ```lua
>  ft = "m
> ```

I have a very similar setup except I'm doing all my bindings using the `config` function and not the `init`, looks like this

```lua
{
  'iamcoo/markdown-preview.nvim',
  build = 'cd app && npm install',
  config = function()
    vim.g.mkdp_auto_close = 1
    vim.g.set('n', '<leader>mp', '<Plug>MarkdownPreviewToggle', { desc = '[M]arkdown [P]review'})
  end
}
```

I'm a complete noop with lazy but I think the `init` function is running at a different time before the plugin is ready (don't quote me 😅 ) and `config` runs once the plugin is loaded

**Comment by BulaBula-zy** [comment]
@IgberZBN

> I discovered the error, I needed to manually run 'npm install' in the plugin folder
cd ~/.local/share/nvim/lazy/markdown-preview.nvim 

worked for me, thanks.

btw, it seems like you should run `npm install` in this folder `~/.local/share/nvim/lazy/markdown-preview.nvim/app` instead.

**Comment by fcarvalhopacheco** [comment]
the following worked for me:
https://github.com/iamcco/markdown-preview.nvim/issues/595#issuecomment-1630961979

```lua
return {
  {
    "iamcco/markdown-preview.nvim",
    build = "cd app && npm install",
    ft = "markdown",
    lazy = true,
    keys = { { "gm", "<cmd>MarkdownPreviewToggle<cr>", desc = "Markdown Preview" } },
    config = function()
      vim.g.mkdp_auto_close = true
      vim.g.mkdp_open_to_the_world = false
      vim.g.mkdp_open_ip = "127.0.0.1"
      vim.g.mkdp_port = "8888"
      vim.g.mkdp_browser = ""
      vim.g.mkdp_echo_preview_url = true
      vim.g.mkdp_page_title = "${name}"
    end,
  },

}
```

**Comment by iamcco** [comment]
README has been updated
