### ISSUE TITLE
Doesn't work on macos with neovim

### ISSUE THREAD

**Issue by svermeulen** [iamcco/markdown-preview.nvim#57]
I tried installing both with yarn+node and also the other way, but either way, when I start the server it does nothing.  `mkdp#rpc#get_server_status()` returns zero.  Any idea what I could be doing wrong?

**Comment by sff1019** [comment]
Had the same problem, but once I changed the `yarn` to `npm` it worked!

Removed the repo 
```
$ rm -rf ~/.vim/dein/repos/github.com/iamcco
```

and then changed the install method: 
```
  call dein#add('iamcco/markdown-preview.nvim', {'on_ft': ['markdown', 'pandoc.markdown', 'rmd'],
                    \ 'build': 'cd app & npm install' })
```

**Comment by iamcco** [comment]
@svermeulen What's the way you install this plugin?

**Comment by svermeulen** [comment]
I tried both of the suggestions:
```
" If you don't have nodejs and yarn
" use pre build
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }

" If you have nodejs and yarn
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
```
I also tried using npm install instead but still no luck

**Comment by svermeulen** [comment]
Oh ok it works now   :)

Changed to use `npm install` (thanks @sff1019) and then explicitly calling `call mkdp#util#open_preview_page()`

Seems great so far, thanks for this

**Comment by iamcco** [comment]
if you use the `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }` after vim-plug install the plugin it will download the pre build binary.

if you use `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }` you have to install nodejs and yarn or change `yarn install` to `npm install` if you don't have yarn.

**Comment by svermeulen** [comment]
I don't think the pre-built binary works.  At least it didn't for me

**Comment by iamcco** [comment]
It use pkg to build package and may can not work on some operate system.
