### ISSUE TITLE
<C-i>h    ==    Highlight   是否是正常的呢，如何更改<C-i>h 这个快捷键，因为这个快捷键和我的配置冲突了

### ISSUE THREAD

**Issue by yao1818** [iamcco/markdown-preview.nvim#570]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

Log:

```
```

**Comment by yao1818** [comment]
Ctrl+i 然后迅速按h键，就会自动填充  ====  高亮的符号，如何修改这个呢？

**Comment by iamcco** [comment]
这插件没有任何 key mapping
