### ISSUE TITLE
Node js version

### ISSUE THREAD

**Issue by OlojaMuyiwa** [iamcco/markdown-preview.nvim#589]
**Describe the bug**
i installed then run `:MarkdownPreview` and i get this message(below) but it does'nt lauch the markdown preview server
![image](https://github.com/iamcco/markdown-preview.nvim/assets/97600170/fa5c495d-260f-4340-9dfb-882aa0c5265c)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

Log:

```
```

**Comment by joshgubler** [comment]
I ran into this because I didn't have yarn installed, so the plugin install hadn't finished. I fixed it with:
```
brew install yarn
cd ~/.vim/plugged/markdown-preview.nvim/app/
yarn install
```

Or just uninstall and re-install the plugin after installing yarn.

**Comment by OlojaMuyiwa** [comment]
> I ran into this because I didn't have yarn installed, so the plugin install hadn't finished. I fixed it with:
> 
> ```
> brew install yarn
> cd ~/.vim/plugged/markdown-preview.nvim/app/
> yarn install
> ```
> 
> Or just uninstall and re-install the plugin after installing yarn.

It's working now thanks
