### ISSUE TITLE
能不能像jupyter notebook那样把端口固定下来, 这样我可以把markdown preview的窗口页面做为应用通过浏览器安装到桌面上

### ISSUE THREAD

**Issue by ZihaoXingUP** [iamcco/markdown-preview.nvim#598]
能不能像jupyter notebook那样把端口固定下来, 这样我可以把markdown preview的窗口页面做为应用通过浏览器安装到桌面上，jupyter notebook每次打开的网址都是localhost:8888, 但是这个markdown preview每次打开端口号都变了，我每次通过通过浏览器把预览窗口安装到桌面上。
![markdown_preview](https://github.com/iamcco/markdown-preview.nvim/assets/68001792/cc33b570-24ec-4665-9a71-c2a9cc0c24bb)

**Comment by tandy1229** [comment]
lua:
```lua
 vim.g.mkdp_open_ip = "127.0.0.1"
 vim.g.mkdp_port = "8888"
```

vimscript:
```vim
let g:mkdp_open_ip = '127.0.0.1'
let g:mkdp_port = '8888'
```

**Comment by ZihaoXingUP** [comment]
> lua:
> 
> ```lua
>  vim.g.mkdp_open_ip = "127.0.0.1"
>  vim.g.mkdp_port = "8888"
> ```
> 
> vimscript:
> 
> ```viml
> let g:mkdp_open_ip = '127.0.0.1'
> let g:mkdp_port = '8888'
> ```

好的，非常感谢呀！
