### ISSUE TITLE
Failed to start vim-node-rpc service报错打不开markdownPreview了

### ISSUE THREAD

**Issue by zihaoxingstudy1** [iamcco/markdown-preview.nvim#602]
Failed to start vim-node-rpc service报错打不开markdownPreview了
![image](https://github.com/iamcco/markdown-preview.nvim/assets/58220227/a04a3676-2acd-4308-bf8a-7f6826436c91)

**Comment by iamcco** [comment]
最新版已经没有 vim-node-rpc 了
