### ISSUE TITLE
Error detected while processing function CompileRunGcc[39]..mkdp#util#open_preview_page[6]..mkdp#rpc#start_server: line 18:

### ISSUE THREAD

**Issue by eawlot3000** [iamcco/markdown-preview.nvim#603]
in this same computer i used it and everything alright. yesterday erase all contents and reinstall the os. got errors.

i use mac os 12 + NVIM v0.9.1 (which is the latest), i installed by putting this in my nvim rc `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }` + zsh + tmux.
when call by `:MarkdownPreview`, i got this:

```
Error detected while processing function CompileRunGcc[39]..mkdp#util#open_preview_page[6]..mkdp#rpc#start_server:
line   18:
E903: Process failed to start: Unknown system error -86: "/Users/eawlot3000/.local/share/nvim/plugged/markdown-preview.nvim/app/bin/markdown-preview-macos"
Press ENTER or type command to continue
```

please specify the possible solution of this. never seen this before
thank you

**Comment by romero-kenny** [comment]
Just checked, it is not broken anymore. Try updating.

**Comment by Pandoks** [comment]
Same issue with MacOS 13. Tried reinstalled. Tried both ways of installing. Nothing is working. I also had it working before with Packer with npm. Now I'm using Lazy. This is my config:
```lua
return {
  "iamcco/markdown-preview.nvim",
  build = function()
    vim.fn["mkdp#util#install"]()
  end,
}
```

**Comment by Pandoks** [comment]
Fixed the issue (For ARM architecture of Macs)! I ran the binary directly and got the error: `zsh: bad CPU type in executable: ./markdown-preview-macos`. This is easy to fix.

Go to your terminal emulator and right click it->Get info->Open using Rosetta. Restart your emulator and it should work.

**Comment by romero-kenny** [comment]
> Fixed the issue (For ARM architecture of Macs)! I ran the binary directly and got the error: `zsh: bad CPU type in executable: ./markdown-preview-macos`. This is easy to fix.
> 
> Go to your terminal emulator and right click it->Get info->Open using Rosetta. Restart your emulator and it should work.

I think you just need to install Rosetta 2. Since a fresh install of macOS does not include Rosetta 2 with it. This is the only major difference I noticed between the time of fresh installing macOS and using my laptop now.

**Comment by Pandoks** [comment]
Seems like I only needed to run preview once in Rosetta and then after that, I am not running on Rosetta and it still works.
