### ISSUE TITLE
Installation instruction for `NvChad`'s `lazy` plugin manager

### ISSUE THREAD

**Issue by aap01** [iamcco/markdown-preview.nvim#609]
You may also need to add `ft = {"markdown"}`.
Else Lazy.nvim may not load the plugin, when opening a Markdown file.
(At least on NvChad)

```lua
{ "iamcco/markdown-preview.nvim",
	ft={"markdown"},
	build = function() vim.fn["mkdp#util#install"]() end,
},
```

_Originally posted by @Rocco-Gossmann in https://github.com/iamcco/markdown-preview.nvim/issues/608#issuecomment-1740208941_

**Comment by iamcco** [comment]
README has been update
