### ISSUE TITLE
OSX SpaceVim : No matching autocommands

### ISSUE THREAD

**Issue by MinuteSheep** [iamcco/markdown-preview.nvim#61]
## description
When I use `spc b f` to preview markdown, shows me `No matching autocommands`
## info
system : OSX + zsh
vim : Space-Vim
details of `markdown.vim`:
```
call add(Plugins,['iamcco/mathjax-support-for-mkdp',{ 'on_ft' : 'markdown'}])
call add(Plugins,['iammcco/markdown-preview.nvim',
       \{ 'on_ft' : 'markdown',
       \ 'depends' : 'open-browser.vim',
       \ 'build' : ' cd app & yarn install' }])
```

**Comment by iamcco** [comment]
I know less about Space-Vim's struct, it seems plugin install not complete, also you have to install nodejs and yarn if you use yarn to install dependencies.

> `iamcco/mathjax-support-for-mkdp` is no need

**Comment by MinuteSheep** [comment]
ok, i'll continue troubleshooting, thank you ~

**Comment by SichangHe** [comment]
The solution is mentioned [here](https://github.com/SpaceVim/SpaceVim/issues/3323)
SpaceVim's package manager does not install it completely
