### ISSUE TITLE
Links Problems with markdown previews

### ISSUE THREAD

**Issue by PalsFreniers** [iamcco/markdown-preview.nvim#625]
**Bug Description**
links override tab and stop server with markdown previews

**To Reproduce**
write a link in the markdown like 
```Markdown
[test](https://google.com)
```
and click on it on the preview
then go back to the previous page

**Expected behavior**
I think it should open in a new tab or don't stop server so we can go back after clicking on a link.

**Comment by CommanderGL** [comment]
It doesn't stop the server this is actually a different problem where the real content is at `/page/1` but it redirects to `/1` while keeping content after pressing back if you replace `/1` with `/page/1` it should fix your problem

**Comment by PalsFreniers** [comment]
ok thanks

**Comment by CommanderGL** [comment]
but this is still a problem and I will be opening a new issue.
