### ISSUE TITLE
:MarkdownPreview does nothing: Mac vim version 9

### ISSUE THREAD

**Issue by Iridium-Lo** [iamcco/markdown-preview.nvim#628]
**Describe the bug**
:MarkdownPreview does not open rendered markdown file in browser, it does nothing

**To Reproduce**
Steps to reproduce the behaviour:

Plugin manager is `pathogen`
1. git cloned repo to `~/.vim/bundle`
2. `vim  README.md`
3. :MarkdownPreview
4. nothing happens

**Expected behaviour**
`:MarkdownPreview` should launch a browser window.

**Screenshots**
Executing `:MarkDownPreview`:
<img width="1440" alt="Screenshot 2023-12-26 at 03 38 57" src="https://github.com/iamcco/markdown-preview.nvim/assets/80277972/8678d94f-5987-4e2e-b493-ac8d535a6ad5">

After execution:
<img width="1440" alt="Screenshot 2023-12-26 at 03 38 28" src="https://github.com/iamcco/markdown-preview.nvim/assets/80277972/93c16d8c-c28a-4fc1-872f-766795573701">

**Desktop and more info (please complete the following information):**
 - OS: ventura 13.4 
- nodejs and yarn installed 

```
 λ vim --version | grep 9
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 05 2023 14:38:33)
+cmdline_compl     +lambda            +profile           +vim9script
~:  
 λ node --version
v21.5.0
~:  
 λ yarn --version
1.22.21
```

**Comment by palladium-o** [comment]
also on Ventura 14.2.1

**Comment by Iridium-Lo** [comment]
I got it working by cd'ing to the plugin directory and running `npm install`

**Comment by SpamixOfficial** [comment]
> I got it working by cd'ing to the plugin directory and running `npm install`

This also resolved it for me

**Comment by Iridium-Lo** [comment]
I added a PR to for the readme to add this for to get normal vim working @iamcco it's been tested by 4 people no (1 of which is me) https://github.com/iamcco/markdown-preview.nvim/pull/649
