### ISSUE TITLE
浏览器跳转url，页面无法刷新

### ISSUE THREAD

**Issue by wty20060888** [iamcco/markdown-preview.nvim#635]
**Describe the bug**
插件可正常预览，但在浏览器中无法进行刷新

**To Reproduce**
1. `:MarkdownPreview`浏览器自动跳转至 url为`localhost:xxxx/1`，可以正常预览
2. 浏览器端按`F5`刷新，网页404
3. 浏览器网址栏输入`http://localhost:xxxx/page/1` 可恢复预览，但网页URL，跳转至`localhost:xxxx/1`，这时再次刷新，与Step2青铜相同

**Expected behavior**

**Screenshots**
![Jan-03-2024 16-07-11](https://github.com/iamcco/markdown-preview.nvim/assets/49235401/199b794a-e78a-46fd-b7e9-dce9324dab5e)

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1

Log:

```
```

**Comment by cybaol** [comment]
这个问题解决了吗?

**Comment by wty20060888** [comment]
@cybaol 已经解决了
修改`router.js`文件,增加以下代码
```js
// /:number
use((req, res, next) => {
  const number = req.asPath.slice(1); // 获取路径中的数字部分
  if (/^\d+$/.test(number)) {
    const newUrl = `/page/${number}`;
    res.writeHead(301, { Location: newUrl }); // 重定向到新的路径
    res.end();
  } else {
    next();
  }
});
```

**Comment by zhaozg** [comment]
@iamcco 请问这个改动可否合并到版本中呢

**Comment by wty20060888** [comment]
@zhaozg  有时间我会提个repo

**Comment by JunYang-tes** [comment]
去掉这行也行：
https://github.com/iamcco/markdown-preview.nvim/blob/a923f5fc5ba36a3b17e289dc35dc17f66d0548ee/app/pages/index.jsx#L123

没发现有其它影响
