### ISSUE TITLE
Preview produces 400 Bad Requests in Browser, Unsupported Protocol version

### ISSUE THREAD

**Issue by sboesebeck** [iamcco/markdown-preview.nvim#657]
**Describe the bug**
I try to use Markdown Preview. Type in `:MarkdownPreview` and the browser opens. White page. The browser shows errors in the console:

``` 
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (socket.io, line 0)    http://localhost:8694/socket.io/?bufnr=11&EIO=3&transport=polling&t=OvjTJ9T
```

When calling the link, the result is:

``` 
{
  "code": 5,
  "message": "Unsupported protocol version"
}
```

**To Reproduce**
1. open a markdown file in neovim
2. type `:MarkdownPreview`
3. admire the blank page

**Expected behavior**
I thought, I'd see some kind of preview 😉 

**Desktop (please complete the following information):**
 - OS:  MacOS, tested with Browsers Safari, Firefox, Chrome

Log:

```
empty
```

**Comment by sboesebeck** [comment]
I am not sure, what happened, but it seems to be fixed now.

**Comment by MrMicc** [comment]
@sboesebeck , I'm facing the same issue that you have report
Did you do anything to try to solve it?

**Comment by Luiz-Micci** [comment]
It is working for me now

To resolve it was necessary to install socket.io with de version 2.x.x 

The problem was a GET that is using EIO=3 and this version of EIO was used on an undated version of socket.io 

```
http://localhost:8155/socket.io/?bufnr=1&EIO=3&transport=polling&t=PEXZTrk
```
