### ISSUE TITLE
Can't start `MarkdownPreview` in mac m2 

### ISSUE THREAD

**Issue by touero** [iamcco/markdown-preview.nvim#660]
My env: mac m2, lazyvim, wezterm.

Try `MarkdownPreview` it  will have a log hint:

```
Error detected while processing function mkdp#util#toggle_preview[2]..mkdp#util#open_preview_page[6]..mkdp#rpc#start_server:
line   18:
E903: Process failed to start: Unknown system error -88: "/Users/weiensong/.local/share/nvim/lazy/markdown-preview.nvim/app/bin/markdown-preview-macos-arm64"
Error detected while processing function mkdp#util#toggle_preview[2]..mkdp#util#open_preview_page[6]..mkdp#rpc#start_server:
line   18:
E903: Process failed to start: Unknown system error -88: "/Users/weiensong/.local/share/nvim/lazy/markdown-preview.nvim/app/bin/markdown-preview
```

it’s logs
![截屏2024-04-05 14 51 07](https://github.com/iamcco/markdown-preview.nvim/assets/61647484/b8cfcac2-d681-481c-ad86-68bd81f5830f)

**Comment by nbari** [comment]
Same here but after updating nodejs to v20.12.1

**Comment by touero** [comment]
> Same here but after updating nodejs to v20.12.1

![截屏2024-04-06 11 04 18](https://github.com/iamcco/markdown-preview.nvim/assets/61647484/f70d5ca3-2d48-4678-98cb-86b765a02701)

already it is

**Comment by wangwenqiangGitHub** [comment]
![image](https://github.com/iamcco/markdown-preview.nvim/assets/28779327/091c3d4d-bff5-454d-bc5a-86909ab8eb2f)
linux already it is

**Comment by nodu** [comment]
https://github.com/iamcco/markdown-preview.nvim/issues/667#issuecomment-2078041723 Maybe connected?

**Comment by dillontkh** [comment]
> [#667 (comment)](https://github.com/iamcco/markdown-preview.nvim/issues/667#issuecomment-2078041723) Maybe connected?

Was facing this issue on a M2 Mac as well, and reinstalling the plugin as you suggested helped to fix it. Thanks!

**Comment by touero** [comment]
> > [#667 (comment)](https://github.com/iamcco/markdown-preview.nvim/issues/667#issuecomment-2078041723) Maybe connected?
> 
> Was facing this issue on a M2 Mac as well, and reinstalling the plugin as you suggested helped to fix it. Thanks!

How did you do that? I always fail.

**Comment by nodu** [comment]
@touero, You can find the neovim location where your plugins are installed, then delete the folder for this plugin. Then launch your neovim plugin manager again and it should re-install.

**Comment by touero** [comment]
> @touero, You can find the neovim location where your plugins are installed, then delete the folder for this plugin. Then launch your neovim plugin manager again and it should re-install.

Wonderful, I used lazy.vim config my neovim.
1. Delete `~/.local/share/nvim/lazy/markdown-preview.nvim`
2. Restart neovim and waitting install finish.

**Comment by tatthien** [comment]
> > @touero, You can find the neovim location where your plugins are installed, then delete the folder for this plugin. Then launch your neovim plugin manager again and it should re-install.
> 
> Wonderful, I used lazy.vim config my neovim.
> 
> 1. Delete `~/.local/share/nvim/lazy/markdown-preview.nvim`
> 2. Restart neovim and waitting install finish.

It works for me

**Comment by Dolfost** [comment]
> > @touero, You can find the neovim location where your plugins are installed, then delete the folder for this plugin. Then launch your neovim plugin manager again and it should re-install.
> 
> Wonderful, I used lazy.vim config my neovim.
> 
> 1. Delete `~/.local/share/nvim/lazy/markdown-preview.nvim`
> 2. Restart neovim and waitting install finish.

I just disabled it in lazy and reinstalled, thanks!
