### ISSUE TITLE
image not preview

### ISSUE THREAD

**Issue by hyawara** [iamcco/markdown-preview.nvim#673]
windows env

My image path uses an absolute path, which can be displayed normally on obsidian. but markdown-preview.nvim not.

![image](https://github.com/iamcco/markdown-preview.nvim/assets/31959238/7897e911-676a-45d1-8cd4-659d62fc0955)

**Comment by RaidOpe** [comment]
You can try '/' to guide the path (Windows ❤️ Linux）. In my case, using relative path can fix that

**Comment by hyawara** [comment]
> You can try '/' to guide the path (Windows ❤️ Linux）. In my case, using relative path can fix that
relative path is ok.

and I was wondering why the absolute path is not work

**Comment by RaidOpe** [comment]
> > You can try '/' to guide the path (Windows ❤️ Linux）. In my case, using relative path can fix that
> > relative path is ok.
> 
> and I was wondering why the absolute path is not work

A little look at the source code shows that the original author prefers to use MD notes with relative paths.

[This is reason why it works with relative path](https://github.com/search?q=repo%3Aiamcco%2Fmarkdown-preview.nvim+fileDir&type=code)

I find there is a Contributor PR the [root path](https://github.com/iamcco/markdown-preview.nvim/pull/671)  

But now that the original author has abandoned the project and hopes that there will be enthusiasts to update the project in the future, this is a good plugin
