### ISSUE TITLE
Error when running :MarkdownPreview

### ISSUE THREAD

**Issue by ekaj2** [iamcco/markdown-preview.nvim#7]
After installation, I opened a markdown file and ran:

    :MarkdownPreview

And I get back two lines of error:

    [vim-node-rpc] pre build and node not found!
    Pre build and node is not found

Then nothing happens, of course. If I try to run the same command again, I get:

    Pre build and node is not found

...every subsequent time.

I am on Mac OS Mojave with MacVim 8.1 (included patches: 1-577). Incidentally, I get the same error message in Vim 8.0 (in the terminal), but I know this plugin is not guaranteed to work with that version anyhow.

**Comment by iamcco** [comment]
it's seems the pre build is install incomplete. try `:call mkdp#util#install()` to reinstall the pre build.

**Comment by ekaj2** [comment]
@iamcco Thanks, that is correct. Not sure why that didn't work as I added the:

```
" vim-plug
call plug#begin()
    Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}
call plug#end()
```

...from the `README.md`. It looks like it works fine for me now, though, so up to you if you want to close this issue.

**Comment by iamcco** [comment]
maybe network error or others, it works for my vim and neovim. so let this open for a while to see if others will get in this.

**Comment by Goddard** [comment]
somewhat related, I had a new install and couldn't get this working until I ran `:call mkdp#util#install()`

I tried the prebuild and also nodejs and yarn version.  Neither worked until running this command.  Using PlugInstall gave an error 127 I believe, but installed the plugin.  After running the above command everything worked and I could run :MarkdownPreview

I am on Ubuntu 18.04 with the latest Neovim ppa.

**Comment by iamcco** [comment]
@Goddard don't know what happend with the error 127. If install with `Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}` it should open an terminal to download the prebuild same as `:call mkdp#util#install()`

**Comment by Goddard** [comment]
Hi, yeah I am unsure why as I am just getting into neovim/vim.  

All I can tell you is I followed the directions exactly and experienced the same result on two Ubuntu 18.04 systems.

I used Plug-Vim and tried both options provided.  Both didn't work until I ran the install call.

Order of operations
edit init file
stop and start vim
:PlugInstall - This gives a 127 error, but acts like everything was installed
:MarkdownPreview - this just does nothing and gives no error or return.
:call mkdp#util#install() - now everything works
:MarkdownPreview - opens my browser window and works fine

Let me know if you need more information.  Glad to help.  Thanks for your work.

**Comment by chris3ware** [comment]
Hi, having a similar problem on macOS Mojave and Brew VIM version 8.1. I installed via vim-plug with: Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }} - this produced error 127. But appears to be installed.

MarkdownPreview is not recognised as a command, so following this thread, I loaded the plugin in Vim and ran :call mkdp#util#install(). This installed some stuff, however I still get "Not an editor command" for :MarkdownPreview.

**Comment by chris3ware** [comment]
Ignore me, fixed. Was missing call plug#end() in .vimrc so it wasn't initialising the plugin system

**Comment by Henry-Ta** [comment]
Hi, I got this error on my new Mac M1 Pro neovim. When I installed via vim-plug: Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']} -> got E117: Unknown function: mkdp#util#install. 

After that, I opened a markdown file and ran :call mkdp#util#install() -> markdown installed, but then still got "Prebuild and node is not found"

**Comment by sturik** [comment]
Hi, similar error to Henry-Ta with my Mac M1 Pro as well. Hoping there might be a fix.

**Comment by qiaolinhan** [comment]
> it's seems the pre build is install incomplete. try `:call mkdp#util#install()` to reinstall the pre build.

This works for me on neovim, thanks.

**Comment by iscc7** [comment]
work fo me too 👍 

> it's seems the pre build is install incomplete. try `:call mkdp#util#install()` to reinstall the pre build.

**Comment by grapemix** [comment]
When I run `:call mkdp#util#install()` in nvim, I get "Unknown function: mkdp#util#install". I tried a few times and it is all the same results. But when I run the same cmd AFTER running `PlusStatus`, the cmd runs and installation is completed. Give a try.
