### ISSUE TITLE
Ability to run plugin on .txt files

### ISSUE THREAD

**Issue by BenKettlewell** [iamcco/markdown-preview.nvim#71]
There's a program I use that creates temporary text files in */tmp* while editing but the temporary file created is a .txt file. The file contains markdown and I've set the filetype in vim with `:set filetype=markdown` but vim still won't allow me to run MarkdownPreview on it.
Would it be possible to allow the plugin to be run on a custom list of filetype extensions or is there a way to work around this?
Thank you for the amazing plugin by the way! Works wonderfully! 💯

**Comment by AaAaYou** [comment]
config option:
>" set to 1, the MarkdownPreview command can be use for all files,
>" by default it can be use in markdown file
>" default: 0
>let g:mkdp_command_for_global = 0

**Comment by BenKettlewell** [comment]
@AaAaYou I'm clearly blind as a bat because I read right past that. Thank you!
