### ISSUE TITLE
在linux mint系统下使用:markdown preview没有反应的问题

### ISSUE THREAD

**Issue by AaAaYou** [iamcco/markdown-preview.nvim#72]
首先感谢作者如此棒的插件，和各位为开源社区做出的贡献。

我的电脑系统是：
>Linux frei_weili 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

我的neovim：
>NVIM v0.3.7
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-8dKHat/neovim-0.3.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-8dKHat/neovim-0.3.7/build/config -I/build/neovim-8dKHat/neovim-0.3.7/src -I/usr/include -I/build/neovim-8dKHat/neovim-0.3.7/build/src/nvim/auto -I/build/neovim-8dKHat/neovim-0.3.7/build/include
Compiled by team+vim@tracker.debian.org

我使用plug-vim安装的插件，配置如下：
>Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install_sync() }, 'for':['markdown', 'vim-plug'] }

>let g:mkdp_auto_start = 0
let g:mkdp_auto_close = 1
let g:mkdp_refresh_slow = 0
let g:mkdp_command_for_global = 0
let g:mkdp_open_to_the_world = 0
let g:mkdp_open_ip = ''
let g:mkdp_browser = 'chromium'
let g:mkdp_echo_preview_url = 0
let g:mkdp_browserfunc = ''
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1
    \ }
let g:mkdp_markdown_css = ''
let g:mkdp_highlight_css = ''
let g:mkdp_port = ''
let g:mkdp_page_title = '「${name}」'

值得一提的是，我在terminal调用浏览器使用的命令是chromium-browser。

问题阐述：
我在.md文件中，输入":MarkdownPreview"之后，并没有浏览器的同步预览出现。但是我注意到右下角出现ownpreview的提示，不知道是什么意思？

我的尝试：
之后我使用了":call mkdp#util#install()"的命令，也没有反应，我使用:plugstatus检查插件是安装成功了的。

至此，因为我是linux和vim的新手，实在是折腾不出来了。希望有大佬能帮我看看，多谢各位了。

**Comment by iamcco** [comment]
> 但是我注意到右下角出现ownpreview的提示

什么提示？

在 neovim 中执行 `:checkhealth` 看输出是什么

**Comment by AaAaYou** [comment]
出现提示是因为我映射了：namp <C-s> <Plug>MarkdownPreview，按了这个快捷键会出现ownpreview的提示。我刚试了下输入:MarkdownPreview，回车之后没有反应。

在neovim执行 :check health之后，输出以下内容，截图内容如下。
[screenshot in github](https://github.com/AaAaYou/My-vim_config/blob/master/fig/Screenshot%20from%202019-07-18%2022-23-00.png)

**Comment by iamcco** [comment]
let g:mkdp_echo_preview_url = 1

设置然后手动打开连接看看是不是可以打开

**Comment by AaAaYou** [comment]
修改设置为１之后，再次输入:MarkdownPreview。出现了Preview page: http://127.0.0.1:8588/page/1。我去浏览器输入网址之后，出现了preview的页面。非常感谢。

但是我想问一下，怎么样才可以让我在使用:MarkdownPreview之后，可以自动弹出浏览器界面呢？

**Comment by iamcco** [comment]
" a custom vim function name to open preview page
" this function will receive url as param
" default is empty
let g:mkdp_browserfunc = ''

可以先设置个函数自定义打开浏览器。

问题可能是打开浏览器的代码在你的环境不起作用，这个还得有时间再看看

**Comment by AaAaYou** [comment]
好的，非常感谢！

**Comment by iamcco** [comment]
linux 下使用 xdg-open 打开 url 的，你试下你的环境 xdg-open 能不能用。不能用的话 可以设置 let g:mkdp_browser = '' 为你可以打开的浏览器。或者用上面的 let g:mkdp_browserfunc = '' 自定义一个打开 url 的函数。

**Comment by iamcco** [comment]
又看了下你的配置 配置了let g:mkdp_browser = 'chromium', 你的环境能用 chromium 打开浏览器么，不能用的话改掉或者留空

**Comment by AaAaYou** [comment]
在我的环境下，终端是使用chromium-browser打开浏览器的。关于xdg-open是否可行，我明天再试一下吧。多谢啦！

**Comment by iamcco** [comment]
那你配置的问题

**Comment by AaAaYou** [comment]
我试着把let g:mkdp_browser = ''留空，以及设置let g:mkdp_echo_preview_url = ０，实现浏览器自动弹出了。非常感谢！

**Comment by singledoggy** [comment]
Thanks a lot!
