### ISSUE TITLE
「 」in mkdp line 89

### ISSUE THREAD

**Issue by qpmcool** [iamcco/markdown-preview.nvim#74]
although it would not affect the function, but my gvim always report an unrecognized message box. 
suggest to use "" replace it.  it works OK.

**Comment by iamcco** [comment]
I don't know what you mean

**Comment by qpmcool** [comment]
![捕获](https://user-images.githubusercontent.com/20516420/62344996-fb3b6500-b522-11e9-90f3-18bf04ee254d.PNG)
plugin/mkdp.vim line 89.  
![捕获1](https://user-images.githubusercontent.com/20516420/62345080-51a8a380-b523-11e9-933e-0b584cdc8776.PNG)
if we modify the code use "" to replace  「 」, that's would be nice.

**Comment by iamcco** [comment]
Add `let g:mkdp_page_title = '${name}'` to your vimrc. I think your vim have problem detecting the encoding of file.
