### ISSUE TITLE
Unknown function: term_start

### ISSUE THREAD

**Issue by bronzdoc** [iamcco/markdown-preview.nvim#75]
I'm following the instructions to install this plugin, I don't have yarn or npm installed.

I use Plug as my plugin manager and I'm doing the following:

```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
``` 

Then I do `:PlugInstall`

But the post update hook is failing and I can't use the plugin.

![Screen Shot 2019-08-06 at 10 20 06 AM](https://user-images.githubusercontent.com/4595174/62557256-dcdfad00-b833-11e9-9812-c3083dcee930.png)

**Comment by iamcco** [comment]
upgrade your vim and make sure it support term_start function

**Comment by bronzdoc** [comment]
Thanks @iamcco that worked 👍
