### ISSUE TITLE
Use Electron as a browser

### ISSUE THREAD

**Issue by Pifpafpouf-blip** [iamcco/markdown-preview.nvim#77]
I spent some time searching for the best web browser to use for the preview, and I found that Electron works great.
Just set `let g:mkdp_browser = 'electron'` and you're good to go!
Works perfectly with `let g:mkdp_auto_close = 1` too, while with Firefox I had some issues with that.
Btw awesome plugin!

**Comment by iamcco** [comment]
Firefox does not allow javascript to close window.
