### ISSUE TITLE
数学公式下标高亮与网络图片显示问题

### ISSUE THREAD

**Issue by Uzzaih-Lee** [iamcco/markdown-preview.nvim#79]
您好，相当棒的插件，是我一直想找的。
有两个小问题
一是在md文件的公式里，下标2会显示红色$x_1$,这个『_ 』会显示红色，不知道是我的配置原因还是怎样，我使用neovim在item2中编写
二是关于图片链接，现在只是支持本地图片显示是么，我发现图床上的图片未能正常显示
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/49584530/62958186-c388c300-be28-11e9-9bd9-9221dcd71779.png">

**Comment by iamcco** [comment]
关于第一个问题，这个插件不会修改或增加你的 vim 的任何高亮相关的东西。第二个问题，可以显示网络图片，图片显示不出来自己检查图片连接是否正确以及你的网络是否能够打开该图片
