### ISSUE TITLE
E117: Unknown function: mkdp#nvim#rpc#get_command

### ISSUE THREAD

**Issue by nicksunyang** [iamcco/markdown-preview.nvim#82]

**Comment by nicksunyang** [comment]
我在用gvim的时候报这个错

**Comment by iamcco** [comment]
没法复现，检查插件是否安装完整

**Comment by nicksunyang** [comment]
我安装是手动到app下运行./install.sh





| |
孙阳阳
邮箱：zhysun1994@163.com
|

签名由 网易邮箱大师 定制

On 08/15/2019 17:31, 年糕小豆汤 wrote:

没法复现，检查插件是否安装完整

**Comment by iamcco** [comment]
查看你的 gvim 的版本

**Comment by nicksunyang** [comment]
应该是版本的问题，谢了




| |
孙阳阳
邮箱：zhysun1994@163.com
|

签名由 网易邮箱大师 定制

On 08/15/2019 17:34, 年糕小豆汤 wrote:

查看你的 gvim 的版本
