### ISSUE TITLE
:MarkdownPreview执行之后没有反应

### ISSUE THREAD

**Issue by kjhuanhao** [iamcco/markdown-preview.nvim#83]
重装和用npm还有yarn的方式都不行

**Comment by iamcco** [comment]
怎么装的，怎么配置的，什么系统，vim什么版本，运行命令后用 `:mess` 看有没有报错

**Comment by kjhuanhao** [comment]
## 安装方式
用的这条安装插件
`Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }`
## 配置
还没有配置
## 系统
我是manjaro系统
## vim版本
vim是8.1.1776 

执行mess之后提示这个：
> 简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>

**Comment by iamcco** [comment]
试下 `xdg-open “https://github.com/iamcco/markdown-preview.nvim/issues/83”`能不能打开浏览器。

配置 `let g:mkdp_echo_preview_url = 1`，然后 markdown 文件中执行命令，看看有没有显示 url，如果显示 url，浏览器打开能不能访问

**Comment by kjhuanhao** [comment]
第一条命令打不开浏览器
然后配置令那个vim之后也没有显示url

**Comment by iamcco** [comment]
可能预编译的二进制包在你的系统用不了，使用 `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }` 看看

**Comment by kjhuanhao** [comment]
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install' }成功解决
