### ISSUE TITLE
it would close the whole browser (ff) instace when exit vim.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [iamcco/markdown-preview.nvim#88]
once opened the living preview page by it, then exit the vim, the whole browser instance would close - even those pages (tabs/windows) were not open by it.
that's a risk to use this ...

ubuntu.
ff.
vim8.1

**Comment by Shane-XB-Qian** [comment]
unless the browser was opened by myself.
was there some trick to use this ?

**Comment by iamcco** [comment]
Browser should not close all windows, it just run `window.close()` command when close window. It can not control the behavior of browser.

**Comment by Shane-XB-Qian** [comment]
"windows" means browser's windows - or just say the firefox instance down.
ok - whatever - i just added a 'confirm' func to myself, so it should be reduce the risk .. :)
thank your answer. let it be. :)

**Comment by Shane-XB-Qian** [comment]
yes, i had set. 
it happened when vim exit.
i did not check your code, but maybe you got the browser id (or sth like that), then close or kill by id later ? if so, that's why it did not impact if i open the ff by myself.
or whatever, as you said, maybe just depends on browser behavior itself.

**Comment by iamcco** [comment]
`window.close()` should just close the current window.

https://developer.mozilla.org/en-US/docs/Web/API/Window/close#Closing_the_current_window

**Comment by iamcco** [comment]
`let g:mkdp_auto_close = 0` still close firefox?

**Comment by iamcco** [comment]
It should fix now.

**Comment by Shane-XB-Qian** [comment]
probably yes, not sure.
i saw you changed to 'spawn'.
