### ISSUE TITLE
說幾個情況,1-安裝的時候網絡問題;2-yarn過程中卡住;3-<Plug>映射慢;環境是WIN7

### ISSUE THREAD

**Issue by eternalcyan** [iamcco/markdown-preview.nvim#90]
### `環境: WIN7SP1 x64 VIM8.1`

- 發現用Plug安裝的時候居然要開網絡全局代理,否則clone不下來,很奇怪,我也不知道為什麼,其他插件都能download下來.等了十幾分鐘都不行,一點動靜沒有.然後重開就彈出以下錯誤.
![](https://github.com/eternalcyan/cyans/blob/master/2019-10-12_165222.png?raw=true)
  
- 強行從github上下載下來,然後解壓,用Plug,發現這貨不支持同名文件夾內容的檢查,彈出以下內容.
![](https://github.com/eternalcyan/cyans/blob/master/2019-10-12_170448.png?raw=true)
  
- 最後實在沒法子,開全局代理試試,結果神奇的成功了.但並不完美,出現以下異常信息,不甚解.
![](https://github.com/eternalcyan/cyans/blob/master/2019-10-12_171224.png?raw=true)
  
> 然後重開VIM重載配置,開啟`:MarkdownPreview`,沒用,後來從`cmd`裡進到`app`中`yarn install`才搞定.我懷疑可能提示那個錯誤就是因為沒有成功`yarn`.但過程中彈出過一次cmd的窗口,字體很奇葩,好像顯示yarn什麼東西,具體沒看清,閃一下就沒了.
![](https://github.com/eternalcyan/cyans/blob/master/yarn%E5%AE%89%E8%A3%9D.png?raw=true)  

>最後終於能成功愉快的實時預覽了!但還發現個小問題,就是用`nmap <M-p> <Plug>MarkdownPreview`這樣的快捷鍵要比`nmap <M-p> :MarkdownPreview<CR>`慢很多很多!用後者幾乎瞬間就打開分頁,前者等個10秒左右!Plug內部在解析什麼東西導致的?真的奇怪,求解釋.  

>***PS:之前我不是用的Plug裝的,是直接把目錄下對應的文件甩到VIM文件夾中,然後yarn了一下,這次用Plug裝後發現了一些問題,以上.***

**Comment by eternalcyan** [comment]
github庫裡的圖怎麼鏈接不出來...?

**Comment by eternalcyan** [comment]
改了下圖鏈地址,好了.

**Comment by eternalcyan** [comment]
另外一提,用的是這個配置命令.  
`Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }`

**Comment by iamcco** [comment]
看不到图片

**Comment by eternalcyan** [comment]
> 看不到图片

現在呢?我之前的庫是私有的,可能是因為這個原因,沒怎麼用過github...現在改成public了.應該能看到了吧,我用FF試了下,沒登錄賬號能看到圖.

**Comment by iamcco** [comment]
vim-plug 安装不成功的问题有可能是存在你之前手动安装的文件 https://github.com/junegunn/vim-plug/issues/516

hook 失败这个，没有具体错误很难定位，改成 `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }` 试试。

**Comment by eternalcyan** [comment]
> vim-plug 安装不成功的问题有可能是存在你之前手动安装的文件 [junegunn/vim-plug#516](https://github.com/junegunn/vim-plug/issues/516)
> 
> hook 失败这个，没有具体错误很难定位，改成 `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }` 试试。

下面我回復有說哦,我就是用的這個,因為我git和yarn環境都安好了,所以就直接用了下面這個.然後沒`yarn`成功,但是`clone`成功了,我自己用`cmd`去app裡面`yarn install`了一遍才能用的.

**Comment by eternalcyan** [comment]
> vim-plug 安装不成功的问题有可能是存在你之前手动安装的文件 [junegunn/vim-plug#516](https://github.com/junegunn/vim-plug/issues/516)
> 
> hook 失败这个，没有具体错误很难定位，改成 `Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }` 试试。

另外我安裝之前有清理過的,之前的文件都清理了,然後就是`vim/plugged`裡面也刪除了`markdown-preview.nvim`文件夾了,也`PlugClean`過,兩個效果都一樣的,`PlugClean`也是清理掉`plugged`文件夾裡面的插件目錄. 我的意思是不用全局代理翻出去下不下來,很奇怪,開了全局代理成功下下來了,但是`yarn`失敗,上面說的,重新手動`yarn`了一次就能用了,不知道是不是後面的`do cd app & yarn install`沒起作用.

**Comment by eternalcyan** [comment]
另外問下,你是在linux環境下測試的嗎?安裝過程.

**Comment by eternalcyan** [comment]
我看了下plug裡面的用法,是不是你命令寫錯了? `{'do': 'cd app | yarn install'}` 這樣吧?用`&&`在vim環境下測試命令無法執行.命令連接符是`|`

**Comment by iamcco** [comment]
应该是 `&&`，这里是执行的shell脚本，我是macos/linux/win10下测试的

**Comment by iamcco** [comment]
对了你上面是用一个 `&` 改成两个 `&&` 试试，正确的应该是两个，readme错了

**Comment by eternalcyan** [comment]
> 对了你上面是用一个 `&` 改成两个 `&&` 试试，正确的应该是两个，readme错了

額,原來是兩個啊,哈哈哈,怪不得我說怎麼看起來怪怪的.
對了,那個映射前面加`<Plug>`怎麼會變的很慢呢?你知道原因嗎?就是用`nmap <Plug>MarkdownPreview`超慢!

**Comment by eternalcyan** [comment]
剛測試了,兩個`&&`不成功,一樣顯示`post-update`云云,然後改了`\|`,`PlugInstall`是通過了,但一樣沒有`yarn`成功.`PlugInstall`過程中閃出一個黑色的`cmd`窗口,字體很怪,瞬間又消失了,好像是顯示`yarn`的字樣,不知道為什麼沒成功.
![](https://github.com/eternalcyan/cyans/blob/master/2019-10-12_215650.png?raw=true)
> 上面是`PlugInstall`顯示安裝完成的圖.
可能是`Plug`在傳遞命令的時候出了什麼問題,難道是相對路徑出錯?沒搞懂,因為馬上消失了,也沒法通過反饋分析原因.沒`yarn`成功的話VIM輸入命令會閃過一個紅色的出錯指令,看不清,太快,然後再次輸入就沒反應了,手動`yarn`之後就正常了.問題就是這個`do`後面的命令沒成功執行.

**Comment by iamcco** [comment]
win7试了，一个还是两个&&都没有问题，<Plug>MarkdownPreview慢的也没法复现

**Comment by eternalcyan** [comment]
> win7试了，一个还是两个&&都没有问题，`<Plug>MarkdownPreview` 慢的也没法复现

這就怪了,難道是我個人系統和硬件環境導致的差異?不管了,反正能用就行了,只是有點小糾結,多謝指教!

**Comment by eternalcyan** [comment]
希望能給跟我有一樣問題的人一點經驗吧.結貼
