### ISSUE TITLE
Installing through dein without yarn?

### ISSUE THREAD

**Issue by jyscao** [iamcco/markdown-preview.nvim#91]
The installation instruction for dein is the following:

```viml
call dein#add('iamcco/markdown-preview.nvim', {'on_ft': ['markdown', 'pandoc.markdown', 'rmd'],
					\ 'build': 'cd app & yarn install' })
```

However I do not have yarn, and if possible would rather not install it just to build a single vim plugin.

Is there an equivalent pre-built for dein like for vim-plug?

Failing that, I do have npm though, so would `cd app & npm install` work in this case?

**Comment by iamcco** [comment]
You can just replace yarn to npm, it should just work.

I don't know if dein support hook to use the plugin function, if yes you can add `call mkdp#util#install()` hook to use pre-build bundle. Or you can run `call mkdp#util#install()` after install the plugin.

**Comment by jyscao** [comment]
Great, I tried `npm install` and it indeed worked.

Also, I looked at the docs for vim-plug, but couldn't find any mention of what it means for plug's post-update-hook to take a table value, as in `{ 'do': { -> mkdp#util#install() } }`. Would you mind explaining that to me?

Ideally, I'd also want to make using the pre-build option available via `dein`, which I believe can be done with `dein#call_hook('post_source')`.

**Comment by iamcco** [comment]
Take a look at https://github.com/junegunn/vim-plug#post-update-hooks

**Comment by jyscao** [comment]
hmm okay, thanks for the tip
