### ISSUE TITLE
page-header option and an exception

### ISSUE THREAD

**Issue by MapleHe** [iamcco/markdown-preview.nvim#93]
## page-header

How to disable page-header and margin line? Especially the page-header (the "README" title and it's background in the following picture). I noticed that there is no header in the .gif example in your `README.md`.

I'm not familiar with js and css, but I've tried to set my own markdown css, the margin line disappear but the header(title) remained. I also tried to set `let g:mkdp_page_title = ''` to void but nothing changed.

![image](https://user-images.githubusercontent.com/18021898/67160993-f0a5a480-f388-11e9-8714-cdd03bb04695.png)

## exception

I encountered this exception. Sorry that I have no log file because this exception doesn't appear every time. (tried with your README.md). What may be the cause? I'm sure that I use the `.nvim` plugin instead of your former `.vim` one and I did not found the file `sequence-diagram.js` mentioned in the picture. There is only `sequence-diagram-min.js` file in `app/_static/` folder.

<img width="958" alt="Screen Shot 2019-10-20 at 22 00 10" src="https://user-images.githubusercontent.com/18021898/67161037-382c3080-f389-11e9-8ea0-ddb974f6b980.png">

**Comment by iamcco** [comment]
add  this to you custom css
``` css
#page-header {
  display: none;
}
```

the exception only display when you open browser console, because it will look for the source map file for debug and there is no source map file.
