### ISSUE TITLE
不支持mermaid的状态图（stateDiagram)

### ISSUE THREAD

**Issue by GPN211314** [iamcco/markdown-preview.nvim#96]
我看这里没有stateDiagram不知道是不是这的原因？
我不清楚插件的执行过程，只是猜的
![image](https://user-images.githubusercontent.com/38633718/67762414-562c1c00-fa80-11e9-8e02-fd0e832a1724.png)

**Comment by iamcco** [comment]
stateDiagram 新出的么，新出的还没支持吧，需要升级版本

**Comment by iamcco** [comment]
支持了
