### ISSUE TITLE
你好,能不能新增一個瀏覽器中直接預覽的功能?

### ISSUE THREAD

**Issue by eternalcyan** [iamcco/markdown-preview.nvim#97]
如標題所述,就是說在瀏覽器打開一個來自網絡或本地的.md或.txt文本的時候,可以通過這個插件做一個Markdown到HTML的轉換,就是說從VIM傳遞數據改成CHROME本身自己的數據,而不需要再安裝一個瀏覽器插件什麼的的,這樣會很方便,而且也和VIM中預覽的佈局一致.這樣的新功能能增加一個嗎?應該不是很麻煩吧?謝謝~

**Comment by iamcco** [comment]
不是很懂你这个描述

**Comment by eternalcyan** [comment]
> 不是很懂你这个描述

就是說用CHROME等瀏覽器打開Markdown或者TXT文件,可以用這個插件直接進行HTML代碼的轉化然後瀏覽,不需要通過VIM軟件.比如Github上的README.MD,點raw按鈕以後,形成純文本,並沒有轉成HTML,然後可以通過這個插件轉一下直接瀏覽,再或者用瀏覽器打開的純文本,具有markdown的代碼,也可以轉,類似VIM打開的文件一樣的效果,只不過不需要通過VIM.

**Comment by iamcco** [comment]
我想你需要的是一个 chrome 插件，试试这个https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk?hl=zh-CN

**Comment by eternalcyan** [comment]
感謝回復幫助!插件不錯

**Comment by eternalcyan** [comment]
> 我想你需要的是一个 chrome 插件，试试这个https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk?hl=zh-CN

謝了
