### ISSUE TITLE
能自动提示显示MarkdownPreview,但是浏览器上没有跳转

### ISSUE THREAD

**Issue by bladelei** [iamcco/markdown-preview.nvim#99]
PlugInstall 显示安装了插件，不知道为啥命令跑后浏览器上不显示， 系统是 manjaro deepin

**Comment by iamcco** [comment]
没错误提示么，怎么配置的

**Comment by bladelei** [comment]
> 没错误提示么，怎么配置的

嗯嗯，没见到提示，我是直接把Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  } 放到nvim/init.vim 对应位置上，然后打开nvim , 运行PlugInstall 然后就安装完了

**Comment by iamcco** [comment]
根据这个 issue 试下

**Comment by iamcco** [comment]
https://github.com/iamcco/markdown-preview.nvim/issues/72
